// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsActiveSubscriptionsByTier = `-- name: AnalyticsActiveSubscriptionsByTier :many
SELECT t.tier_name, t.display_name_en, COUNT(us.id)::bigint AS count
FROM subscription_tiers t
LEFT JOIN user_subscriptions us ON us.tier_name = t.tier_name AND us.is_active = true
GROUP BY t.tier_name, t.display_name_en ORDER BY t.tier_name
`

type AnalyticsActiveSubscriptionsByTierRow struct {
	TierName      string `json:"tier_name"`
	DisplayNameEn string `json:"display_name_en"`
	Count         int64  `json:"count"`
}

func (q *Queries) AnalyticsActiveSubscriptionsByTier(ctx context.Context) ([]AnalyticsActiveSubscriptionsByTierRow, error) {
	rows, err := q.db.Query(ctx, analyticsActiveSubscriptionsByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsActiveSubscriptionsByTierRow
	for rows.Next() {
		var i AnalyticsActiveSubscriptionsByTierRow
		if err := rows.Scan(&i.TierName, &i.DisplayNameEn, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCountActiveSessions = `-- name: AnalyticsCountActiveSessions :one
SELECT COUNT(*)::bigint AS count FROM user_sessions WHERE expires_at > now()
`

func (q *Queries) AnalyticsCountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsCountActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analyticsCountBidsByDay = `-- name: AnalyticsCountBidsByDay :many
SELECT bucket::date, SUM(value)::bigint AS value
FROM (
  SELECT date_trunc('day', sb.created_at) AS bucket, 1 AS value FROM sell_bids sb
   WHERE sb.created_at >= $1 AND sb.created_at < $2
  UNION ALL
  SELECT date_trunc('day', so.created_at), 1 FROM supply_offers so
   WHERE so.created_at >= $1 AND so.created_at < $2
) x GROUP BY bucket ORDER BY bucket
`

type AnalyticsCountBidsByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsCountBidsByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsCountBidsByDay(ctx context.Context, arg AnalyticsCountBidsByDayParams) ([]AnalyticsCountBidsByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCountBidsByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCountBidsByDayRow
	for rows.Next() {
		var i AnalyticsCountBidsByDayRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCountBuyRequestsByDay = `-- name: AnalyticsCountBuyRequestsByDay :many
SELECT date_trunc('day', created_at)::date AS bucket, COUNT(*)::bigint AS value
FROM buy_requests
WHERE created_at >= $1 AND created_at < $2
GROUP BY 1 ORDER BY 1
`

type AnalyticsCountBuyRequestsByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsCountBuyRequestsByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsCountBuyRequestsByDay(ctx context.Context, arg AnalyticsCountBuyRequestsByDayParams) ([]AnalyticsCountBuyRequestsByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCountBuyRequestsByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCountBuyRequestsByDayRow
	for rows.Next() {
		var i AnalyticsCountBuyRequestsByDayRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCountClosedAuctionsByDay = `-- name: AnalyticsCountClosedAuctionsByDay :many
SELECT date_trunc('day', end_time)::date AS bucket, COUNT(*)::bigint AS value
FROM sell_auctions
WHERE status IN ('expired','winner_selected') AND end_time >= $1 AND end_time < $2
GROUP BY 1 ORDER BY 1
`

type AnalyticsCountClosedAuctionsByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsCountClosedAuctionsByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsCountClosedAuctionsByDay(ctx context.Context, arg AnalyticsCountClosedAuctionsByDayParams) ([]AnalyticsCountClosedAuctionsByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCountClosedAuctionsByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCountClosedAuctionsByDayRow
	for rows.Next() {
		var i AnalyticsCountClosedAuctionsByDayRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCountFailedLoginsByDay = `-- name: AnalyticsCountFailedLoginsByDay :many
SELECT date_trunc('day', login_at)::date AS bucket, COUNT(*)::bigint AS value
FROM login_history
WHERE success = false AND login_at >= $1 AND login_at < $2
GROUP BY 1 ORDER BY 1
`

type AnalyticsCountFailedLoginsByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsCountFailedLoginsByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsCountFailedLoginsByDay(ctx context.Context, arg AnalyticsCountFailedLoginsByDayParams) ([]AnalyticsCountFailedLoginsByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCountFailedLoginsByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCountFailedLoginsByDayRow
	for rows.Next() {
		var i AnalyticsCountFailedLoginsByDayRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCountIssuesByDay = `-- name: AnalyticsCountIssuesByDay :many
SELECT date_trunc('day', created_at)::date AS bucket, COUNT(*)::bigint AS value
FROM issues
WHERE created_at >= $1 AND created_at < $2
GROUP BY 1 ORDER BY 1
`

type AnalyticsCountIssuesByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsCountIssuesByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsCountIssuesByDay(ctx context.Context, arg AnalyticsCountIssuesByDayParams) ([]AnalyticsCountIssuesByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCountIssuesByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCountIssuesByDayRow
	for rows.Next() {
		var i AnalyticsCountIssuesByDayRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsCountOpenIssues = `-- name: AnalyticsCountOpenIssues :one
SELECT COUNT(*)::bigint AS count FROM issues WHERE status = 'open'
`

func (q *Queries) AnalyticsCountOpenIssues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsCountOpenIssues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analyticsCountUsersByDay = `-- name: AnalyticsCountUsersByDay :many
SELECT date_trunc('day', created_at)::date AS bucket, COUNT(*)::bigint AS value
FROM users
WHERE created_at >= $1 AND created_at < $2
GROUP BY 1 ORDER BY 1
`

type AnalyticsCountUsersByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsCountUsersByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsCountUsersByDay(ctx context.Context, arg AnalyticsCountUsersByDayParams) ([]AnalyticsCountUsersByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsCountUsersByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsCountUsersByDayRow
	for rows.Next() {
		var i AnalyticsCountUsersByDayRow
		if err := rows.Scan(&i.Bucket, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsInactiveSubscriptionsCount = `-- name: AnalyticsInactiveSubscriptionsCount :one
SELECT COUNT(*)::bigint AS count FROM user_subscriptions WHERE is_active = false
`

func (q *Queries) AnalyticsInactiveSubscriptionsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsInactiveSubscriptionsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const analyticsIssuesByStatus = `-- name: AnalyticsIssuesByStatus :many
SELECT status, COUNT(*)::bigint AS count
FROM issues
WHERE created_at >= $1 AND created_at < $2
GROUP BY status ORDER BY count DESC
`

type AnalyticsIssuesByStatusParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsIssuesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) AnalyticsIssuesByStatus(ctx context.Context, arg AnalyticsIssuesByStatusParams) ([]AnalyticsIssuesByStatusRow, error) {
	rows, err := q.db.Query(ctx, analyticsIssuesByStatus, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsIssuesByStatusRow
	for rows.Next() {
		var i AnalyticsIssuesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsOrdersGMVByDay = `-- name: AnalyticsOrdersGMVByDay :many
SELECT date_trunc('day', created_at)::date AS bucket,
       COUNT(*)::bigint AS orders,
       COALESCE(SUM(final_price * quantity), 0)::numeric AS gmv
FROM orders
WHERE created_at >= $1 AND created_at < $2
GROUP BY 1 ORDER BY 1
`

type AnalyticsOrdersGMVByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsOrdersGMVByDayRow struct {
	Bucket pgtype.Date    `json:"bucket"`
	Orders int64          `json:"orders"`
	Gmv    pgtype.Numeric `json:"gmv"`
}

func (q *Queries) AnalyticsOrdersGMVByDay(ctx context.Context, arg AnalyticsOrdersGMVByDayParams) ([]AnalyticsOrdersGMVByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsOrdersGMVByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsOrdersGMVByDayRow
	for rows.Next() {
		var i AnalyticsOrdersGMVByDayRow
		if err := rows.Scan(&i.Bucket, &i.Orders, &i.Gmv); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsOverviewOrders = `-- name: AnalyticsOverviewOrders :one
SELECT
  COUNT(*)::bigint AS count,
  COALESCE(SUM(final_price * quantity), 0)::numeric AS gmv
FROM orders
WHERE created_at >= $1 AND created_at < $2
`

type AnalyticsOverviewOrdersParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsOverviewOrdersRow struct {
	Count int64          `json:"count"`
	Gmv   pgtype.Numeric `json:"gmv"`
}

func (q *Queries) AnalyticsOverviewOrders(ctx context.Context, arg AnalyticsOverviewOrdersParams) (AnalyticsOverviewOrdersRow, error) {
	row := q.db.QueryRow(ctx, analyticsOverviewOrders, arg.FromTime, arg.ToTime)
	var i AnalyticsOverviewOrdersRow
	err := row.Scan(&i.Count, &i.Gmv)
	return i, err
}

const analyticsOverviewUsers = `-- name: AnalyticsOverviewUsers :one
SELECT
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE created_at >= $1 AND created_at < $2)::bigint AS new_in_range
FROM users
`

type AnalyticsOverviewUsersParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsOverviewUsersRow struct {
	Total      int64 `json:"total"`
	NewInRange int64 `json:"new_in_range"`
}

func (q *Queries) AnalyticsOverviewUsers(ctx context.Context, arg AnalyticsOverviewUsersParams) (AnalyticsOverviewUsersRow, error) {
	row := q.db.QueryRow(ctx, analyticsOverviewUsers, arg.FromTime, arg.ToTime)
	var i AnalyticsOverviewUsersRow
	err := row.Scan(&i.Total, &i.NewInRange)
	return i, err
}

const analyticsProfileCompletionRatio = `-- name: AnalyticsProfileCompletionRatio :one
SELECT
  COUNT(*) FILTER (WHERE status IN ('pending_review','active'))::bigint AS completed,
  COUNT(*)::bigint AS total
FROM users
`

type AnalyticsProfileCompletionRatioRow struct {
	Completed int64 `json:"completed"`
	Total     int64 `json:"total"`
}

func (q *Queries) AnalyticsProfileCompletionRatio(ctx context.Context) (AnalyticsProfileCompletionRatioRow, error) {
	row := q.db.QueryRow(ctx, analyticsProfileCompletionRatio)
	var i AnalyticsProfileCompletionRatioRow
	err := row.Scan(&i.Completed, &i.Total)
	return i, err
}

const analyticsUsersByInterest = `-- name: AnalyticsUsersByInterest :many
SELECT
  u.public_id,
  u.name,
  u.phone,
  u.status,
  u.created_at
FROM users u
JOIN user_interests ui ON ui.user_id = u.id
WHERE ui.interest_id = $1
ORDER BY u.created_at DESC
`

type AnalyticsUsersByInterestRow struct {
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	Phone     pgtype.Text        `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AnalyticsUsersByInterest(ctx context.Context, interestID int32) ([]AnalyticsUsersByInterestRow, error) {
	rows, err := q.db.Query(ctx, analyticsUsersByInterest, interestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsUsersByInterestRow
	for rows.Next() {
		var i AnalyticsUsersByInterestRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Name,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsUsersBySource = `-- name: AnalyticsUsersBySource :many
SELECT signup_source AS source, COUNT(*)::bigint AS count
FROM users
WHERE created_at >= $1 AND created_at < $2
GROUP BY signup_source
ORDER BY count DESC
`

type AnalyticsUsersBySourceParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsUsersBySourceRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

func (q *Queries) AnalyticsUsersBySource(ctx context.Context, arg AnalyticsUsersBySourceParams) ([]AnalyticsUsersBySourceRow, error) {
	rows, err := q.db.Query(ctx, analyticsUsersBySource, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsUsersBySourceRow
	for rows.Next() {
		var i AnalyticsUsersBySourceRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsUsersBySourceByDay = `-- name: AnalyticsUsersBySourceByDay :many
SELECT date_trunc('day', created_at)::date AS bucket,
       signup_source AS source,
       COUNT(*)::bigint AS value
FROM users
WHERE created_at >= $1 AND created_at < $2
GROUP BY bucket, signup_source
ORDER BY bucket, signup_source
`

type AnalyticsUsersBySourceByDayParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AnalyticsUsersBySourceByDayRow struct {
	Bucket pgtype.Date `json:"bucket"`
	Source string      `json:"source"`
	Value  int64       `json:"value"`
}

func (q *Queries) AnalyticsUsersBySourceByDay(ctx context.Context, arg AnalyticsUsersBySourceByDayParams) ([]AnalyticsUsersBySourceByDayRow, error) {
	rows, err := q.db.Query(ctx, analyticsUsersBySourceByDay, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsUsersBySourceByDayRow
	for rows.Next() {
		var i AnalyticsUsersBySourceByDayRow
		if err := rows.Scan(&i.Bucket, &i.Source, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsUsersByStatus = `-- name: AnalyticsUsersByStatus :many
SELECT status, COUNT(*)::bigint AS count FROM users GROUP BY status ORDER BY count DESC
`

type AnalyticsUsersByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) AnalyticsUsersByStatus(ctx context.Context) ([]AnalyticsUsersByStatusRow, error) {
	rows, err := q.db.Query(ctx, analyticsUsersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsUsersByStatusRow
	for rows.Next() {
		var i AnalyticsUsersByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsUsersCountByInterest = `-- name: AnalyticsUsersCountByInterest :many
SELECT
  i.id,
  i.name_ar,
  i.name_en,
  COUNT(ui.user_id)::bigint AS count
FROM interests i
LEFT JOIN user_interests ui ON ui.interest_id = i.id
WHERE i.is_active = TRUE
GROUP BY i.id, i.name_ar, i.name_en
ORDER BY count DESC, i.name_ar
`

type AnalyticsUsersCountByInterestRow struct {
	ID     int32       `json:"id"`
	NameAr string      `json:"name_ar"`
	NameEn pgtype.Text `json:"name_en"`
	Count  int64       `json:"count"`
}

func (q *Queries) AnalyticsUsersCountByInterest(ctx context.Context) ([]AnalyticsUsersCountByInterestRow, error) {
	rows, err := q.db.Query(ctx, analyticsUsersCountByInterest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsUsersCountByInterestRow
	for rows.Next() {
		var i AnalyticsUsersCountByInterestRow
		if err := rows.Scan(
			&i.ID,
			&i.NameAr,
			&i.NameEn,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
