// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, updated_at, updated_by_admin_id FROM app_settings WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedByAdminID,
	)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at, updated_by_admin_id FROM app_settings ORDER BY key
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.Query(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedByAdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :one
INSERT INTO app_settings (key, value, updated_by_admin_id)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_by_admin_id = EXCLUDED.updated_by_admin_id,
    updated_at = NOW()
RETURNING key, value, updated_at, updated_by_admin_id
`

type UpsertAppSettingParams struct {
	Key              string      `json:"key"`
	Value            string      `json:"value"`
	UpdatedByAdminID pgtype.Int4 `json:"updated_by_admin_id"`
}

// Keys are whitelisted in the handler; this is not a general-purpose store.
func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertAppSetting, arg.Key, arg.Value, arg.UpdatedByAdminID)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedByAdminID,
	)
	return i, err
}
