// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: buy_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBuyRequest = `-- name: CancelBuyRequest :exec
UPDATE buy_requests SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CancelBuyRequest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelBuyRequest, id)
	return err
}

const countActiveBuyRequests = `-- name: CountActiveBuyRequests :one
SELECT COUNT(*) FROM buy_requests
WHERE status = 'active' AND end_time > NOW()
  AND ($1::int IS NULL OR owner_id != $1::int)
  AND ($2::int[] IS NULL OR id NOT IN (
    SELECT so.buy_request_id FROM supply_offers so WHERE so.supplier_id = $3::int
  ))
`

type CountActiveBuyRequestsParams struct {
	ExcludeOwnerID         int32   `json:"exclude_owner_id"`
	ExcludeOfferedRequests []int32 `json:"exclude_offered_requests"`
	UserID                 int32   `json:"user_id"`
}

func (q *Queries) CountActiveBuyRequests(ctx context.Context, arg CountActiveBuyRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBuyRequests, arg.ExcludeOwnerID, arg.ExcludeOfferedRequests, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBuyRequestsByOwner = `-- name: CountBuyRequestsByOwner :one
SELECT COUNT(*) FROM buy_requests WHERE owner_id = $1
`

func (q *Queries) CountBuyRequestsByOwner(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countBuyRequestsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonthlyBuyCancellations = `-- name: CountMonthlyBuyCancellations :one
SELECT COUNT(*) FROM buy_requests
WHERE owner_id = $1 AND status = 'cancelled'
  AND updated_at >= date_trunc('month', NOW())
`

func (q *Queries) CountMonthlyBuyCancellations(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countMonthlyBuyCancellations, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchBuyRequests = `-- name: CountSearchBuyRequests :one
SELECT COUNT(*) FROM buy_requests
WHERE status = 'active' AND end_time > NOW()
  AND title ILIKE '%' || $1::text || '%'
  AND ($2::int IS NULL OR owner_id != $2::int)
  AND ($3::int[] IS NULL OR id NOT IN (
    SELECT so.buy_request_id FROM supply_offers so WHERE so.supplier_id = $4::int
  ))
`

type CountSearchBuyRequestsParams struct {
	SearchTerm             string  `json:"search_term"`
	ExcludeOwnerID         int32   `json:"exclude_owner_id"`
	ExcludeOfferedRequests []int32 `json:"exclude_offered_requests"`
	UserID                 int32   `json:"user_id"`
}

func (q *Queries) CountSearchBuyRequests(ctx context.Context, arg CountSearchBuyRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchBuyRequests,
		arg.SearchTerm,
		arg.ExcludeOwnerID,
		arg.ExcludeOfferedRequests,
		arg.UserID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuyRequest = `-- name: CreateBuyRequest :one
INSERT INTO buy_requests (owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, end_time, owner_name, region_name, interest_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at
`

type CreateBuyRequestParams struct {
	OwnerID       int32              `json:"owner_id"`
	RegionID      int32              `json:"region_id"`
	InterestID    int32              `json:"interest_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	ImageUrl      string             `json:"image_url"`
	Unit          string             `json:"unit"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	BuyAllFromOne bool               `json:"buy_all_from_one"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	OwnerName     string             `json:"owner_name"`
	RegionName    string             `json:"region_name"`
	InterestName  string             `json:"interest_name"`
}

func (q *Queries) CreateBuyRequest(ctx context.Context, arg CreateBuyRequestParams) (BuyRequest, error) {
	row := q.db.QueryRow(ctx, createBuyRequest,
		arg.OwnerID,
		arg.RegionID,
		arg.InterestID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Unit,
		arg.Quantity,
		arg.BuyAllFromOne,
		arg.EndTime,
		arg.OwnerName,
		arg.RegionName,
		arg.InterestName,
	)
	var i BuyRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.BuyAllFromOne,
		&i.OfferCount,
		&i.AcceptedOfferCount,
		&i.FulfilledQuantity,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
	)
	return i, err
}

const getBuyRequestByID = `-- name: GetBuyRequestByID :one
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests WHERE id = $1
`

func (q *Queries) GetBuyRequestByID(ctx context.Context, id int32) (BuyRequest, error) {
	row := q.db.QueryRow(ctx, getBuyRequestByID, id)
	var i BuyRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.BuyAllFromOne,
		&i.OfferCount,
		&i.AcceptedOfferCount,
		&i.FulfilledQuantity,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
	)
	return i, err
}

const getBuyRequestByPublicID = `-- name: GetBuyRequestByPublicID :one
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests WHERE public_id = $1
`

func (q *Queries) GetBuyRequestByPublicID(ctx context.Context, publicID pgtype.UUID) (BuyRequest, error) {
	row := q.db.QueryRow(ctx, getBuyRequestByPublicID, publicID)
	var i BuyRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.BuyAllFromOne,
		&i.OfferCount,
		&i.AcceptedOfferCount,
		&i.FulfilledQuantity,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
	)
	return i, err
}

const getBuyRequestByPublicIDForUpdate = `-- name: GetBuyRequestByPublicIDForUpdate :one
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests WHERE public_id = $1 FOR UPDATE
`

func (q *Queries) GetBuyRequestByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (BuyRequest, error) {
	row := q.db.QueryRow(ctx, getBuyRequestByPublicIDForUpdate, publicID)
	var i BuyRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.BuyAllFromOne,
		&i.OfferCount,
		&i.AcceptedOfferCount,
		&i.FulfilledQuantity,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
	)
	return i, err
}

const getExpiredActiveBuyRequests = `-- name: GetExpiredActiveBuyRequests :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests WHERE status = 'active' AND end_time <= NOW()
`

func (q *Queries) GetExpiredActiveBuyRequests(ctx context.Context) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, getExpiredActiveBuyRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPendingSelectionBuyRequests = `-- name: GetExpiredPendingSelectionBuyRequests :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests
WHERE status = 'pending_selection' AND end_time + INTERVAL '1 hour' <= NOW()
`

func (q *Queries) GetExpiredPendingSelectionBuyRequests(ctx context.Context) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, getExpiredPendingSelectionBuyRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMotivatableActiveBuyRequests = `-- name: GetMotivatableActiveBuyRequests :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests
WHERE status = 'active'
  AND end_time > NOW()
  AND end_time <= NOW() + INTERVAL '30 minutes'
  AND (last_motivation_sent_at IS NULL OR last_motivation_sent_at < NOW() - INTERVAL '20 minutes')
`

func (q *Queries) GetMotivatableActiveBuyRequests(ctx context.Context) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, getMotivatableActiveBuyRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSoonExpiringSelectionBuyRequests = `-- name: GetSoonExpiringSelectionBuyRequests :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests
WHERE status = 'pending_selection'
  AND end_time + INTERVAL '50 minutes' <= NOW()
  AND end_time + INTERVAL '1 hour' > NOW()
`

func (q *Queries) GetSoonExpiringSelectionBuyRequests(ctx context.Context) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, getSoonExpiringSelectionBuyRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnnotifiedActiveBuyRequests = `-- name: GetUnnotifiedActiveBuyRequests :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests
WHERE status = 'active' AND notified_at IS NULL
`

func (q *Queries) GetUnnotifiedActiveBuyRequests(ctx context.Context) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, getUnnotifiedActiveBuyRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBuyRequestAcceptedOfferCount = `-- name: IncrementBuyRequestAcceptedOfferCount :exec
UPDATE buy_requests SET accepted_offer_count = accepted_offer_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementBuyRequestAcceptedOfferCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementBuyRequestAcceptedOfferCount, id)
	return err
}

const incrementBuyRequestOfferCount = `-- name: IncrementBuyRequestOfferCount :exec
UPDATE buy_requests SET offer_count = offer_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementBuyRequestOfferCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementBuyRequestOfferCount, id)
	return err
}

const listActiveBuyRequests = `-- name: ListActiveBuyRequests :many
SELECT br.id, br.public_id, br.owner_id, br.region_id, br.interest_id, br.title, br.description, br.image_url, br.unit, br.quantity, br.buy_all_from_one, br.offer_count, br.accepted_offer_count, br.fulfilled_quantity, br.end_time, br.status, br.created_at, br.updated_at, br.owner_name, br.region_name, br.interest_name, br.notified_at, br.last_motivation_sent_at FROM buy_requests br
WHERE br.status = 'active' AND br.end_time > NOW()
  AND ($3::int IS NULL OR br.owner_id != $3::int)
  AND ($4::int[] IS NULL OR br.id NOT IN (
    SELECT so.buy_request_id FROM supply_offers so WHERE so.supplier_id = $5::int
  ))
ORDER BY
  CASE WHEN br.interest_id = ANY($6::integer[]) THEN 0 ELSE 1 END,
  br.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveBuyRequestsParams struct {
	Limit                  int32   `json:"limit"`
	Offset                 int32   `json:"offset"`
	ExcludeOwnerID         int32   `json:"exclude_owner_id"`
	ExcludeOfferedRequests []int32 `json:"exclude_offered_requests"`
	UserID                 int32   `json:"user_id"`
	UserInterestIds        []int32 `json:"user_interest_ids"`
}

func (q *Queries) ListActiveBuyRequests(ctx context.Context, arg ListActiveBuyRequestsParams) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, listActiveBuyRequests,
		arg.Limit,
		arg.Offset,
		arg.ExcludeOwnerID,
		arg.ExcludeOfferedRequests,
		arg.UserID,
		arg.UserInterestIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuyRequestsByOwner = `-- name: ListBuyRequestsByOwner :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, buy_all_from_one, offer_count, accepted_offer_count, fulfilled_quantity, end_time, status, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at FROM buy_requests WHERE owner_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBuyRequestsByOwnerParams struct {
	OwnerID int32 `json:"owner_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListBuyRequestsByOwner(ctx context.Context, arg ListBuyRequestsByOwnerParams) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, listBuyRequestsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBuyRequestMotivated = `-- name: MarkBuyRequestMotivated :exec
UPDATE buy_requests SET last_motivation_sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkBuyRequestMotivated(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markBuyRequestMotivated, id)
	return err
}

const markBuyRequestNotified = `-- name: MarkBuyRequestNotified :exec
UPDATE buy_requests SET notified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkBuyRequestNotified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markBuyRequestNotified, id)
	return err
}

const revertBuyRequestToPendingSelection = `-- name: RevertBuyRequestToPendingSelection :exec
UPDATE buy_requests 
SET status = 'pending_selection', accepted_offer_count = 0, fulfilled_quantity = 0, updated_at = NOW()
WHERE id = $1 AND status IN ('fulfilled', 'partially_fulfilled')
`

func (q *Queries) RevertBuyRequestToPendingSelection(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revertBuyRequestToPendingSelection, id)
	return err
}

const searchBuyRequests = `-- name: SearchBuyRequests :many
SELECT br.id, br.public_id, br.owner_id, br.region_id, br.interest_id, br.title, br.description, br.image_url, br.unit, br.quantity, br.buy_all_from_one, br.offer_count, br.accepted_offer_count, br.fulfilled_quantity, br.end_time, br.status, br.created_at, br.updated_at, br.owner_name, br.region_name, br.interest_name, br.notified_at, br.last_motivation_sent_at FROM buy_requests br
WHERE br.status = 'active' AND br.end_time > NOW()
  AND br.title ILIKE '%' || $3::text || '%'
  AND ($4::int IS NULL OR br.owner_id != $4::int)
  AND ($5::int[] IS NULL OR br.id NOT IN (
    SELECT so.buy_request_id FROM supply_offers so WHERE so.supplier_id = $6::int
  ))
ORDER BY
  CASE WHEN br.interest_id = ANY($7::integer[]) THEN 0 ELSE 1 END,
  br.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchBuyRequestsParams struct {
	Limit                  int32   `json:"limit"`
	Offset                 int32   `json:"offset"`
	SearchTerm             string  `json:"search_term"`
	ExcludeOwnerID         int32   `json:"exclude_owner_id"`
	ExcludeOfferedRequests []int32 `json:"exclude_offered_requests"`
	UserID                 int32   `json:"user_id"`
	UserInterestIds        []int32 `json:"user_interest_ids"`
}

func (q *Queries) SearchBuyRequests(ctx context.Context, arg SearchBuyRequestsParams) ([]BuyRequest, error) {
	rows, err := q.db.Query(ctx, searchBuyRequests,
		arg.Limit,
		arg.Offset,
		arg.SearchTerm,
		arg.ExcludeOwnerID,
		arg.ExcludeOfferedRequests,
		arg.UserID,
		arg.UserInterestIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuyRequest
	for rows.Next() {
		var i BuyRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.BuyAllFromOne,
			&i.OfferCount,
			&i.AcceptedOfferCount,
			&i.FulfilledQuantity,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuyRequestFulfilledQuantity = `-- name: UpdateBuyRequestFulfilledQuantity :exec
UPDATE buy_requests SET fulfilled_quantity = $2, updated_at = NOW() WHERE id = $1
`

type UpdateBuyRequestFulfilledQuantityParams struct {
	ID                int32          `json:"id"`
	FulfilledQuantity pgtype.Numeric `json:"fulfilled_quantity"`
}

func (q *Queries) UpdateBuyRequestFulfilledQuantity(ctx context.Context, arg UpdateBuyRequestFulfilledQuantityParams) error {
	_, err := q.db.Exec(ctx, updateBuyRequestFulfilledQuantity, arg.ID, arg.FulfilledQuantity)
	return err
}

const updateBuyRequestStatus = `-- name: UpdateBuyRequestStatus :exec
UPDATE buy_requests SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateBuyRequestStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateBuyRequestStatus(ctx context.Context, arg UpdateBuyRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateBuyRequestStatus, arg.ID, arg.Status)
	return err
}
