// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carriers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCarrierRegion = `-- name: AddCarrierRegion :exec
INSERT INTO carrier_regions (user_id, region_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCarrierRegionParams struct {
	UserID   int32 `json:"user_id"`
	RegionID int32 `json:"region_id"`
}

func (q *Queries) AddCarrierRegion(ctx context.Context, arg AddCarrierRegionParams) error {
	_, err := q.db.Exec(ctx, addCarrierRegion, arg.UserID, arg.RegionID)
	return err
}

const countCarrierRegions = `-- name: CountCarrierRegions :one
SELECT COUNT(*) FROM carrier_regions WHERE user_id = $1
`

func (q *Queries) CountCarrierRegions(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countCarrierRegions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCarrierProfile = `-- name: GetCarrierProfile :one
SELECT user_id, logo_url, notes, created_at, updated_at FROM carrier_profiles WHERE user_id = $1
`

func (q *Queries) GetCarrierProfile(ctx context.Context, userID int32) (CarrierProfile, error) {
	row := q.db.QueryRow(ctx, getCarrierProfile, userID)
	var i CarrierProfile
	err := row.Scan(
		&i.UserID,
		&i.LogoUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCarrierRegionIDs = `-- name: ListCarrierRegionIDs :many
SELECT region_id FROM carrier_regions WHERE user_id = $1
`

func (q *Queries) ListCarrierRegionIDs(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listCarrierRegionIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var region_id int32
		if err := rows.Scan(&region_id); err != nil {
			return nil, err
		}
		items = append(items, region_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarrierRegions = `-- name: ListCarrierRegions :many
SELECT cr.region_id, r.name_ar, r.name_en
FROM carrier_regions cr
JOIN regions r ON r.id = cr.region_id
WHERE cr.user_id = $1
ORDER BY r.name_ar
`

type ListCarrierRegionsRow struct {
	RegionID int32       `json:"region_id"`
	NameAr   string      `json:"name_ar"`
	NameEn   pgtype.Text `json:"name_en"`
}

func (q *Queries) ListCarrierRegions(ctx context.Context, userID int32) ([]ListCarrierRegionsRow, error) {
	rows, err := q.db.Query(ctx, listCarrierRegions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCarrierRegionsRow
	for rows.Next() {
		var i ListCarrierRegionsRow
		if err := rows.Scan(&i.RegionID, &i.NameAr, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCarrierRegions = `-- name: ReplaceCarrierRegions :exec
DELETE FROM carrier_regions WHERE user_id = $1
`

// Coverage is replaced wholesale rather than diffed: the edit form always sends
// the complete set, and a partial update would leave stale governorates behind.
func (q *Queries) ReplaceCarrierRegions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, replaceCarrierRegions, userID)
	return err
}

const upsertCarrierProfile = `-- name: UpsertCarrierProfile :one
INSERT INTO carrier_profiles (user_id, logo_url, notes)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET logo_url = EXCLUDED.logo_url,
    notes = EXCLUDED.notes,
    updated_at = NOW()
RETURNING user_id, logo_url, notes, created_at, updated_at
`

type UpsertCarrierProfileParams struct {
	UserID  int32       `json:"user_id"`
	LogoUrl pgtype.Text `json:"logo_url"`
	Notes   pgtype.Text `json:"notes"`
}

// Registration and profile edits share one path: a carrier always has exactly
// one profile row, so there is nothing to distinguish create from update.
func (q *Queries) UpsertCarrierProfile(ctx context.Context, arg UpsertCarrierProfileParams) (CarrierProfile, error) {
	row := q.db.QueryRow(ctx, upsertCarrierProfile, arg.UserID, arg.LogoUrl, arg.Notes)
	var i CarrierProfile
	err := row.Scan(
		&i.UserID,
		&i.LogoUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
