// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachChargesToInvoice = `-- name: AttachChargesToInvoice :execrows
UPDATE commission_charges
SET invoice_id = $1::int
WHERE invoice_id IS NULL
  AND seller_id = $2::int
  AND order_completed_at >= $3::timestamptz
  AND order_completed_at <  $4::timestamptz
`

type AttachChargesToInvoiceParams struct {
	InvoiceID   int32              `json:"invoice_id"`
	SellerID    int32              `json:"seller_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

func (q *Queries) AttachChargesToInvoice(ctx context.Context, arg AttachChargesToInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachChargesToInvoice,
		arg.InvoiceID,
		arg.SellerID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSellerBalances = `-- name: CountSellerBalances :one
SELECT COUNT(DISTINCT seller_id) FROM commission_invoices
WHERE status = 'unpaid'
  AND ($1::bool = false OR due_at < NOW())
`

func (q *Queries) CountSellerBalances(ctx context.Context, overdueOnly bool) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerBalances, overdueOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommissionCharge = `-- name: CreateCommissionCharge :one
INSERT INTO commission_charges (
    order_id, seller_id, deal_value, rate_percent, amount, order_completed_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, public_id, order_id, seller_id, deal_value, rate_percent, amount, order_completed_at, invoice_id, created_at
`

type CreateCommissionChargeParams struct {
	OrderID          int32              `json:"order_id"`
	SellerID         int32              `json:"seller_id"`
	DealValue        pgtype.Numeric     `json:"deal_value"`
	RatePercent      pgtype.Numeric     `json:"rate_percent"`
	Amount           pgtype.Numeric     `json:"amount"`
	OrderCompletedAt pgtype.Timestamptz `json:"order_completed_at"`
}

func (q *Queries) CreateCommissionCharge(ctx context.Context, arg CreateCommissionChargeParams) (CommissionCharge, error) {
	row := q.db.QueryRow(ctx, createCommissionCharge,
		arg.OrderID,
		arg.SellerID,
		arg.DealValue,
		arg.RatePercent,
		arg.Amount,
		arg.OrderCompletedAt,
	)
	var i CommissionCharge
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrderID,
		&i.SellerID,
		&i.DealValue,
		&i.RatePercent,
		&i.Amount,
		&i.OrderCompletedAt,
		&i.InvoiceID,
		&i.CreatedAt,
	)
	return i, err
}

const createCommissionInvoice = `-- name: CreateCommissionInvoice :one
INSERT INTO commission_invoices (
    seller_id, period_start, period_end, total_amount, due_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (seller_id, period_start) DO NOTHING
RETURNING id, public_id, seller_id, period_start, period_end, total_amount, status, issued_at, due_at, paid_at, payment_method, payment_reference, payment_note, waived_reason, recorded_by_admin_id, created_at, updated_at, last_reminder_at, reminder_count
`

type CreateCommissionInvoiceParams struct {
	SellerID    int32              `json:"seller_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateCommissionInvoice(ctx context.Context, arg CreateCommissionInvoiceParams) (CommissionInvoice, error) {
	row := q.db.QueryRow(ctx, createCommissionInvoice,
		arg.SellerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalAmount,
		arg.DueAt,
	)
	var i CommissionInvoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalAmount,
		&i.Status,
		&i.IssuedAt,
		&i.DueAt,
		&i.PaidAt,
		&i.PaymentMethod,
		&i.PaymentReference,
		&i.PaymentNote,
		&i.WaivedReason,
		&i.RecordedByAdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastReminderAt,
		&i.ReminderCount,
	)
	return i, err
}

const getCommissionTotals = `-- name: GetCommissionTotals :one
SELECT
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'unpaid'), 0)::DECIMAL(14,2) AS total_outstanding,
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'unpaid' AND due_at < NOW()), 0)::DECIMAL(14,2) AS total_overdue,
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'paid'), 0)::DECIMAL(14,2) AS total_collected
FROM commission_invoices
`

type GetCommissionTotalsRow struct {
	TotalOutstanding pgtype.Numeric `json:"total_outstanding"`
	TotalOverdue     pgtype.Numeric `json:"total_overdue"`
	TotalCollected   pgtype.Numeric `json:"total_collected"`
}

func (q *Queries) GetCommissionTotals(ctx context.Context) (GetCommissionTotalsRow, error) {
	row := q.db.QueryRow(ctx, getCommissionTotals)
	var i GetCommissionTotalsRow
	err := row.Scan(&i.TotalOutstanding, &i.TotalOverdue, &i.TotalCollected)
	return i, err
}

const getInvoiceByPublicID = `-- name: GetInvoiceByPublicID :one
SELECT id, public_id, seller_id, period_start, period_end, total_amount, status, issued_at, due_at, paid_at, payment_method, payment_reference, payment_note, waived_reason, recorded_by_admin_id, created_at, updated_at, last_reminder_at, reminder_count FROM commission_invoices WHERE public_id = $1
`

func (q *Queries) GetInvoiceByPublicID(ctx context.Context, publicID pgtype.UUID) (CommissionInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByPublicID, publicID)
	var i CommissionInvoice
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalAmount,
		&i.Status,
		&i.IssuedAt,
		&i.DueAt,
		&i.PaidAt,
		&i.PaymentMethod,
		&i.PaymentReference,
		&i.PaymentNote,
		&i.WaivedReason,
		&i.RecordedByAdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastReminderAt,
		&i.ReminderCount,
	)
	return i, err
}

const getSellerCommissionSummary = `-- name: GetSellerCommissionSummary :one
SELECT
    COALESCE((SELECT SUM(total_amount) FROM commission_invoices
              WHERE seller_id = $1::int AND status = 'unpaid'), 0)::DECIMAL(14,2) AS outstanding,
    COALESCE((SELECT SUM(amount) FROM commission_charges
              WHERE seller_id = $1::int AND invoice_id IS NULL), 0)::DECIMAL(14,2) AS accruing,
    (SELECT COUNT(*) FROM commission_invoices
     WHERE seller_id = $1::int AND status = 'unpaid' AND due_at < NOW()) AS overdue_count
`

type GetSellerCommissionSummaryRow struct {
	Outstanding  pgtype.Numeric `json:"outstanding"`
	Accruing     pgtype.Numeric `json:"accruing"`
	OverdueCount int64          `json:"overdue_count"`
}

// Seller-facing.
func (q *Queries) GetSellerCommissionSummary(ctx context.Context, sellerID int32) (GetSellerCommissionSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSellerCommissionSummary, sellerID)
	var i GetSellerCommissionSummaryRow
	err := row.Scan(&i.Outstanding, &i.Accruing, &i.OverdueCount)
	return i, err
}

const listChargesByInvoice = `-- name: ListChargesByInvoice :many
SELECT id, public_id, order_id, seller_id, deal_value, rate_percent, amount, order_completed_at, invoice_id, created_at FROM commission_charges
WHERE invoice_id = $1
ORDER BY order_completed_at
`

func (q *Queries) ListChargesByInvoice(ctx context.Context, invoiceID pgtype.Int4) ([]CommissionCharge, error) {
	rows, err := q.db.Query(ctx, listChargesByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommissionCharge
	for rows.Next() {
		var i CommissionCharge
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrderID,
			&i.SellerID,
			&i.DealValue,
			&i.RatePercent,
			&i.Amount,
			&i.OrderCompletedAt,
			&i.InvoiceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargesBySeller = `-- name: ListChargesBySeller :many
SELECT id, public_id, order_id, seller_id, deal_value, rate_percent, amount, order_completed_at, invoice_id, created_at FROM commission_charges
WHERE seller_id = $1
ORDER BY order_completed_at DESC
LIMIT $2 OFFSET $3
`

type ListChargesBySellerParams struct {
	SellerID int32 `json:"seller_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListChargesBySeller(ctx context.Context, arg ListChargesBySellerParams) ([]CommissionCharge, error) {
	rows, err := q.db.Query(ctx, listChargesBySeller, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommissionCharge
	for rows.Next() {
		var i CommissionCharge
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrderID,
			&i.SellerID,
			&i.DealValue,
			&i.RatePercent,
			&i.Amount,
			&i.OrderCompletedAt,
			&i.InvoiceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedOrdersWithoutCharge = `-- name: ListCompletedOrdersWithoutCharge :many

SELECT o.id, o.seller_id, o.final_price, o.quantity, o.completed_at
FROM orders o
JOIN users s ON s.id = o.seller_id
LEFT JOIN commission_charges c ON c.order_id = o.id
WHERE o.status = 'completed'
  AND o.completed_at IS NOT NULL
  AND c.id IS NULL
  -- Production is almost entirely seeded; billing the seeder would bury every
  -- real debt under fiction.
  AND s.email <> $2::text
ORDER BY o.completed_at
LIMIT $1
`

type ListCompletedOrdersWithoutChargeParams struct {
	Limit     int32  `json:"limit"`
	SeedEmail string `json:"seed_email"`
}

type ListCompletedOrdersWithoutChargeRow struct {
	ID          int32              `json:"id"`
	SellerID    int32              `json:"seller_id"`
	FinalPrice  pgtype.Numeric     `json:"final_price"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// Platform commission (#13). See migration 045 for the shape and the reasoning.
// Accrual. Charges are derived from orders rather than written by the
// confirmation handler: ConfirmOrderAsSeller/AsBuyer are conditional updates
// declared :exec, so the service cannot tell whether the transition actually
// applied, and accruing there would bill orders that never completed. Running
// this every minute is idempotent because commission_charges.order_id is UNIQUE.
func (q *Queries) ListCompletedOrdersWithoutCharge(ctx context.Context, arg ListCompletedOrdersWithoutChargeParams) ([]ListCompletedOrdersWithoutChargeRow, error) {
	rows, err := q.db.Query(ctx, listCompletedOrdersWithoutCharge, arg.Limit, arg.SeedEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedOrdersWithoutChargeRow
	for rows.Next() {
		var i ListCompletedOrdersWithoutChargeRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.FinalPrice,
			&i.Quantity,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesBySeller = `-- name: ListInvoicesBySeller :many
SELECT id, public_id, seller_id, period_start, period_end, total_amount, status, issued_at, due_at, paid_at, payment_method, payment_reference, payment_note, waived_reason, recorded_by_admin_id, created_at, updated_at, last_reminder_at, reminder_count FROM commission_invoices
WHERE seller_id = $1
ORDER BY period_start DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesBySellerParams struct {
	SellerID int32 `json:"seller_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListInvoicesBySeller(ctx context.Context, arg ListInvoicesBySellerParams) ([]CommissionInvoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesBySeller, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommissionInvoice
	for rows.Next() {
		var i CommissionInvoice
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalAmount,
			&i.Status,
			&i.IssuedAt,
			&i.DueAt,
			&i.PaidAt,
			&i.PaymentMethod,
			&i.PaymentReference,
			&i.PaymentNote,
			&i.WaivedReason,
			&i.RecordedByAdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReminderAt,
			&i.ReminderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesForAdmin = `-- name: ListInvoicesForAdmin :many
SELECT i.id, i.public_id, i.seller_id, i.period_start, i.period_end, i.total_amount, i.status, i.issued_at, i.due_at, i.paid_at, i.payment_method, i.payment_reference, i.payment_note, i.waived_reason, i.recorded_by_admin_id, i.created_at, i.updated_at, i.last_reminder_at, i.reminder_count, u.name AS seller_name, u.phone AS seller_phone, u.public_id AS seller_public_id
FROM commission_invoices i
JOIN users u ON u.id = i.seller_id
WHERE ($3::text = '' OR i.status = $3::text)
ORDER BY i.issued_at DESC
LIMIT $1 OFFSET $2
`

type ListInvoicesForAdminParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	StatusFilter string `json:"status_filter"`
}

type ListInvoicesForAdminRow struct {
	ID                int32              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	SellerID          int32              `json:"seller_id"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	Status            string             `json:"status"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	PaymentMethod     pgtype.Text        `json:"payment_method"`
	PaymentReference  pgtype.Text        `json:"payment_reference"`
	PaymentNote       pgtype.Text        `json:"payment_note"`
	WaivedReason      pgtype.Text        `json:"waived_reason"`
	RecordedByAdminID pgtype.Int4        `json:"recorded_by_admin_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	LastReminderAt    pgtype.Timestamptz `json:"last_reminder_at"`
	ReminderCount     int32              `json:"reminder_count"`
	SellerName        string             `json:"seller_name"`
	SellerPhone       pgtype.Text        `json:"seller_phone"`
	SellerPublicID    pgtype.UUID        `json:"seller_public_id"`
}

func (q *Queries) ListInvoicesForAdmin(ctx context.Context, arg ListInvoicesForAdminParams) ([]ListInvoicesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesForAdmin, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesForAdminRow
	for rows.Next() {
		var i ListInvoicesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalAmount,
			&i.Status,
			&i.IssuedAt,
			&i.DueAt,
			&i.PaidAt,
			&i.PaymentMethod,
			&i.PaymentReference,
			&i.PaymentNote,
			&i.WaivedReason,
			&i.RecordedByAdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReminderAt,
			&i.ReminderCount,
			&i.SellerName,
			&i.SellerPhone,
			&i.SellerPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesNeedingReminder = `-- name: ListInvoicesNeedingReminder :many
SELECT i.id, i.public_id, i.seller_id, i.period_start, i.period_end, i.total_amount, i.status, i.issued_at, i.due_at, i.paid_at, i.payment_method, i.payment_reference, i.payment_note, i.waived_reason, i.recorded_by_admin_id, i.created_at, i.updated_at, i.last_reminder_at, i.reminder_count, u.name AS seller_name
FROM commission_invoices i
JOIN users u ON u.id = i.seller_id
WHERE i.status = 'unpaid'
  AND i.due_at <= NOW()
  -- The cutoff is computed by the caller from the configured cadence: doing the
  -- interval arithmetic here would put the same rule in two places.
  AND (i.last_reminder_at IS NULL OR i.last_reminder_at < $2::timestamptz)
ORDER BY i.due_at
LIMIT $1
`

type ListInvoicesNeedingReminderParams struct {
	Limit        int32              `json:"limit"`
	RemindBefore pgtype.Timestamptz `json:"remind_before"`
}

type ListInvoicesNeedingReminderRow struct {
	ID                int32              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	SellerID          int32              `json:"seller_id"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	Status            string             `json:"status"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	PaymentMethod     pgtype.Text        `json:"payment_method"`
	PaymentReference  pgtype.Text        `json:"payment_reference"`
	PaymentNote       pgtype.Text        `json:"payment_note"`
	WaivedReason      pgtype.Text        `json:"waived_reason"`
	RecordedByAdminID pgtype.Int4        `json:"recorded_by_admin_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	LastReminderAt    pgtype.Timestamptz `json:"last_reminder_at"`
	ReminderCount     int32              `json:"reminder_count"`
	SellerName        string             `json:"seller_name"`
}

// Payment reminders. Candidates are unpaid invoices that are due and either
// never reminded or last reminded longer ago than the configured interval. The
// interval is a parameter rather than a literal so the admin setting is the only
// place the cadence is defined.
func (q *Queries) ListInvoicesNeedingReminder(ctx context.Context, arg ListInvoicesNeedingReminderParams) ([]ListInvoicesNeedingReminderRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesNeedingReminder, arg.Limit, arg.RemindBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesNeedingReminderRow
	for rows.Next() {
		var i ListInvoicesNeedingReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalAmount,
			&i.Status,
			&i.IssuedAt,
			&i.DueAt,
			&i.PaidAt,
			&i.PaymentMethod,
			&i.PaymentReference,
			&i.PaymentNote,
			&i.WaivedReason,
			&i.RecordedByAdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReminderAt,
			&i.ReminderCount,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerBalances = `-- name: ListSellerBalances :many
SELECT
    u.id AS seller_id, u.public_id, u.name, u.phone, u.email, u.status,
    SUM(i.total_amount)::DECIMAL(14,2) AS outstanding,
    COUNT(*) AS unpaid_invoices,
    MIN(i.due_at)::timestamptz AS earliest_due_at,
    BOOL_OR(i.due_at < NOW()) AS is_overdue
FROM commission_invoices i
JOIN users u ON u.id = i.seller_id
WHERE i.status = 'unpaid'
  AND ($3::bool = false OR i.due_at < NOW())
GROUP BY u.id, u.public_id, u.name, u.phone, u.email, u.status
ORDER BY BOOL_OR(i.due_at < NOW()) DESC, MIN(i.due_at)
LIMIT $1 OFFSET $2
`

type ListSellerBalancesParams struct {
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
	OverdueOnly bool  `json:"overdue_only"`
}

type ListSellerBalancesRow struct {
	SellerID       int32              `json:"seller_id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	Name           string             `json:"name"`
	Phone          pgtype.Text        `json:"phone"`
	Email          string             `json:"email"`
	Status         string             `json:"status"`
	Outstanding    pgtype.Numeric     `json:"outstanding"`
	UnpaidInvoices int64              `json:"unpaid_invoices"`
	EarliestDueAt  pgtype.Timestamptz `json:"earliest_due_at"`
	IsOverdue      bool               `json:"is_overdue"`
}

// Admin. The worklist is one row per seller who owes something, overdue first.
func (q *Queries) ListSellerBalances(ctx context.Context, arg ListSellerBalancesParams) ([]ListSellerBalancesRow, error) {
	rows, err := q.db.Query(ctx, listSellerBalances, arg.Limit, arg.Offset, arg.OverdueOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellerBalancesRow
	for rows.Next() {
		var i ListSellerBalancesRow
		if err := rows.Scan(
			&i.SellerID,
			&i.PublicID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Status,
			&i.Outstanding,
			&i.UnpaidInvoices,
			&i.EarliestDueAt,
			&i.IsOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellersWithUninvoicedCharges = `-- name: ListSellersWithUninvoicedCharges :many
SELECT seller_id, SUM(amount)::DECIMAL(14,2) AS total, COUNT(*) AS charge_count
FROM commission_charges
WHERE invoice_id IS NULL
  AND order_completed_at >= $1::timestamptz
  AND order_completed_at <  $2::timestamptz
GROUP BY seller_id
ORDER BY seller_id
`

type ListSellersWithUninvoicedChargesParams struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type ListSellersWithUninvoicedChargesRow struct {
	SellerID    int32          `json:"seller_id"`
	Total       pgtype.Numeric `json:"total"`
	ChargeCount int64          `json:"charge_count"`
}

// Invoicing.
func (q *Queries) ListSellersWithUninvoicedCharges(ctx context.Context, arg ListSellersWithUninvoicedChargesParams) ([]ListSellersWithUninvoicedChargesRow, error) {
	rows, err := q.db.Query(ctx, listSellersWithUninvoicedCharges, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellersWithUninvoicedChargesRow
	for rows.Next() {
		var i ListSellersWithUninvoicedChargesRow
		if err := rows.Scan(&i.SellerID, &i.Total, &i.ChargeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :execrows
UPDATE commission_invoices
SET status = 'paid', paid_at = NOW(), payment_method = $2, payment_reference = $3,
    payment_note = $4, recorded_by_admin_id = $5, updated_at = NOW()
WHERE id = $1 AND status = 'unpaid'
`

type MarkInvoicePaidParams struct {
	ID                int32       `json:"id"`
	PaymentMethod     pgtype.Text `json:"payment_method"`
	PaymentReference  pgtype.Text `json:"payment_reference"`
	PaymentNote       pgtype.Text `json:"payment_note"`
	RecordedByAdminID pgtype.Int4 `json:"recorded_by_admin_id"`
}

// Recording a payment is admin-only and one-way: an invoice is unpaid, paid or
// waived. The status guard makes a double-submit a no-op rather than a second
// payment record.
func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicePaid,
		arg.ID,
		arg.PaymentMethod,
		arg.PaymentReference,
		arg.PaymentNote,
		arg.RecordedByAdminID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInvoiceReminded = `-- name: MarkInvoiceReminded :exec
UPDATE commission_invoices
SET last_reminder_at = NOW(),
    reminder_count   = reminder_count + 1,
    updated_at       = NOW()
WHERE id = $1
`

func (q *Queries) MarkInvoiceReminded(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markInvoiceReminded, id)
	return err
}

const waiveInvoice = `-- name: WaiveInvoice :execrows
UPDATE commission_invoices
SET status = 'waived', waived_reason = $2, recorded_by_admin_id = $3, updated_at = NOW()
WHERE id = $1 AND status = 'unpaid'
`

type WaiveInvoiceParams struct {
	ID                int32       `json:"id"`
	WaivedReason      pgtype.Text `json:"waived_reason"`
	RecordedByAdminID pgtype.Int4 `json:"recorded_by_admin_id"`
}

func (q *Queries) WaiveInvoice(ctx context.Context, arg WaiveInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, waiveInvoice, arg.ID, arg.WaivedReason, arg.RecordedByAdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
