// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package sqlc

import (
	"context"
)

const deactivateDeviceToken = `-- name: DeactivateDeviceToken :exec
UPDATE device_tokens SET is_active = FALSE, updated_at = NOW() WHERE token = $1
`

func (q *Queries) DeactivateDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deactivateDeviceToken, token)
	return err
}

const getActiveDeviceTokensByUser = `-- name: GetActiveDeviceTokensByUser :many
SELECT id, user_id, token, platform, is_active, created_at, updated_at FROM device_tokens WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) GetActiveDeviceTokensByUser(ctx context.Context, userID int32) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getActiveDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, token) DO UPDATE SET is_active = TRUE, updated_at = NOW()
`

type UpsertDeviceTokenParams struct {
	UserID   int32  `json:"user_id"`
	Token    string `json:"token"`
	Platform string `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	return err
}
