// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeIssueIfOpen = `-- name: CloseIssueIfOpen :one
UPDATE issues SET status = 'closed', updated_at = NOW() WHERE public_id = $1 AND status <> 'closed' RETURNING id
`

func (q *Queries) CloseIssueIfOpen(ctx context.Context, publicID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, closeIssueIfOpen, publicID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const countOpenIssuesByUser = `-- name: CountOpenIssuesByUser :one
SELECT COUNT(*) FROM issues WHERE user_id = $1 AND status = 'open'
`

func (q *Queries) CountOpenIssuesByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIssuesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (user_id, title, description, category, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, user_id, title, description, status, created_at, updated_at, category, priority
`

type CreateIssueParams struct {
	UserID      int32  `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Category    string `json:"category"`
	Priority    string `json:"priority"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Priority,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Priority,
	)
	return i, err
}

const createIssueReply = `-- name: CreateIssueReply :one
INSERT INTO issue_replies (issue_id, admin_id, message) VALUES ($1, $2, $3) RETURNING id, issue_id, admin_id, message, created_at
`

type CreateIssueReplyParams struct {
	IssueID int32  `json:"issue_id"`
	AdminID int32  `json:"admin_id"`
	Message string `json:"message"`
}

func (q *Queries) CreateIssueReply(ctx context.Context, arg CreateIssueReplyParams) (IssueReply, error) {
	row := q.db.QueryRow(ctx, createIssueReply, arg.IssueID, arg.AdminID, arg.Message)
	var i IssueReply
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AdminID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getIssueAdminDetail = `-- name: GetIssueAdminDetail :one
SELECT
    i.id, i.public_id, i.title, i.description, i.status, i.category, i.priority, i.created_at, i.updated_at,
    u.name AS user_name,
    u.email AS user_email,
    u.phone AS user_phone,
    u.region_name AS user_region
FROM issues i
JOIN users u ON u.id = i.user_id
WHERE i.public_id = $1
`

type GetIssueAdminDetailRow struct {
	ID          int32              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Category    string             `json:"category"`
	Priority    string             `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
	UserPhone   pgtype.Text        `json:"user_phone"`
	UserRegion  string             `json:"user_region"`
}

func (q *Queries) GetIssueAdminDetail(ctx context.Context, publicID pgtype.UUID) (GetIssueAdminDetailRow, error) {
	row := q.db.QueryRow(ctx, getIssueAdminDetail, publicID)
	var i GetIssueAdminDetailRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Category,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserRegion,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, public_id, user_id, title, description, status, created_at, updated_at, category, priority FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int32) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Priority,
	)
	return i, err
}

const getIssueByPublicID = `-- name: GetIssueByPublicID :one
SELECT id, public_id, user_id, title, description, status, created_at, updated_at, category, priority FROM issues WHERE public_id = $1
`

func (q *Queries) GetIssueByPublicID(ctx context.Context, publicID pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByPublicID, publicID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Priority,
	)
	return i, err
}

const listAllIssues = `-- name: ListAllIssues :many
SELECT id, public_id, user_id, title, description, status, created_at, updated_at, category, priority FROM issues ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllIssuesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllIssues(ctx context.Context, arg ListAllIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listAllIssues, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueReplies = `-- name: ListIssueReplies :many
SELECT id, issue_id, admin_id, message, created_at FROM issue_replies WHERE issue_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListIssueReplies(ctx context.Context, issueID int32) ([]IssueReply, error) {
	rows, err := q.db.Query(ctx, listIssueReplies, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueReply
	for rows.Next() {
		var i IssueReply
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AdminID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByUser = `-- name: ListIssuesByUser :many
SELECT id, public_id, user_id, title, description, status, created_at, updated_at, category, priority FROM issues WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListIssuesByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIssuesByUser(ctx context.Context, arg ListIssuesByUserParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateIssueStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.Exec(ctx, updateIssueStatus, arg.ID, arg.Status)
	return err
}
