// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: jobs.sql

package sqlc

import (
	"context"
)

const getJobByID = `-- name: GetJobByID :one
SELECT id, key, name_ar, name_en, is_active, created_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameAr,
		&i.NameEn,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getJobByKey = `-- name: GetJobByKey :one
SELECT id, key, name_ar, name_en, is_active, created_at FROM jobs WHERE key = $1
`

func (q *Queries) GetJobByKey(ctx context.Context, key string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByKey, key)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameAr,
		&i.NameEn,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, key, name_ar, name_en, is_active, created_at FROM jobs WHERE is_active = TRUE ORDER BY name_ar
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.NameAr,
			&i.NameEn,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
