// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginHistory = `-- name: CreateLoginHistory :exec
INSERT INTO login_history (user_id, device_info, ip_address, success)
VALUES ($1, $2, $3, $4)
`

type CreateLoginHistoryParams struct {
	UserID     int32       `json:"user_id"`
	DeviceInfo pgtype.Text `json:"device_info"`
	IpAddress  pgtype.Text `json:"ip_address"`
	Success    bool        `json:"success"`
}

func (q *Queries) CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) error {
	_, err := q.db.Exec(ctx, createLoginHistory,
		arg.UserID,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.Success,
	)
	return err
}

const listLoginHistoryByUser = `-- name: ListLoginHistoryByUser :many
SELECT id, user_id, device_info, ip_address, login_at, success FROM login_history WHERE user_id = $1
ORDER BY login_at DESC LIMIT $2 OFFSET $3
`

type ListLoginHistoryByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLoginHistoryByUser(ctx context.Context, arg ListLoginHistoryByUserParams) ([]LoginHistory, error) {
	rows, err := q.db.Query(ctx, listLoginHistoryByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginHistory
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.LoginAt,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
