// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BuyRequest struct {
	ID                     int32              `json:"id"`
	PublicID               pgtype.UUID        `json:"public_id"`
	OwnerID                int32              `json:"owner_id"`
	RegionID               int32              `json:"region_id"`
	InterestID             int32              `json:"interest_id"`
	Title                  string             `json:"title"`
	Description            pgtype.Text        `json:"description"`
	ImageUrl               string             `json:"image_url"`
	Unit                   string             `json:"unit"`
	Quantity               pgtype.Numeric     `json:"quantity"`
	BuyAllFromOne          bool               `json:"buy_all_from_one"`
	OfferCount             int32              `json:"offer_count"`
	AcceptedOfferCount     int32              `json:"accepted_offer_count"`
	FulfilledQuantity      pgtype.Numeric     `json:"fulfilled_quantity"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerName              string             `json:"owner_name"`
	RegionName             string             `json:"region_name"`
	InterestName           string             `json:"interest_name"`
	NotifiedAt             pgtype.Timestamptz `json:"notified_at"`
	LastMotivationSentAt   pgtype.Timestamptz `json:"last_motivation_sent_at"`
	SelectionWarningSentAt pgtype.Timestamptz `json:"selection_warning_sent_at"`
}

type DeviceToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	Platform  string             `json:"platform"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ErrorLog struct {
	ID         int32              `json:"id"`
	UserID     pgtype.Int4        `json:"user_id"`
	ErrorType  pgtype.Text        `json:"error_type"`
	Message    pgtype.Text        `json:"message"`
	StackTrace pgtype.Text        `json:"stack_trace"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Interest struct {
	ID        int32              `json:"id"`
	NameAr    string             `json:"name_ar"`
	NameEn    pgtype.Text        `json:"name_en"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID          int32              `json:"id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	UserID      int32              `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Category    string             `json:"category"`
	Priority    string             `json:"priority"`
}

type IssueReply struct {
	ID        int32              `json:"id"`
	IssueID   int32              `json:"issue_id"`
	AdminID   int32              `json:"admin_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID        int32              `json:"id"`
	Key       string             `json:"key"`
	NameAr    string             `json:"name_ar"`
	NameEn    pgtype.Text        `json:"name_en"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LoginHistory struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	LoginAt    pgtype.Timestamptz `json:"login_at"`
	Success    bool               `json:"success"`
}

type Notification struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	EventType string             `json:"event_type"`
	Data      []byte             `json:"data"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	PushEnabled bool               `json:"push_enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID                   int32              `json:"id"`
	PublicID             pgtype.UUID        `json:"public_id"`
	SellAuctionID        pgtype.Int4        `json:"sell_auction_id"`
	BuyRequestID         pgtype.Int4        `json:"buy_request_id"`
	SellerID             int32              `json:"seller_id"`
	BuyerID              int32              `json:"buyer_id"`
	FinalPrice           pgtype.Numeric     `json:"final_price"`
	Quantity             pgtype.Numeric     `json:"quantity"`
	Unit                 string             `json:"unit"`
	Status               string             `json:"status"`
	SellerConfirmedAt    pgtype.Timestamptz `json:"seller_confirmed_at"`
	BuyerConfirmedAt     pgtype.Timestamptz `json:"buyer_confirmed_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SellerName           string             `json:"seller_name"`
	SellerPhone          string             `json:"seller_phone"`
	SellerRegion         string             `json:"seller_region"`
	BuyerName            string             `json:"buyer_name"`
	BuyerPhone           string             `json:"buyer_phone"`
	BuyerRegion          string             `json:"buyer_region"`
	SourcePublicID       pgtype.UUID        `json:"source_public_id"`
	ConfirmationDeadline pgtype.Timestamptz `json:"confirmation_deadline"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
}

type ReferralCode struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Code            string             `json:"code"`
	DiscountPercent pgtype.Numeric     `json:"discount_percent"`
	UsageCount      int32              `json:"usage_count"`
	MaxUses         pgtype.Int4        `json:"max_uses"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ReferralUsage struct {
	ID              int32              `json:"id"`
	ReferralCodeID  int32              `json:"referral_code_id"`
	ReferredUserID  int32              `json:"referred_user_id"`
	DiscountApplied pgtype.Numeric     `json:"discount_applied"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Region struct {
	ID        int32              `json:"id"`
	NameAr    string             `json:"name_ar"`
	NameEn    pgtype.Text        `json:"name_en"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SellAuction struct {
	ID                     int32              `json:"id"`
	PublicID               pgtype.UUID        `json:"public_id"`
	OwnerID                int32              `json:"owner_id"`
	RegionID               int32              `json:"region_id"`
	InterestID             int32              `json:"interest_id"`
	Title                  string             `json:"title"`
	Description            pgtype.Text        `json:"description"`
	ImageUrl               string             `json:"image_url"`
	Unit                   string             `json:"unit"`
	Quantity               pgtype.Numeric     `json:"quantity"`
	UnitPrice              pgtype.Numeric     `json:"unit_price"`
	BuyAllFromOne          bool               `json:"buy_all_from_one"`
	BidCount               int32              `json:"bid_count"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	Status                 string             `json:"status"`
	SelectedBidID          pgtype.Int4        `json:"selected_bid_id"`
	WinnerID               pgtype.Int4        `json:"winner_id"`
	FinalPrice             pgtype.Numeric     `json:"final_price"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerName              string             `json:"owner_name"`
	RegionName             string             `json:"region_name"`
	InterestName           string             `json:"interest_name"`
	NotifiedAt             pgtype.Timestamptz `json:"notified_at"`
	LastMotivationSentAt   pgtype.Timestamptz `json:"last_motivation_sent_at"`
	SelectionWarningSentAt pgtype.Timestamptz `json:"selection_warning_sent_at"`
}

type SellBid struct {
	ID               int32              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	AuctionID        int32              `json:"auction_id"`
	BidderID         int32              `json:"bidder_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	IsSelected       bool               `json:"is_selected"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BidderRegionName string             `json:"bidder_region_name"`
	BidderFakeName   string             `json:"bidder_fake_name"`
	AuctionTitle     string             `json:"auction_title"`
	AuctionUnitPrice pgtype.Numeric     `json:"auction_unit_price"`
	AuctionQuantity  pgtype.Numeric     `json:"auction_quantity"`
	AuctionUnit      string             `json:"auction_unit"`
	IsNotChosen      bool               `json:"is_not_chosen"`
}

type Subscription struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Tier      string             `json:"tier"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionTier struct {
	TierName                string             `json:"tier_name"`
	PriceEgp                pgtype.Numeric     `json:"price_egp"`
	PriceUsd                pgtype.Numeric     `json:"price_usd"`
	MaxSellAuctionsPerMonth pgtype.Int4        `json:"max_sell_auctions_per_month"`
	MaxBuyRequestsPerMonth  pgtype.Int4        `json:"max_buy_requests_per_month"`
	MaxBidsPerMonth         pgtype.Int4        `json:"max_bids_per_month"`
	MaxOffersPerMonth       pgtype.Int4        `json:"max_offers_per_month"`
	CanCreateSellAuctions   bool               `json:"can_create_sell_auctions"`
	CanCreateBuyRequests    bool               `json:"can_create_buy_requests"`
	CanPlaceBids            bool               `json:"can_place_bids"`
	CanMakeOffers           bool               `json:"can_make_offers"`
	PrioritySupport         bool               `json:"priority_support"`
	DisplayNameAr           string             `json:"display_name_ar"`
	DisplayNameEn           string             `json:"display_name_en"`
	DescriptionAr           pgtype.Text        `json:"description_ar"`
	DescriptionEn           pgtype.Text        `json:"description_en"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SupplyOffer struct {
	ID                 int32              `json:"id"`
	PublicID           pgtype.UUID        `json:"public_id"`
	BuyRequestID       int32              `json:"buy_request_id"`
	SupplierID         int32              `json:"supplier_id"`
	PricePerUnit       pgtype.Numeric     `json:"price_per_unit"`
	OfferedQuantity    pgtype.Numeric     `json:"offered_quantity"`
	IsAccepted         bool               `json:"is_accepted"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SupplierRegionName string             `json:"supplier_region_name"`
	SupplierFakeName   string             `json:"supplier_fake_name"`
	RequestTitle       string             `json:"request_title"`
	RequestQuantity    pgtype.Numeric     `json:"request_quantity"`
	RequestUnit        string             `json:"request_unit"`
	IsNotChosen        bool               `json:"is_not_chosen"`
}

type User struct {
	ID                     int32              `json:"id"`
	PublicID               pgtype.UUID        `json:"public_id"`
	Email                  string             `json:"email"`
	Phone                  pgtype.Text        `json:"phone"`
	PhoneVerified          bool               `json:"phone_verified"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	EmailVerified          bool               `json:"email_verified"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	OtpHash                pgtype.Text        `json:"otp_hash"`
	OtpExpiresAt           pgtype.Timestamptz `json:"otp_expires_at"`
	Name                   string             `json:"name"`
	Role                   pgtype.Text        `json:"role"`
	JobID                  pgtype.Int4        `json:"job_id"`
	RegionID               pgtype.Int4        `json:"region_id"`
	Status                 string             `json:"status"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	Latitude               pgtype.Numeric     `json:"latitude"`
	Longitude              pgtype.Numeric     `json:"longitude"`
	FcmToken               pgtype.Text        `json:"fcm_token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	InterestsCount         int32              `json:"interests_count"`
	RegionName             string             `json:"region_name"`
	JobName                string             `json:"job_name"`
	SignupSource           string             `json:"signup_source"`
	SuspendedUntil         pgtype.Timestamptz `json:"suspended_until"`
	SuspensionReason       pgtype.Text        `json:"suspension_reason"`
	BannedAt               pgtype.Timestamptz `json:"banned_at"`
	BannedReason           pgtype.Text        `json:"banned_reason"`
	StatusChangedByAdminID pgtype.Int4        `json:"status_changed_by_admin_id"`
	StatusChangedAt        pgtype.Timestamptz `json:"status_changed_at"`
}

type UserDocument struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	DocumentType string             `json:"document_type"`
	FilePath     string             `json:"file_path"`
	UploadedAt   pgtype.Timestamptz `json:"uploaded_at"`
}

type UserInterest struct {
	UserID     int32 `json:"user_id"`
	InterestID int32 `json:"interest_id"`
}

type UserSession struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	IsCurrent  bool               `json:"is_current"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type UserSubscription struct {
	ID                       int32              `json:"id"`
	UserID                   int32              `json:"user_id"`
	TierName                 string             `json:"tier_name"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	AuctionsCreatedThisMonth int32              `json:"auctions_created_this_month"`
	RequestsCreatedThisMonth int32              `json:"requests_created_this_month"`
	BidsPlacedThisMonth      int32              `json:"bids_placed_this_month"`
	OffersMadeThisMonth      int32              `json:"offers_made_this_month"`
	MonthResetAt             pgtype.Timestamptz `json:"month_reset_at"`
	IsActive                 bool               `json:"is_active"`
	IsPrimary                bool               `json:"is_primary"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}
