// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNewsInterest = `-- name: AddNewsInterest :exec
INSERT INTO news_interests (news_id, interest_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddNewsInterestParams struct {
	NewsID     int32 `json:"news_id"`
	InterestID int32 `json:"interest_id"`
}

func (q *Queries) AddNewsInterest(ctx context.Context, arg AddNewsInterestParams) error {
	_, err := q.db.Exec(ctx, addNewsInterest, arg.NewsID, arg.InterestID)
	return err
}

const adminCountNews = `-- name: AdminCountNews :one
SELECT COUNT(*) FROM news
WHERE ($1::text = '' OR status = $1::text)
`

func (q *Queries) AdminCountNews(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountNews, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListNews = `-- name: AdminListNews :many
SELECT id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body FROM news
WHERE ($1::text = '' OR status = $1::text)
ORDER BY COALESCE(published_at, updated_at) DESC, id DESC
LIMIT $3 OFFSET $2
`

type AdminListNewsParams struct {
	Status string `json:"status"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

func (q *Queries) AdminListNews(ctx context.Context, arg AdminListNewsParams) ([]News, error) {
	rows, err := q.db.Query(ctx, adminListNews, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Summary,
			&i.BodyHtml,
			&i.CoverImageUrl,
			&i.SourceUrl,
			&i.SourceName,
			&i.SourceText,
			&i.Status,
			&i.AiProvider,
			&i.AiModel,
			&i.CreatedByAdminID,
			&i.PublishedAt,
			&i.NotifiedAt,
			&i.NotifiedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceImages,
			&i.NotificationTitle,
			&i.NotificationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNewsNotification = `-- name: ClaimNewsNotification :one
UPDATE news SET notified_at = NOW()
WHERE id = $1 AND notified_at IS NULL
RETURNING id
`

// Claims the notification for this story. Only one caller can win, so a double
// click on "publish" cannot notify members twice.
func (q *Queries) ClaimNewsNotification(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, claimNewsNotification, id)
	err := row.Scan(&id)
	return id, err
}

const countNewsViewers = `-- name: CountNewsViewers :one
SELECT COUNT(*) FROM news_views v
WHERE v.news_id = $1
  AND (
      $2::text = ''
      OR ($2::text = 'pro' AND v.read_as_pro AND NOT v.gated)
      OR ($2::text = 'free' AND v.gated)
      OR ($2::text = 'push' AND v.from_push)
      OR ($2::text = 'upgrade' AND v.upgrade_clicked)
  )
`

type CountNewsViewersParams struct {
	NewsID int32  `json:"news_id"`
	Filter string `json:"filter"`
}

func (q *Queries) CountNewsViewers(ctx context.Context, arg CountNewsViewersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewsViewers, arg.NewsID, arg.Filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewsViewersByNews = `-- name: CountNewsViewersByNews :many
SELECT news_id, COUNT(*) AS viewers FROM news_views
WHERE news_id = ANY($1::int[])
GROUP BY news_id
`

type CountNewsViewersByNewsRow struct {
	NewsID  int32 `json:"news_id"`
	Viewers int64 `json:"viewers"`
}

func (q *Queries) CountNewsViewersByNews(ctx context.Context, newsIds []int32) ([]CountNewsViewersByNewsRow, error) {
	rows, err := q.db.Query(ctx, countNewsViewersByNews, newsIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountNewsViewersByNewsRow
	for rows.Next() {
		var i CountNewsViewersByNewsRow
		if err := rows.Scan(&i.NewsID, &i.Viewers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPublishedNews = `-- name: CountPublishedNews :one
SELECT COUNT(*) FROM news WHERE status = 'published'
`

func (q *Queries) CountPublishedNews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedNews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNews = `-- name: CountUnreadNews :one
SELECT COUNT(*) FROM news n
WHERE n.status = 'published'
  AND n.published_at > COALESCE(
      (SELECT ns.last_seen_at FROM news_seen ns WHERE ns.user_id = $1),
      '-infinity'::timestamptz
  )
`

func (q *Queries) CountUnreadNews(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNews, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithActiveDevice = `-- name: CountUsersWithActiveDevice :one
SELECT COUNT(DISTINCT user_id) FROM device_tokens
WHERE is_active = TRUE AND user_id = ANY($1::int[])
`

// How many of the given members can actually receive a push right now.
func (q *Queries) CountUsersWithActiveDevice(ctx context.Context, userIds []int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithActiveDevice, userIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNews = `-- name: CreateNews :one

INSERT INTO news (
    title, summary, body_html, cover_image_url, source_url, source_name,
    source_text, source_images, ai_provider, ai_model, created_by_admin_id,
    notification_title, notification_body
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13
)
RETURNING id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body
`

type CreateNewsParams struct {
	Title             string      `json:"title"`
	Summary           string      `json:"summary"`
	BodyHtml          string      `json:"body_html"`
	CoverImageUrl     pgtype.Text `json:"cover_image_url"`
	SourceUrl         pgtype.Text `json:"source_url"`
	SourceName        pgtype.Text `json:"source_name"`
	SourceText        pgtype.Text `json:"source_text"`
	SourceImages      []byte      `json:"source_images"`
	AiProvider        pgtype.Text `json:"ai_provider"`
	AiModel           pgtype.Text `json:"ai_model"`
	CreatedByAdminID  pgtype.Int4 `json:"created_by_admin_id"`
	NotificationTitle string      `json:"notification_title"`
	NotificationBody  string      `json:"notification_body"`
}

// ------------------------------------------------------------------ admin
func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, createNews,
		arg.Title,
		arg.Summary,
		arg.BodyHtml,
		arg.CoverImageUrl,
		arg.SourceUrl,
		arg.SourceName,
		arg.SourceText,
		arg.SourceImages,
		arg.AiProvider,
		arg.AiModel,
		arg.CreatedByAdminID,
		arg.NotificationTitle,
		arg.NotificationBody,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Summary,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.SourceUrl,
		&i.SourceName,
		&i.SourceText,
		&i.Status,
		&i.AiProvider,
		&i.AiModel,
		&i.CreatedByAdminID,
		&i.PublishedAt,
		&i.NotifiedAt,
		&i.NotifiedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceImages,
		&i.NotificationTitle,
		&i.NotificationBody,
	)
	return i, err
}

const deleteNews = `-- name: DeleteNews :execrows
DELETE FROM news WHERE public_id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, publicID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNews, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNewsInterests = `-- name: DeleteNewsInterests :exec
DELETE FROM news_interests WHERE news_id = $1
`

func (q *Queries) DeleteNewsInterests(ctx context.Context, newsID int32) error {
	_, err := q.db.Exec(ctx, deleteNewsInterests, newsID)
	return err
}

const getNewsByPublicID = `-- name: GetNewsByPublicID :one
SELECT id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body FROM news WHERE public_id = $1
`

func (q *Queries) GetNewsByPublicID(ctx context.Context, publicID pgtype.UUID) (News, error) {
	row := q.db.QueryRow(ctx, getNewsByPublicID, publicID)
	var i News
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Summary,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.SourceUrl,
		&i.SourceName,
		&i.SourceText,
		&i.Status,
		&i.AiProvider,
		&i.AiModel,
		&i.CreatedByAdminID,
		&i.PublishedAt,
		&i.NotifiedAt,
		&i.NotifiedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceImages,
		&i.NotificationTitle,
		&i.NotificationBody,
	)
	return i, err
}

const getPublishedNews = `-- name: GetPublishedNews :one
SELECT id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body FROM news WHERE public_id = $1 AND status = 'published'
`

func (q *Queries) GetPublishedNews(ctx context.Context, publicID pgtype.UUID) (News, error) {
	row := q.db.QueryRow(ctx, getPublishedNews, publicID)
	var i News
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Summary,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.SourceUrl,
		&i.SourceName,
		&i.SourceText,
		&i.Status,
		&i.AiProvider,
		&i.AiModel,
		&i.CreatedByAdminID,
		&i.PublishedAt,
		&i.NotifiedAt,
		&i.NotifiedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceImages,
		&i.NotificationTitle,
		&i.NotificationBody,
	)
	return i, err
}

const insertNewsDeliveries = `-- name: InsertNewsDeliveries :exec

INSERT INTO news_deliveries (news_id, user_id, was_pro)
SELECT $1::int, unnest($2::int[]), unnest($3::bool[])
ON CONFLICT (news_id, user_id) DO NOTHING
`

type InsertNewsDeliveriesParams struct {
	NewsID  int32   `json:"news_id"`
	UserIds []int32 `json:"user_ids"`
	WasPro  []bool  `json:"was_pro"`
}

// ------------------------------------------------------------- analytics
// Two unnests in the select list are zipped row by row, so user_ids[i] gets
// was_pro[i]. The arrays are always built together and are the same length.
func (q *Queries) InsertNewsDeliveries(ctx context.Context, arg InsertNewsDeliveriesParams) error {
	_, err := q.db.Exec(ctx, insertNewsDeliveries, arg.NewsID, arg.UserIds, arg.WasPro)
	return err
}

const isProUser = `-- name: IsProUser :one

SELECT EXISTS (
    SELECT 1 FROM user_subscriptions
    WHERE user_id = $1
      AND tier_name = 'pro'
      AND is_active = TRUE
      AND (expires_at IS NULL OR expires_at > NOW())
) AS is_pro
`

// --------------------------------------------------------------- members
func (q *Queries) IsProUser(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRow(ctx, isProUser, userID)
	var is_pro bool
	err := row.Scan(&is_pro)
	return is_pro, err
}

const listNewsInterests = `-- name: ListNewsInterests :many
SELECT ni.news_id, i.id, i.name_ar
FROM news_interests ni
JOIN interests i ON i.id = ni.interest_id
WHERE ni.news_id = ANY($1::int[])
ORDER BY i.name_ar
`

type ListNewsInterestsRow struct {
	NewsID int32  `json:"news_id"`
	ID     int32  `json:"id"`
	NameAr string `json:"name_ar"`
}

func (q *Queries) ListNewsInterests(ctx context.Context, newsIds []int32) ([]ListNewsInterestsRow, error) {
	rows, err := q.db.Query(ctx, listNewsInterests, newsIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsInterestsRow
	for rows.Next() {
		var i ListNewsInterestsRow
		if err := rows.Scan(&i.NewsID, &i.ID, &i.NameAr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsRecipients = `-- name: ListNewsRecipients :many
SELECT u.id,
       EXISTS (
           SELECT 1 FROM user_subscriptions us
           WHERE us.user_id = u.id
             AND us.tier_name = 'pro'
             AND us.is_active = TRUE
             AND (us.expires_at IS NULL OR us.expires_at > NOW())
       ) AS is_pro
FROM users u
WHERE u.status = 'active'
  AND u.job_key <> 'shipping_company'
  AND COALESCE(u.role, '') <> 'admin'
  AND (
      NOT $1::bool
      OR EXISTS (
          SELECT 1 FROM user_interests ui
          JOIN news_interests ni ON ni.interest_id = ui.interest_id
          WHERE ui.user_id = u.id AND ni.news_id = $2::int
      )
  )
ORDER BY u.id
`

type ListNewsRecipientsParams struct {
	ByInterest bool  `json:"by_interest"`
	NewsID     int32 `json:"news_id"`
}

type ListNewsRecipientsRow struct {
	ID    int32 `json:"id"`
	IsPro bool  `json:"is_pro"`
}

// Members to notify about a story: every active member, Pro or not — a
// non-Pro member who taps it is shown the story's teaser and an upgrade
// prompt. by_interest narrows it to members who share one of the story's
// interests. Carriers and admins are not the audience.
func (q *Queries) ListNewsRecipients(ctx context.Context, arg ListNewsRecipientsParams) ([]ListNewsRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listNewsRecipients, arg.ByInterest, arg.NewsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsRecipientsRow
	for rows.Next() {
		var i ListNewsRecipientsRow
		if err := rows.Scan(&i.ID, &i.IsPro); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsViewers = `-- name: ListNewsViewers :many
SELECT u.public_id, u.name, u.phone, u.email,
       v.from_push, v.read_as_pro, v.gated, v.read_to_end, v.upgrade_clicked,
       v.view_count, v.first_viewed_at, v.last_viewed_at
FROM news_views v
JOIN users u ON u.id = v.user_id
WHERE v.news_id = $1
  AND (
      $2::text = ''
      OR ($2::text = 'pro' AND v.read_as_pro AND NOT v.gated)
      OR ($2::text = 'free' AND v.gated)
      OR ($2::text = 'push' AND v.from_push)
      OR ($2::text = 'upgrade' AND v.upgrade_clicked)
  )
ORDER BY v.last_viewed_at DESC
LIMIT $4 OFFSET $3
`

type ListNewsViewersParams struct {
	NewsID int32  `json:"news_id"`
	Filter string `json:"filter"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

type ListNewsViewersRow struct {
	PublicID       pgtype.UUID        `json:"public_id"`
	Name           string             `json:"name"`
	Phone          pgtype.Text        `json:"phone"`
	Email          string             `json:"email"`
	FromPush       bool               `json:"from_push"`
	ReadAsPro      bool               `json:"read_as_pro"`
	Gated          bool               `json:"gated"`
	ReadToEnd      bool               `json:"read_to_end"`
	UpgradeClicked bool               `json:"upgrade_clicked"`
	ViewCount      int32              `json:"view_count"`
	FirstViewedAt  pgtype.Timestamptz `json:"first_viewed_at"`
	LastViewedAt   pgtype.Timestamptz `json:"last_viewed_at"`
}

func (q *Queries) ListNewsViewers(ctx context.Context, arg ListNewsViewersParams) ([]ListNewsViewersRow, error) {
	rows, err := q.db.Query(ctx, listNewsViewers,
		arg.NewsID,
		arg.Filter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsViewersRow
	for rows.Next() {
		var i ListNewsViewersRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.FromPush,
			&i.ReadAsPro,
			&i.Gated,
			&i.ReadToEnd,
			&i.UpgradeClicked,
			&i.ViewCount,
			&i.FirstViewedAt,
			&i.LastViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedNews = `-- name: ListPublishedNews :many
SELECT n.public_id, n.title, n.summary, n.cover_image_url, n.published_at,
       n.published_at > COALESCE(
           (SELECT ns.last_seen_at FROM news_seen ns WHERE ns.user_id = $1),
           '-infinity'::timestamptz
       ) AS is_new
FROM news n
WHERE n.status = 'published'
ORDER BY n.published_at DESC, n.id DESC
LIMIT $3 OFFSET $2
`

type ListPublishedNewsParams struct {
	UserID int32 `json:"user_id"`
	Off    int32 `json:"off"`
	Lim    int32 `json:"lim"`
}

type ListPublishedNewsRow struct {
	PublicID      pgtype.UUID        `json:"public_id"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	IsNew         bool               `json:"is_new"`
}

func (q *Queries) ListPublishedNews(ctx context.Context, arg ListPublishedNewsParams) ([]ListPublishedNewsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedNews, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedNewsRow
	for rows.Next() {
		var i ListPublishedNewsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Title,
			&i.Summary,
			&i.CoverImageUrl,
			&i.PublishedAt,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsDelivered = `-- name: MarkNewsDelivered :exec
UPDATE news_deliveries SET delivered = TRUE WHERE news_id = $1 AND user_id = $2
`

type MarkNewsDeliveredParams struct {
	NewsID int32 `json:"news_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNewsDelivered(ctx context.Context, arg MarkNewsDeliveredParams) error {
	_, err := q.db.Exec(ctx, markNewsDelivered, arg.NewsID, arg.UserID)
	return err
}

const markNewsReadToEnd = `-- name: MarkNewsReadToEnd :execrows
UPDATE news_views SET read_to_end = TRUE
WHERE news_id = $1 AND user_id = $2 AND read_as_pro
`

type MarkNewsReadToEndParams struct {
	NewsID int32 `json:"news_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNewsReadToEnd(ctx context.Context, arg MarkNewsReadToEndParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNewsReadToEnd, arg.NewsID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNewsSeen = `-- name: MarkNewsSeen :exec
INSERT INTO news_seen (user_id, last_seen_at) VALUES ($1, NOW())
ON CONFLICT (user_id) DO UPDATE SET last_seen_at = NOW()
`

func (q *Queries) MarkNewsSeen(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markNewsSeen, userID)
	return err
}

const markNewsUpgradeClicked = `-- name: MarkNewsUpgradeClicked :execrows
UPDATE news_views SET upgrade_clicked = TRUE
WHERE news_id = $1 AND user_id = $2 AND gated
`

type MarkNewsUpgradeClickedParams struct {
	NewsID int32 `json:"news_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNewsUpgradeClicked(ctx context.Context, arg MarkNewsUpgradeClickedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNewsUpgradeClicked, arg.NewsID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const newsDeliveryStats = `-- name: NewsDeliveryStats :one
SELECT COUNT(*)                                   AS recipients,
       COUNT(*) FILTER (WHERE was_pro)            AS recipients_pro,
       COUNT(*) FILTER (WHERE delivered)          AS delivered,
       COUNT(*) FILTER (WHERE delivered AND was_pro) AS delivered_pro
FROM news_deliveries WHERE news_id = $1
`

type NewsDeliveryStatsRow struct {
	Recipients    int64 `json:"recipients"`
	RecipientsPro int64 `json:"recipients_pro"`
	Delivered     int64 `json:"delivered"`
	DeliveredPro  int64 `json:"delivered_pro"`
}

func (q *Queries) NewsDeliveryStats(ctx context.Context, newsID int32) (NewsDeliveryStatsRow, error) {
	row := q.db.QueryRow(ctx, newsDeliveryStats, newsID)
	var i NewsDeliveryStatsRow
	err := row.Scan(
		&i.Recipients,
		&i.RecipientsPro,
		&i.Delivered,
		&i.DeliveredPro,
	)
	return i, err
}

const newsViewStats = `-- name: NewsViewStats :one
SELECT COUNT(*)                                                  AS viewers,
       COUNT(*) FILTER (WHERE read_as_pro AND NOT gated)         AS viewers_pro,
       COUNT(*) FILTER (WHERE gated)                             AS viewers_free,
       COUNT(*) FILTER (WHERE from_push)                         AS push_opens,
       COUNT(*) FILTER (WHERE from_push AND read_as_pro AND NOT gated) AS push_opens_pro,
       COUNT(*) FILTER (WHERE from_push AND gated)               AS push_opens_free,
       COUNT(*) FILTER (WHERE read_to_end)                       AS read_to_end,
       COUNT(*) FILTER (WHERE upgrade_clicked)                   AS upgrade_clicks,
       COUNT(*) FILTER (WHERE gated AND read_as_pro)             AS converted,
       COALESCE(SUM(view_count), 0)::bigint                      AS total_views
FROM news_views WHERE news_id = $1
`

type NewsViewStatsRow struct {
	Viewers       int64 `json:"viewers"`
	ViewersPro    int64 `json:"viewers_pro"`
	ViewersFree   int64 `json:"viewers_free"`
	PushOpens     int64 `json:"push_opens"`
	PushOpensPro  int64 `json:"push_opens_pro"`
	PushOpensFree int64 `json:"push_opens_free"`
	ReadToEnd     int64 `json:"read_to_end"`
	UpgradeClicks int64 `json:"upgrade_clicks"`
	Converted     int64 `json:"converted"`
	TotalViews    int64 `json:"total_views"`
}

// "Pro" below means read it and never hit the prompt; "free" means hit the
// prompt, whether or not they upgraded afterwards (converted).
func (q *Queries) NewsViewStats(ctx context.Context, newsID int32) (NewsViewStatsRow, error) {
	row := q.db.QueryRow(ctx, newsViewStats, newsID)
	var i NewsViewStatsRow
	err := row.Scan(
		&i.Viewers,
		&i.ViewersPro,
		&i.ViewersFree,
		&i.PushOpens,
		&i.PushOpensPro,
		&i.PushOpensFree,
		&i.ReadToEnd,
		&i.UpgradeClicks,
		&i.Converted,
		&i.TotalViews,
	)
	return i, err
}

const publishNews = `-- name: PublishNews :one
UPDATE news SET
    status       = 'published',
    published_at = COALESCE(published_at, NOW()),
    updated_at   = NOW()
WHERE public_id = $1
RETURNING id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body
`

// First publish stamps published_at; publishing again after an unpublish keeps
// the original date so the story does not jump back to the top of the list.
func (q *Queries) PublishNews(ctx context.Context, publicID pgtype.UUID) (News, error) {
	row := q.db.QueryRow(ctx, publishNews, publicID)
	var i News
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Summary,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.SourceUrl,
		&i.SourceName,
		&i.SourceText,
		&i.Status,
		&i.AiProvider,
		&i.AiModel,
		&i.CreatedByAdminID,
		&i.PublishedAt,
		&i.NotifiedAt,
		&i.NotifiedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceImages,
		&i.NotificationTitle,
		&i.NotificationBody,
	)
	return i, err
}

const recordNewsView = `-- name: RecordNewsView :exec
INSERT INTO news_views (news_id, user_id, from_push, read_as_pro, gated)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (news_id, user_id) DO UPDATE SET
    from_push      = news_views.from_push OR EXCLUDED.from_push,
    read_as_pro    = news_views.read_as_pro OR EXCLUDED.read_as_pro,
    gated          = news_views.gated OR EXCLUDED.gated,
    view_count     = news_views.view_count + 1,
    last_viewed_at = NOW()
`

type RecordNewsViewParams struct {
	NewsID    int32 `json:"news_id"`
	UserID    int32 `json:"user_id"`
	FromPush  bool  `json:"from_push"`
	ReadAsPro bool  `json:"read_as_pro"`
	Gated     bool  `json:"gated"`
}

// Flags only ever turn on: a member who opened from the push once stays
// counted as a push open however they come back.
func (q *Queries) RecordNewsView(ctx context.Context, arg RecordNewsViewParams) error {
	_, err := q.db.Exec(ctx, recordNewsView,
		arg.NewsID,
		arg.UserID,
		arg.FromPush,
		arg.ReadAsPro,
		arg.Gated,
	)
	return err
}

const setNewsNotifiedCount = `-- name: SetNewsNotifiedCount :exec
UPDATE news SET notified_count = $2 WHERE id = $1
`

type SetNewsNotifiedCountParams struct {
	ID            int32 `json:"id"`
	NotifiedCount int32 `json:"notified_count"`
}

func (q *Queries) SetNewsNotifiedCount(ctx context.Context, arg SetNewsNotifiedCountParams) error {
	_, err := q.db.Exec(ctx, setNewsNotifiedCount, arg.ID, arg.NotifiedCount)
	return err
}

const unpublishNews = `-- name: UnpublishNews :one
UPDATE news SET status = 'draft', updated_at = NOW()
WHERE public_id = $1
RETURNING id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body
`

func (q *Queries) UnpublishNews(ctx context.Context, publicID pgtype.UUID) (News, error) {
	row := q.db.QueryRow(ctx, unpublishNews, publicID)
	var i News
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Summary,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.SourceUrl,
		&i.SourceName,
		&i.SourceText,
		&i.Status,
		&i.AiProvider,
		&i.AiModel,
		&i.CreatedByAdminID,
		&i.PublishedAt,
		&i.NotifiedAt,
		&i.NotifiedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceImages,
		&i.NotificationTitle,
		&i.NotificationBody,
	)
	return i, err
}

const updateNews = `-- name: UpdateNews :one
UPDATE news SET
    title           = $1,
    summary         = $2,
    body_html       = $3,
    cover_image_url = $4,
    source_url      = $5,
    source_name     = $6,
    source_text     = $7,
    source_images   = $8,
    ai_provider     = $9,
    ai_model        = $10,
    notification_title = $11,
    notification_body  = $12,
    updated_at      = NOW()
WHERE public_id = $13
RETURNING id, public_id, title, summary, body_html, cover_image_url, source_url, source_name, source_text, status, ai_provider, ai_model, created_by_admin_id, published_at, notified_at, notified_count, created_at, updated_at, source_images, notification_title, notification_body
`

type UpdateNewsParams struct {
	Title             string      `json:"title"`
	Summary           string      `json:"summary"`
	BodyHtml          string      `json:"body_html"`
	CoverImageUrl     pgtype.Text `json:"cover_image_url"`
	SourceUrl         pgtype.Text `json:"source_url"`
	SourceName        pgtype.Text `json:"source_name"`
	SourceText        pgtype.Text `json:"source_text"`
	SourceImages      []byte      `json:"source_images"`
	AiProvider        pgtype.Text `json:"ai_provider"`
	AiModel           pgtype.Text `json:"ai_model"`
	NotificationTitle string      `json:"notification_title"`
	NotificationBody  string      `json:"notification_body"`
	PublicID          pgtype.UUID `json:"public_id"`
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, updateNews,
		arg.Title,
		arg.Summary,
		arg.BodyHtml,
		arg.CoverImageUrl,
		arg.SourceUrl,
		arg.SourceName,
		arg.SourceText,
		arg.SourceImages,
		arg.AiProvider,
		arg.AiModel,
		arg.NotificationTitle,
		arg.NotificationBody,
		arg.PublicID,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Summary,
		&i.BodyHtml,
		&i.CoverImageUrl,
		&i.SourceUrl,
		&i.SourceName,
		&i.SourceText,
		&i.Status,
		&i.AiProvider,
		&i.AiModel,
		&i.CreatedByAdminID,
		&i.PublishedAt,
		&i.NotifiedAt,
		&i.NotifiedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceImages,
		&i.NotificationTitle,
		&i.NotificationBody,
	)
	return i, err
}
