// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: notifications.sql

package sqlc

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, title, body, event_type, data)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, title, body, event_type, data, is_read, created_at
`

type CreateNotificationParams struct {
	UserID    int32  `json:"user_id"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	EventType string `json:"event_type"`
	Data      []byte `json:"data"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.EventType,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.EventType,
		&i.Data,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications n1
WHERE n1.user_id = $1
AND n1.id NOT IN (
    SELECT n2.id FROM notifications n2
    WHERE n2.user_id = $1
    ORDER BY n2.created_at DESC
    LIMIT $2::integer
)
`

type DeleteOldNotificationsParams struct {
	UserID    int32 `json:"user_id"`
	KeepCount int32 `json:"keep_count"`
}

func (q *Queries) DeleteOldNotifications(ctx context.Context, arg DeleteOldNotificationsParams) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, arg.UserID, arg.KeepCount)
	return err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, title, body, event_type, data, is_read, created_at FROM notifications WHERE user_id = $1
ORDER BY created_at DESC LIMIT $2
`

type ListNotificationsByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.EventType,
			&i.Data,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = TRUE WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = TRUE WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
