// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders 
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status IN ('seller_confirmed', 'buyer_confirmed')
`

func (q *Queries) CancelOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelOrder, id)
	return err
}

const checkOrderExistsForBuyRequestAndSupplier = `-- name: CheckOrderExistsForBuyRequestAndSupplier :one
SELECT EXISTS(SELECT 1 FROM orders WHERE buy_request_id = $1 AND seller_id = $2)
`

type CheckOrderExistsForBuyRequestAndSupplierParams struct {
	BuyRequestID pgtype.Int4 `json:"buy_request_id"`
	SellerID     int32       `json:"seller_id"`
}

func (q *Queries) CheckOrderExistsForBuyRequestAndSupplier(ctx context.Context, arg CheckOrderExistsForBuyRequestAndSupplierParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrderExistsForBuyRequestAndSupplier, arg.BuyRequestID, arg.SellerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkOrderExistsForSellAuction = `-- name: CheckOrderExistsForSellAuction :one
SELECT EXISTS(SELECT 1 FROM orders WHERE sell_auction_id = $1)
`

func (q *Queries) CheckOrderExistsForSellAuction(ctx context.Context, sellAuctionID pgtype.Int4) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrderExistsForSellAuction, sellAuctionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const completeOrder = `-- name: CompleteOrder :exec
UPDATE orders SET status = 'completed', completed_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) CompleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, completeOrder, id)
	return err
}

const confirmOrderAsBuyer = `-- name: ConfirmOrderAsBuyer :exec
UPDATE orders 
SET status = 'completed', buyer_confirmed_at = NOW(), completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'seller_confirmed' AND confirmation_deadline > NOW()
`

func (q *Queries) ConfirmOrderAsBuyer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, confirmOrderAsBuyer, id)
	return err
}

const confirmOrderAsSeller = `-- name: ConfirmOrderAsSeller :exec
UPDATE orders 
SET status = 'completed', seller_confirmed_at = NOW(), completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'buyer_confirmed' AND confirmation_deadline > NOW()
`

func (q *Queries) ConfirmOrderAsSeller(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, confirmOrderAsSeller, id)
	return err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) FROM orders WHERE seller_id = $1 OR buyer_id = $1
`

func (q *Queries) CountOrdersByUser(ctx context.Context, sellerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderFromBuyRequest = `-- name: CreateOrderFromBuyRequest :one
INSERT INTO orders (
    buy_request_id, seller_id, buyer_id, final_price, quantity, unit,
    seller_name, seller_phone, seller_region,
    buyer_name, buyer_phone, buyer_region,
    source_public_id, status, buyer_confirmed_at, confirmation_deadline
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, 'buyer_confirmed', NOW(), NOW() + INTERVAL '30 minutes'
) RETURNING id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at
`

type CreateOrderFromBuyRequestParams struct {
	BuyRequestID   pgtype.Int4    `json:"buy_request_id"`
	SellerID       int32          `json:"seller_id"`
	BuyerID        int32          `json:"buyer_id"`
	FinalPrice     pgtype.Numeric `json:"final_price"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	SellerName     string         `json:"seller_name"`
	SellerPhone    string         `json:"seller_phone"`
	SellerRegion   string         `json:"seller_region"`
	BuyerName      string         `json:"buyer_name"`
	BuyerPhone     string         `json:"buyer_phone"`
	BuyerRegion    string         `json:"buyer_region"`
	SourcePublicID pgtype.UUID    `json:"source_public_id"`
}

func (q *Queries) CreateOrderFromBuyRequest(ctx context.Context, arg CreateOrderFromBuyRequestParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrderFromBuyRequest,
		arg.BuyRequestID,
		arg.SellerID,
		arg.BuyerID,
		arg.FinalPrice,
		arg.Quantity,
		arg.Unit,
		arg.SellerName,
		arg.SellerPhone,
		arg.SellerRegion,
		arg.BuyerName,
		arg.BuyerPhone,
		arg.BuyerRegion,
		arg.SourcePublicID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.SellerID,
		&i.BuyerID,
		&i.FinalPrice,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.SellerConfirmedAt,
		&i.BuyerConfirmedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerPhone,
		&i.SellerRegion,
		&i.BuyerName,
		&i.BuyerPhone,
		&i.BuyerRegion,
		&i.SourcePublicID,
		&i.ConfirmationDeadline,
		&i.CancelledAt,
	)
	return i, err
}

const createOrderFromSellAuction = `-- name: CreateOrderFromSellAuction :one
INSERT INTO orders (
    sell_auction_id, seller_id, buyer_id, final_price, quantity, unit,
    seller_name, seller_phone, seller_region,
    buyer_name, buyer_phone, buyer_region,
    source_public_id, status, seller_confirmed_at, confirmation_deadline
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, 'seller_confirmed', NOW(), NOW() + INTERVAL '30 minutes'
) RETURNING id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at
`

type CreateOrderFromSellAuctionParams struct {
	SellAuctionID  pgtype.Int4    `json:"sell_auction_id"`
	SellerID       int32          `json:"seller_id"`
	BuyerID        int32          `json:"buyer_id"`
	FinalPrice     pgtype.Numeric `json:"final_price"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	SellerName     string         `json:"seller_name"`
	SellerPhone    string         `json:"seller_phone"`
	SellerRegion   string         `json:"seller_region"`
	BuyerName      string         `json:"buyer_name"`
	BuyerPhone     string         `json:"buyer_phone"`
	BuyerRegion    string         `json:"buyer_region"`
	SourcePublicID pgtype.UUID    `json:"source_public_id"`
}

func (q *Queries) CreateOrderFromSellAuction(ctx context.Context, arg CreateOrderFromSellAuctionParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrderFromSellAuction,
		arg.SellAuctionID,
		arg.SellerID,
		arg.BuyerID,
		arg.FinalPrice,
		arg.Quantity,
		arg.Unit,
		arg.SellerName,
		arg.SellerPhone,
		arg.SellerRegion,
		arg.BuyerName,
		arg.BuyerPhone,
		arg.BuyerRegion,
		arg.SourcePublicID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.SellerID,
		&i.BuyerID,
		&i.FinalPrice,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.SellerConfirmedAt,
		&i.BuyerConfirmedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerPhone,
		&i.SellerRegion,
		&i.BuyerName,
		&i.BuyerPhone,
		&i.BuyerRegion,
		&i.SourcePublicID,
		&i.ConfirmationDeadline,
		&i.CancelledAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.SellerID,
		&i.BuyerID,
		&i.FinalPrice,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.SellerConfirmedAt,
		&i.BuyerConfirmedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerPhone,
		&i.SellerRegion,
		&i.BuyerName,
		&i.BuyerPhone,
		&i.BuyerRegion,
		&i.SourcePublicID,
		&i.ConfirmationDeadline,
		&i.CancelledAt,
	)
	return i, err
}

const getOrderByPublicID = `-- name: GetOrderByPublicID :one
SELECT id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at FROM orders WHERE public_id = $1
`

func (q *Queries) GetOrderByPublicID(ctx context.Context, publicID pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByPublicID, publicID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.SellerID,
		&i.BuyerID,
		&i.FinalPrice,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.SellerConfirmedAt,
		&i.BuyerConfirmedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerPhone,
		&i.SellerRegion,
		&i.BuyerName,
		&i.BuyerPhone,
		&i.BuyerRegion,
		&i.SourcePublicID,
		&i.ConfirmationDeadline,
		&i.CancelledAt,
	)
	return i, err
}

const getOrdersPendingConfirmation = `-- name: GetOrdersPendingConfirmation :many
SELECT id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at FROM orders 
WHERE confirmation_deadline < NOW() 
  AND status IN ('seller_confirmed', 'buyer_confirmed')
ORDER BY confirmation_deadline ASC
`

func (q *Queries) GetOrdersPendingConfirmation(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersPendingConfirmation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.SellerID,
			&i.BuyerID,
			&i.FinalPrice,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.SellerConfirmedAt,
			&i.BuyerConfirmedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerPhone,
			&i.SellerRegion,
			&i.BuyerName,
			&i.BuyerPhone,
			&i.BuyerRegion,
			&i.SourcePublicID,
			&i.ConfirmationDeadline,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByBuyRequest = `-- name: ListOrdersByBuyRequest :many
SELECT id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at FROM orders WHERE buy_request_id = $1
`

func (q *Queries) ListOrdersByBuyRequest(ctx context.Context, buyRequestID pgtype.Int4) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByBuyRequest, buyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.SellerID,
			&i.BuyerID,
			&i.FinalPrice,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.SellerConfirmedAt,
			&i.BuyerConfirmedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerPhone,
			&i.SellerRegion,
			&i.BuyerName,
			&i.BuyerPhone,
			&i.BuyerRegion,
			&i.SourcePublicID,
			&i.ConfirmationDeadline,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersBySellAuction = `-- name: ListOrdersBySellAuction :many
SELECT id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at FROM orders WHERE sell_auction_id = $1
`

func (q *Queries) ListOrdersBySellAuction(ctx context.Context, sellAuctionID pgtype.Int4) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersBySellAuction, sellAuctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.SellerID,
			&i.BuyerID,
			&i.FinalPrice,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.SellerConfirmedAt,
			&i.BuyerConfirmedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerPhone,
			&i.SellerRegion,
			&i.BuyerName,
			&i.BuyerPhone,
			&i.BuyerRegion,
			&i.SourcePublicID,
			&i.ConfirmationDeadline,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at FROM orders WHERE seller_id = $1 OR buyer_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	SellerID int32 `json:"seller_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.SellerID,
			&i.BuyerID,
			&i.FinalPrice,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.SellerConfirmedAt,
			&i.BuyerConfirmedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerPhone,
			&i.SellerRegion,
			&i.BuyerName,
			&i.BuyerPhone,
			&i.BuyerRegion,
			&i.SourcePublicID,
			&i.ConfirmationDeadline,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
