// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetCode = `-- name: ConsumePasswordResetCode :exec
UPDATE password_reset_codes SET consumed_at = NOW() WHERE id = $1
`

func (q *Queries) ConsumePasswordResetCode(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, consumePasswordResetCode, id)
	return err
}

const countRecentPasswordResetCodes = `-- name: CountRecentPasswordResetCodes :one
SELECT COUNT(*) FROM password_reset_codes
WHERE user_id = $1::int AND created_at > $2::timestamptz
`

type CountRecentPasswordResetCodesParams struct {
	UserID int32              `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

// Throttle input: how many codes this user has requested since a cutoff.
func (q *Queries) CountRecentPasswordResetCodes(ctx context.Context, arg CountRecentPasswordResetCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPasswordResetCodes, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordResetCode = `-- name: CreatePasswordResetCode :one
INSERT INTO password_reset_codes (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, expires_at, consumed_at, attempts, created_at
`

type CreatePasswordResetCodeParams struct {
	UserID    int32              `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetCode(ctx context.Context, arg CreatePasswordResetCodeParams) (PasswordResetCode, error) {
	row := q.db.QueryRow(ctx, createPasswordResetCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getLivePasswordResetCode = `-- name: GetLivePasswordResetCode :one
SELECT id, user_id, code_hash, expires_at, consumed_at, attempts, created_at FROM password_reset_codes
WHERE user_id = $1::int
  AND consumed_at IS NULL
  AND expires_at > NOW()
  AND attempts < $2::int
ORDER BY created_at DESC
LIMIT 1
`

type GetLivePasswordResetCodeParams struct {
	UserID      int32 `json:"user_id"`
	MaxAttempts int32 `json:"max_attempts"`
}

// The user's most recent code that is still usable: not consumed, not expired,
// and not yet burned through its attempt allowance.
func (q *Queries) GetLivePasswordResetCode(ctx context.Context, arg GetLivePasswordResetCodeParams) (PasswordResetCode, error) {
	row := q.db.QueryRow(ctx, getLivePasswordResetCode, arg.UserID, arg.MaxAttempts)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :exec
UPDATE password_reset_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementPasswordResetAttempts, id)
	return err
}

const invalidatePasswordResetCodes = `-- name: InvalidatePasswordResetCodes :exec
UPDATE password_reset_codes SET consumed_at = NOW()
WHERE user_id = $1 AND consumed_at IS NULL
`

// After a successful reset, retire every other outstanding code for the user.
func (q *Queries) InvalidatePasswordResetCodes(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetCodes, userID)
	return err
}

const markPasswordChanged = `-- name: MarkPasswordChanged :exec
UPDATE users SET password_changed_at = NOW(), updated_at = NOW() WHERE id = $1
`

// Revocation marker — tokens issued before this are rejected downstream.
func (q *Queries) MarkPasswordChanged(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markPasswordChanged, id)
	return err
}
