// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptShippingQuote(ctx context.Context, id int32) (ShippingQuote, error)
	AcceptSupplyOffer(ctx context.Context, id int32) error
	AddCarrierRegion(ctx context.Context, arg AddCarrierRegionParams) error
	AddUserInterest(ctx context.Context, arg AddUserInterestParams) error
	AnalyticsActiveSubscriptionsByTier(ctx context.Context) ([]AnalyticsActiveSubscriptionsByTierRow, error)
	AnalyticsCountActiveSessions(ctx context.Context) (int64, error)
	AnalyticsCountBidsByDay(ctx context.Context, arg AnalyticsCountBidsByDayParams) ([]AnalyticsCountBidsByDayRow, error)
	AnalyticsCountBuyRequestsByDay(ctx context.Context, arg AnalyticsCountBuyRequestsByDayParams) ([]AnalyticsCountBuyRequestsByDayRow, error)
	AnalyticsCountClosedAuctionsByDay(ctx context.Context, arg AnalyticsCountClosedAuctionsByDayParams) ([]AnalyticsCountClosedAuctionsByDayRow, error)
	AnalyticsCountFailedLoginsByDay(ctx context.Context, arg AnalyticsCountFailedLoginsByDayParams) ([]AnalyticsCountFailedLoginsByDayRow, error)
	AnalyticsCountIssuesByDay(ctx context.Context, arg AnalyticsCountIssuesByDayParams) ([]AnalyticsCountIssuesByDayRow, error)
	AnalyticsCountOpenIssues(ctx context.Context) (int64, error)
	AnalyticsCountUsersByDay(ctx context.Context, arg AnalyticsCountUsersByDayParams) ([]AnalyticsCountUsersByDayRow, error)
	AnalyticsInactiveSubscriptionsCount(ctx context.Context) (int64, error)
	AnalyticsIssuesByStatus(ctx context.Context, arg AnalyticsIssuesByStatusParams) ([]AnalyticsIssuesByStatusRow, error)
	AnalyticsOrdersGMVByDay(ctx context.Context, arg AnalyticsOrdersGMVByDayParams) ([]AnalyticsOrdersGMVByDayRow, error)
	AnalyticsOverviewOrders(ctx context.Context, arg AnalyticsOverviewOrdersParams) (AnalyticsOverviewOrdersRow, error)
	AnalyticsOverviewUsers(ctx context.Context, arg AnalyticsOverviewUsersParams) (AnalyticsOverviewUsersRow, error)
	AnalyticsProfileCompletionRatio(ctx context.Context) (AnalyticsProfileCompletionRatioRow, error)
	AnalyticsUsersByInterest(ctx context.Context, interestID int32) ([]AnalyticsUsersByInterestRow, error)
	AnalyticsUsersBySource(ctx context.Context, arg AnalyticsUsersBySourceParams) ([]AnalyticsUsersBySourceRow, error)
	AnalyticsUsersBySourceByDay(ctx context.Context, arg AnalyticsUsersBySourceByDayParams) ([]AnalyticsUsersBySourceByDayRow, error)
	AnalyticsUsersByStatus(ctx context.Context) ([]AnalyticsUsersByStatusRow, error)
	AnalyticsUsersCountByInterest(ctx context.Context) ([]AnalyticsUsersCountByInterestRow, error)
	// end_time is set here, not at creation: the deal gets its full run from the
	// moment it goes live, however long it waited in the queue. Also used to
	// restore a suspended post, which is why 'suspended' is accepted too.
	ApproveBuyRequest(ctx context.Context, arg ApproveBuyRequestParams) (BuyRequest, error)
	// end_time is set here, not at creation: the deal gets its full run from the
	// moment it goes live, however long it waited in the queue. Also used to
	// restore a suspended post, which is why 'suspended' is accepted too.
	ApproveSellAuction(ctx context.Context, arg ApproveSellAuctionParams) (SellAuction, error)
	AttachCarrierToOrder(ctx context.Context, arg AttachCarrierToOrderParams) (Order, error)
	AttachChargesToInvoice(ctx context.Context, arg AttachChargesToInvoiceParams) (int64, error)
	BanUser(ctx context.Context, arg BanUserParams) (int64, error)
	CancelBuyRequest(ctx context.Context, id int32) error
	CancelOrder(ctx context.Context, id int32) error
	CancelSellAuction(ctx context.Context, id int32) error
	CheckOrderExistsForBuyRequestAndSupplier(ctx context.Context, arg CheckOrderExistsForBuyRequestAndSupplierParams) (bool, error)
	CheckOrderExistsForSellAuction(ctx context.Context, sellAuctionID pgtype.Int4) (bool, error)
	ClearUserOTP(ctx context.Context, id int32) error
	CloseIssueIfOpen(ctx context.Context, publicID pgtype.UUID) (int32, error)
	CompleteOrder(ctx context.Context, id int32) error
	ConfirmOrderAsBuyer(ctx context.Context, id int32) error
	ConfirmOrderAsSeller(ctx context.Context, id int32) error
	ConsumePasswordResetCode(ctx context.Context, id int32) error
	CountActiveBuyRequests(ctx context.Context, arg CountActiveBuyRequestsParams) (int64, error)
	CountActiveSellAuctions(ctx context.Context, arg CountActiveSellAuctionsParams) (int64, error)
	CountActiveSellBidsByBidder(ctx context.Context, bidderID int32) (int64, error)
	CountActiveSellBidsByUser(ctx context.Context, bidderID int32) (int64, error)
	CountActiveSupplyOffersBySupplier(ctx context.Context, supplierID int32) (int64, error)
	CountActiveSupplyOffersByUser(ctx context.Context, supplierID int32) (int64, error)
	CountAllUsersAnyStatus(ctx context.Context) (int64, error)
	CountBuyRequestsByOwner(ctx context.Context, ownerID int32) (int64, error)
	CountCarrierRegions(ctx context.Context, userID int32) (int64, error)
	CountModeratableBuyRequests(ctx context.Context) (int64, error)
	CountModeratableSellAuctions(ctx context.Context) (int64, error)
	CountMonthlyBuyCancellations(ctx context.Context, ownerID int32) (int64, error)
	CountMonthlySellCancellations(ctx context.Context, ownerID int32) (int64, error)
	CountOpenIssuesByUser(ctx context.Context, userID int32) (int64, error)
	CountOrdersByUser(ctx context.Context, sellerID int32) (int64, error)
	CountPendingApprovalBuyRequests(ctx context.Context) (int64, error)
	CountPendingApprovalSellAuctions(ctx context.Context) (int64, error)
	CountQuotableBuyRequestsForCarrier(ctx context.Context, regionIds []int32) (int64, error)
	CountQuotableOrdersForCarrier(ctx context.Context, regionIds []int32) (int64, error)
	CountQuotableSellAuctionsForCarrier(ctx context.Context, regionIds []int32) (int64, error)
	// Throttle input: how many codes this user has requested since a cutoff.
	CountRecentPasswordResetCodes(ctx context.Context, arg CountRecentPasswordResetCodesParams) (int64, error)
	CountSearchBuyRequests(ctx context.Context, arg CountSearchBuyRequestsParams) (int64, error)
	CountSearchSellAuctions(ctx context.Context, arg CountSearchSellAuctionsParams) (int64, error)
	CountSellAuctionsByOwner(ctx context.Context, ownerID int32) (int64, error)
	CountSellBidsByAuction(ctx context.Context, auctionID int32) (int64, error)
	CountSellerBalances(ctx context.Context, overdueOnly bool) (int64, error)
	CountShippingQuotesByCarrier(ctx context.Context, carrierID int32) (int64, error)
	CountSupplyOffersByRequest(ctx context.Context, buyRequestID int32) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID int32) (int64, error)
	CountUserDocuments(ctx context.Context, userID int32) (int64, error)
	CountUsersByStatus(ctx context.Context, status string) (int64, error)
	CreateBuyRequest(ctx context.Context, arg CreateBuyRequestParams) (BuyRequest, error)
	CreateCommissionCharge(ctx context.Context, arg CreateCommissionChargeParams) (CommissionCharge, error)
	CreateCommissionInvoice(ctx context.Context, arg CreateCommissionInvoiceParams) (CommissionInvoice, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateIssueReply(ctx context.Context, arg CreateIssueReplyParams) (IssueReply, error)
	CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrderFromBuyRequest(ctx context.Context, arg CreateOrderFromBuyRequestParams) (Order, error)
	// The region ids alongside the names: carrier job feeds (#14) scope by
	// governorate id, and this table only ever denormalized the display names.
	CreateOrderFromSellAuction(ctx context.Context, arg CreateOrderFromSellAuctionParams) (Order, error)
	CreatePasswordResetCode(ctx context.Context, arg CreatePasswordResetCodeParams) (PasswordResetCode, error)
	CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (ReferralCode, error)
	CreateReferralUsage(ctx context.Context, arg CreateReferralUsageParams) error
	CreateSellAuction(ctx context.Context, arg CreateSellAuctionParams) (SellAuction, error)
	CreateSellBid(ctx context.Context, arg CreateSellBidParams) (SellBid, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	// Quotes.
	CreateShippingQuote(ctx context.Context, arg CreateShippingQuoteParams) (ShippingQuote, error)
	CreateSupplyOffer(ctx context.Context, arg CreateSupplyOfferParams) (SupplyOffer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserDocument(ctx context.Context, arg CreateUserDocumentParams) (UserDocument, error)
	CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error)
	DeactivateAllUserSubscriptions(ctx context.Context, userID int32) error
	DeactivateDeviceToken(ctx context.Context, token string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldNotifications(ctx context.Context, arg DeleteOldNotificationsParams) error
	DeleteUserInterests(ctx context.Context, userID int32) error
	EnsureSeedUser(ctx context.Context, arg EnsureSeedUserParams) (User, error)
	GetAcceptedQuoteForOrder(ctx context.Context, orderID pgtype.Int4) (GetAcceptedQuoteForOrderRow, error)
	// Post-stage acceptance happens before an order exists, so when the deal closes
	// the winning carrier has to be carried onto it — otherwise the order looks
	// unshipped and the carrier feed would offer it again.
	GetAcceptedQuoteForPost(ctx context.Context, arg GetAcceptedQuoteForPostParams) (ShippingQuote, error)
	GetActiveDeviceTokensByUser(ctx context.Context, userID int32) ([]DeviceToken, error)
	GetActiveUsersByInterest(ctx context.Context, arg GetActiveUsersByInterestParams) ([]int32, error)
	// Admin: lists ALL subscriptions for a user, active or not.
	GetAllUserSubscriptions(ctx context.Context, userID int32) ([]GetAllUserSubscriptionsRow, error)
	GetAppSetting(ctx context.Context, key string) (AppSetting, error)
	GetBuyRequestByID(ctx context.Context, id int32) (BuyRequest, error)
	GetBuyRequestByPublicID(ctx context.Context, publicID pgtype.UUID) (BuyRequest, error)
	GetBuyRequestByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (BuyRequest, error)
	GetCarrierProfile(ctx context.Context, userID int32) (CarrierProfile, error)
	GetCommissionTotals(ctx context.Context) (GetCommissionTotalsRow, error)
	GetExpiredActiveBuyRequests(ctx context.Context) ([]BuyRequest, error)
	GetExpiredActiveSellAuctions(ctx context.Context) ([]SellAuction, error)
	GetExpiredPendingSelectionBuyRequests(ctx context.Context, windowHours int32) ([]BuyRequest, error)
	GetExpiredPendingSelectionSellAuctions(ctx context.Context, windowHours int32) ([]SellAuction, error)
	GetInterestByID(ctx context.Context, id int32) (Interest, error)
	GetInvoiceByPublicID(ctx context.Context, publicID pgtype.UUID) (CommissionInvoice, error)
	GetIssueAdminDetail(ctx context.Context, publicID pgtype.UUID) (GetIssueAdminDetailRow, error)
	GetIssueByID(ctx context.Context, id int32) (Issue, error)
	GetIssueByPublicID(ctx context.Context, publicID pgtype.UUID) (Issue, error)
	GetJobByID(ctx context.Context, id int32) (Job, error)
	GetJobByKey(ctx context.Context, key string) (Job, error)
	// The user's most recent code that is still usable: not consumed, not expired,
	// and not yet burned through its attempt allowance.
	GetLivePasswordResetCode(ctx context.Context, arg GetLivePasswordResetCodeParams) (PasswordResetCode, error)
	GetLosingBidderIDsForAuction(ctx context.Context, arg GetLosingBidderIDsForAuctionParams) ([]int32, error)
	GetMissingDocumentTypes(ctx context.Context, userID int32) ([]interface{}, error)
	GetMotivatableActiveBuyRequests(ctx context.Context) ([]BuyRequest, error)
	GetMotivatableActiveSellAuctions(ctx context.Context) ([]SellAuction, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetOrderByPublicID(ctx context.Context, publicID pgtype.UUID) (Order, error)
	GetOrdersPendingConfirmation(ctx context.Context) ([]Order, error)
	GetReferralCodeByCode(ctx context.Context, code string) (ReferralCode, error)
	GetReferralCodeByUser(ctx context.Context, userID int32) (ReferralCode, error)
	GetRegionByID(ctx context.Context, id int32) (Region, error)
	GetSellAuctionByID(ctx context.Context, id int32) (SellAuction, error)
	GetSellAuctionByPublicID(ctx context.Context, publicID pgtype.UUID) (SellAuction, error)
	GetSellAuctionByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (SellAuction, error)
	GetSellBidByAuctionAndBidder(ctx context.Context, arg GetSellBidByAuctionAndBidderParams) (SellBid, error)
	GetSellBidByID(ctx context.Context, id int32) (SellBid, error)
	GetSellBidByPublicID(ctx context.Context, publicID pgtype.UUID) (SellBid, error)
	// Seller-facing.
	GetSellerCommissionSummary(ctx context.Context, sellerID int32) (GetSellerCommissionSummaryRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error)
	GetShippingQuoteByPublicID(ctx context.Context, publicID pgtype.UUID) (ShippingQuote, error)
	GetShippingQuoteByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (ShippingQuote, error)
	// Fires once, during the final hour before the selection deadline.
	GetSoonExpiringSelectionBuyRequests(ctx context.Context, windowHours int32) ([]BuyRequest, error)
	// Fires once, during the final hour before the selection deadline.
	GetSoonExpiringSelectionSellAuctions(ctx context.Context, windowHours int32) ([]SellAuction, error)
	GetSubscriptionTiers(ctx context.Context) ([]SubscriptionTier, error)
	GetSupplyOfferByID(ctx context.Context, id int32) (SupplyOffer, error)
	GetSupplyOfferByPublicID(ctx context.Context, publicID pgtype.UUID) (SupplyOffer, error)
	GetSupplyOfferByRequestAndSupplier(ctx context.Context, arg GetSupplyOfferByRequestAndSupplierParams) (SupplyOffer, error)
	GetUnacceptedSupplierIDsForRequest(ctx context.Context, buyRequestID int32) ([]int32, error)
	GetUnnotifiedActiveBuyRequests(ctx context.Context) ([]BuyRequest, error)
	GetUnnotifiedActiveSellAuctions(ctx context.Context) ([]SellAuction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error)
	GetUserDocuments(ctx context.Context, userID int32) ([]UserDocument, error)
	GetUserInterestIDs(ctx context.Context, userID int32) ([]int32, error)
	GetUserInterests(ctx context.Context, userID int32) ([]GetUserInterestsRow, error)
	GetUserStatusByID(ctx context.Context, id int32) (GetUserStatusByIDRow, error)
	GetUserStatusData(ctx context.Context, id int32) (GetUserStatusDataRow, error)
	GetUserSubscriptionByID(ctx context.Context, id int32) (UserSubscription, error)
	GetUserSubscriptionByUserAndTier(ctx context.Context, arg GetUserSubscriptionByUserAndTierParams) (UserSubscription, error)
	GetUserSubscriptionStatus(ctx context.Context, userID int32) (GetUserSubscriptionStatusRow, error)
	GetUserSubscriptions(ctx context.Context, userID int32) ([]GetUserSubscriptionsRow, error)
	GetUserWithRegion(ctx context.Context, id int32) (GetUserWithRegionRow, error)
	GetUserWithRegionAndJob(ctx context.Context, id int32) (GetUserWithRegionAndJobRow, error)
	GetUserWithRegionAndJobByPublicID(ctx context.Context, publicID pgtype.UUID) (GetUserWithRegionAndJobByPublicIDRow, error)
	// Get user info with their highest active subscription in one query
	GetUserWithSubscription(ctx context.Context, id int32) (GetUserWithSubscriptionRow, error)
	HasActiveSubscription(ctx context.Context, userID int32) (bool, error)
	IncrementAuctionCount(ctx context.Context, id int32) error
	IncrementBidCount(ctx context.Context, id int32) error
	IncrementBuyRequestAcceptedOfferCount(ctx context.Context, id int32) error
	IncrementBuyRequestOfferCount(ctx context.Context, id int32) error
	IncrementOfferCount(ctx context.Context, id int32) error
	IncrementPasswordResetAttempts(ctx context.Context, id int32) error
	IncrementReferralUsage(ctx context.Context, id int32) error
	IncrementRequestCount(ctx context.Context, id int32) error
	IncrementSellAuctionBidCount(ctx context.Context, id int32) error
	// After a successful reset, retire every other outstanding code for the user.
	InvalidatePasswordResetCodes(ctx context.Context, userID int32) error
	InvalidateSession(ctx context.Context, id int32) error
	InvalidateUserSessions(ctx context.Context, userID int32) error
	LazyRestoreExpiredSuspension(ctx context.Context, id int32) (int64, error)
	ListAcceptedOffersByRequest(ctx context.Context, buyRequestID int32) ([]SupplyOffer, error)
	ListActiveBuyRequests(ctx context.Context, arg ListActiveBuyRequestsParams) ([]BuyRequest, error)
	ListActiveSellAuctions(ctx context.Context, arg ListActiveSellAuctionsParams) ([]SellAuction, error)
	ListAllIssues(ctx context.Context, arg ListAllIssuesParams) ([]Issue, error)
	ListAllUsersAnyStatus(ctx context.Context, arg ListAllUsersAnyStatusParams) ([]User, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	ListBuyRequestsByOwner(ctx context.Context, arg ListBuyRequestsByOwnerParams) ([]BuyRequest, error)
	ListCarrierRegionIDs(ctx context.Context, userID int32) ([]int32, error)
	ListCarrierRegions(ctx context.Context, userID int32) ([]ListCarrierRegionsRow, error)
	ListChargesByInvoice(ctx context.Context, invoiceID pgtype.Int4) ([]CommissionCharge, error)
	ListChargesBySeller(ctx context.Context, arg ListChargesBySellerParams) ([]CommissionCharge, error)
	// Platform commission (#13). See migration 045 for the shape and the reasoning.
	// Accrual. Charges are derived from orders rather than written by the
	// confirmation handler: ConfirmOrderAsSeller/AsBuyer are conditional updates
	// declared :exec, so the service cannot tell whether the transition actually
	// applied, and accruing there would bill orders that never completed. Running
	// this every minute is idempotent because commission_charges.order_id is UNIQUE.
	ListCompletedOrdersWithoutCharge(ctx context.Context, arg ListCompletedOrdersWithoutChargeParams) ([]ListCompletedOrdersWithoutChargeRow, error)
	ListInterests(ctx context.Context) ([]Interest, error)
	ListInvoicesBySeller(ctx context.Context, arg ListInvoicesBySellerParams) ([]CommissionInvoice, error)
	ListInvoicesForAdmin(ctx context.Context, arg ListInvoicesForAdminParams) ([]ListInvoicesForAdminRow, error)
	ListIssueReplies(ctx context.Context, issueID int32) ([]IssueReply, error)
	ListIssuesByUser(ctx context.Context, arg ListIssuesByUserParams) ([]Issue, error)
	ListJobs(ctx context.Context) ([]Job, error)
	ListLoginHistoryByUser(ctx context.Context, arg ListLoginHistoryByUserParams) ([]LoginHistory, error)
	// Live and suspended posts, for the admin's "published" tab.
	ListModeratableBuyRequests(ctx context.Context, arg ListModeratableBuyRequestsParams) ([]BuyRequest, error)
	// Live and suspended posts, for the admin's "published" tab.
	ListModeratableSellAuctions(ctx context.Context, arg ListModeratableSellAuctionsParams) ([]SellAuction, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListOrdersByBuyRequest(ctx context.Context, buyRequestID pgtype.Int4) ([]Order, error)
	ListOrdersBySellAuction(ctx context.Context, sellAuctionID pgtype.Int4) ([]Order, error)
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	ListPendingApprovalBuyRequests(ctx context.Context, arg ListPendingApprovalBuyRequestsParams) ([]BuyRequest, error)
	ListPendingApprovalSellAuctions(ctx context.Context, arg ListPendingApprovalSellAuctionsParams) ([]SellAuction, error)
	ListQuotableBuyRequestsForCarrier(ctx context.Context, arg ListQuotableBuyRequestsForCarrierParams) ([]ListQuotableBuyRequestsForCarrierRow, error)
	// Carrier-facing job feeds.
	//
	// Every one of these deliberately omits the money: final_price, unit_price and
	// total_price never leave the database on a carrier request. Transport is priced
	// on weight, distance and goods type, so a carrier has no need for the value of
	// the cargo — and handing a third party the market's pricing is not recoverable
	// once done.
	// Deals that still need moving: both parties have a stake, no carrier chosen
	// yet, and at least one end sits in a governorate this carrier serves.
	ListQuotableOrdersForCarrier(ctx context.Context, arg ListQuotableOrdersForCarrierParams) ([]ListQuotableOrdersForCarrierRow, error)
	// Post-stage mode. The destination does not exist yet — no winner means no
	// buyer — so a quote here is indicative on the origin governorate alone.
	ListQuotableSellAuctionsForCarrier(ctx context.Context, arg ListQuotableSellAuctionsForCarrierParams) ([]ListQuotableSellAuctionsForCarrierRow, error)
	ListRegions(ctx context.Context) ([]Region, error)
	ListSellAuctionsByOwner(ctx context.Context, arg ListSellAuctionsByOwnerParams) ([]SellAuction, error)
	ListSellBidsByAuction(ctx context.Context, auctionID int32) ([]ListSellBidsByAuctionRow, error)
	ListSellBidsByBidder(ctx context.Context, arg ListSellBidsByBidderParams) ([]ListSellBidsByBidderRow, error)
	// Admin. The worklist is one row per seller who owes something, overdue first.
	ListSellerBalances(ctx context.Context, arg ListSellerBalancesParams) ([]ListSellerBalancesRow, error)
	// Invoicing.
	ListSellersWithUninvoicedCharges(ctx context.Context, arg ListSellersWithUninvoicedChargesParams) ([]ListSellersWithUninvoicedChargesRow, error)
	// The carrier's own list, so their own prices are theirs to see. The job's title
	// comes from whichever target the quote points at.
	ListShippingQuotesByCarrier(ctx context.Context, arg ListShippingQuotesByCarrierParams) ([]ListShippingQuotesByCarrierRow, error)
	ListShippingQuotesForBuyRequest(ctx context.Context, buyRequestID pgtype.Int4) ([]ListShippingQuotesForBuyRequestRow, error)
	// Merchant-facing.
	ListShippingQuotesForOrder(ctx context.Context, orderID pgtype.Int4) ([]ListShippingQuotesForOrderRow, error)
	ListShippingQuotesForSellAuction(ctx context.Context, sellAuctionID pgtype.Int4) ([]ListShippingQuotesForSellAuctionRow, error)
	ListSupplyOffersByRequest(ctx context.Context, buyRequestID int32) ([]ListSupplyOffersByRequestRow, error)
	ListSupplyOffersBySupplier(ctx context.Context, arg ListSupplyOffersBySupplierParams) ([]ListSupplyOffersBySupplierRow, error)
	ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error)
	MarkAllNotificationsRead(ctx context.Context, userID int32) error
	MarkBuyRequestMotivated(ctx context.Context, id int32) error
	MarkBuyRequestNotified(ctx context.Context, id int32) error
	MarkBuyRequestSelectionWarned(ctx context.Context, id int32) error
	// Recording a payment is admin-only and one-way: an invoice is unpaid, paid or
	// waived. The status guard makes a double-submit a no-op rather than a second
	// payment record.
	MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error)
	MarkNotChosenSellBids(ctx context.Context, auctionID int32) error
	MarkNotChosenSupplyOffers(ctx context.Context, buyRequestID int32) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	// Revocation marker — tokens issued before this are rejected downstream.
	MarkPasswordChanged(ctx context.Context, id int32) error
	MarkSellAuctionMotivated(ctx context.Context, id int32) error
	MarkSellAuctionNotified(ctx context.Context, id int32) error
	MarkSellAuctionSelectionWarned(ctx context.Context, id int32) error
	ReactivateUserSubscription(ctx context.Context, arg ReactivateUserSubscriptionParams) (UserSubscription, error)
	RejectBuyRequest(ctx context.Context, arg RejectBuyRequestParams) (BuyRequest, error)
	RejectSellAuction(ctx context.Context, arg RejectSellAuctionParams) (SellAuction, error)
	RejectShippingQuote(ctx context.Context, id int32) (ShippingQuote, error)
	// Accepting one answers the rest. Returns the losers so each can be told, which
	// is the difference between a carrier knowing where it stands and being ignored.
	RejectSiblingShippingQuotes(ctx context.Context, arg RejectSiblingShippingQuotesParams) ([]RejectSiblingShippingQuotesRow, error)
	// Coverage is replaced wholesale rather than diffed: the edit form always sends
	// the complete set, and a partial update would leave stale governorates behind.
	ReplaceCarrierRegions(ctx context.Context, userID int32) error
	ResetMonthlyCounts(ctx context.Context) error
	RevertBuyRequestToPendingSelection(ctx context.Context, id int32) error
	RevertSellAuctionToPendingSelection(ctx context.Context, id int32) error
	SearchBuyRequests(ctx context.Context, arg SearchBuyRequestsParams) ([]BuyRequest, error)
	SearchSellAuctions(ctx context.Context, arg SearchSellAuctionsParams) ([]SellAuction, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SearchUsersCount(ctx context.Context, arg SearchUsersCountParams) (int64, error)
	SelectSellBid(ctx context.Context, id int32) error
	SelectSellWinner(ctx context.Context, arg SelectSellWinnerParams) error
	// Whether a supply-side merchant is willing to sell to retailers (#7). Kept as
	// its own statement rather than folded into UpdateUserProfileWithNames: that one
	// is called with a full profile payload, and a bool absent from such a payload
	// would read as false and silently opt the merchant out.
	SetSuppliesToRetail(ctx context.Context, arg SetSuppliesToRetailParams) error
	SumAcceptedQuantityByRequest(ctx context.Context, buyRequestID int32) (pgtype.Numeric, error)
	SuspendBuyRequest(ctx context.Context, arg SuspendBuyRequestParams) (BuyRequest, error)
	SuspendSellAuction(ctx context.Context, arg SuspendSellAuctionParams) (SellAuction, error)
	SuspendUser(ctx context.Context, arg SuspendUserParams) (int64, error)
	UnbanUser(ctx context.Context, arg UnbanUserParams) (int64, error)
	UnsuspendUser(ctx context.Context, arg UnsuspendUserParams) (int64, error)
	UpdateBuyRequestFulfilledQuantity(ctx context.Context, arg UpdateBuyRequestFulfilledQuantityParams) error
	UpdateBuyRequestStatus(ctx context.Context, arg UpdateBuyRequestStatusParams) error
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error
	UpdateSellAuctionStatus(ctx context.Context, arg UpdateSellAuctionStatusParams) error
	UpdateSessionLastUsed(ctx context.Context, id int32) error
	UpdateUserCachedNames(ctx context.Context, arg UpdateUserCachedNamesParams) error
	UpdateUserFCMToken(ctx context.Context, arg UpdateUserFCMTokenParams) error
	UpdateUserInterestsCount(ctx context.Context, arg UpdateUserInterestsCountParams) error
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
	UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserProfileWithNames(ctx context.Context, arg UpdateUserProfileWithNamesParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserStatusWithReason(ctx context.Context, arg UpdateUserStatusWithReasonParams) error
	// NOTE: clearing expires_at to NULL is not supported by COALESCE(narg, expires_at).
	//       For perpetual subscriptions, send a far-future date from the frontend.
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error)
	// Keys are whitelisted in the handler; this is not a general-purpose store.
	UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error)
	// Registration and profile edits share one path: a carrier always has exactly
	// one profile row, so there is nothing to distinguish create from update.
	UpsertCarrierProfile(ctx context.Context, arg UpsertCarrierProfileParams) (CarrierProfile, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error
	WaiveInvoice(ctx context.Context, arg WaiveInvoiceParams) (int64, error)
	// Only a quote nobody has answered yet: withdrawing an accepted one would strip
	// a carrier off a deal the merchant has already committed to.
	WithdrawShippingQuote(ctx context.Context, id int32) (ShippingQuote, error)
}

var _ Querier = (*Queries)(nil)
