// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: referral_codes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReferralCode = `-- name: CreateReferralCode :one
INSERT INTO referral_codes (user_id, code) VALUES ($1, $2) RETURNING id, user_id, code, discount_percent, usage_count, max_uses, is_active, created_at
`

type CreateReferralCodeParams struct {
	UserID int32  `json:"user_id"`
	Code   string `json:"code"`
}

func (q *Queries) CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, createReferralCode, arg.UserID, arg.Code)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.DiscountPercent,
		&i.UsageCount,
		&i.MaxUses,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createReferralUsage = `-- name: CreateReferralUsage :exec
INSERT INTO referral_usages (referral_code_id, referred_user_id, discount_applied)
VALUES ($1, $2, $3)
`

type CreateReferralUsageParams struct {
	ReferralCodeID  int32          `json:"referral_code_id"`
	ReferredUserID  int32          `json:"referred_user_id"`
	DiscountApplied pgtype.Numeric `json:"discount_applied"`
}

func (q *Queries) CreateReferralUsage(ctx context.Context, arg CreateReferralUsageParams) error {
	_, err := q.db.Exec(ctx, createReferralUsage, arg.ReferralCodeID, arg.ReferredUserID, arg.DiscountApplied)
	return err
}

const getReferralCodeByCode = `-- name: GetReferralCodeByCode :one
SELECT id, user_id, code, discount_percent, usage_count, max_uses, is_active, created_at FROM referral_codes WHERE code = $1 AND is_active = TRUE
`

func (q *Queries) GetReferralCodeByCode(ctx context.Context, code string) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeByCode, code)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.DiscountPercent,
		&i.UsageCount,
		&i.MaxUses,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralCodeByUser = `-- name: GetReferralCodeByUser :one
SELECT id, user_id, code, discount_percent, usage_count, max_uses, is_active, created_at FROM referral_codes WHERE user_id = $1
`

func (q *Queries) GetReferralCodeByUser(ctx context.Context, userID int32) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeByUser, userID)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.DiscountPercent,
		&i.UsageCount,
		&i.MaxUses,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const incrementReferralUsage = `-- name: IncrementReferralUsage :exec
UPDATE referral_codes SET usage_count = usage_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReferralUsage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementReferralUsage, id)
	return err
}
