// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: regions.sql

package sqlc

import (
	"context"
)

const getRegionByID = `-- name: GetRegionByID :one
SELECT id, name_ar, name_en, is_active, created_at FROM regions WHERE id = $1
`

func (q *Queries) GetRegionByID(ctx context.Context, id int32) (Region, error) {
	row := q.db.QueryRow(ctx, getRegionByID, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.NameAr,
		&i.NameEn,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT id, name_ar, name_en, is_active, created_at FROM regions WHERE is_active = TRUE ORDER BY name_ar
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.NameAr,
			&i.NameEn,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
