// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSeedNotification = `-- name: ClaimSeedNotification :one
INSERT INTO seed_notification_quota AS q (user_id, day, sent_today, last_sent_at)
VALUES ($1, $2, 1, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    sent_today   = CASE WHEN q.day = EXCLUDED.day THEN q.sent_today + 1 ELSE 1 END,
    day          = EXCLUDED.day,
    last_sent_at = NOW()
WHERE q.day <> EXCLUDED.day
   OR (q.sent_today < $3::int
       AND q.last_sent_at <= NOW() - make_interval(mins => $4::int))
RETURNING q.user_id
`

type ClaimSeedNotificationParams struct {
	UserID        int32       `json:"user_id"`
	Day           pgtype.Date `json:"day"`
	DailyMax      int32       `json:"daily_max"`
	MinGapMinutes int32       `json:"min_gap_minutes"`
}

// Takes one of a member's demo-notification slots for today, if one is free:
// fewer than daily_max sent today, and the last one at least min_gap_minutes
// ago. Returns the member's id when the slot was taken, no row when it was not.
// A new Cairo day starts the count again.
func (q *Queries) ClaimSeedNotification(ctx context.Context, arg ClaimSeedNotificationParams) (int32, error) {
	row := q.db.QueryRow(ctx, claimSeedNotification,
		arg.UserID,
		arg.Day,
		arg.DailyMax,
		arg.MinGapMinutes,
	)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
