// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sell_auctions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveSellAuction = `-- name: ApproveSellAuction :one
UPDATE sell_auctions
SET status = 'active',
    end_time = NOW() + make_interval(hours => $1::int),
    moderation_reason = NULL,
    moderated_by_admin_id = $2::int,
    moderated_at = NOW(),
    updated_at = NOW()
WHERE public_id = $3 AND status IN ('pending_approval','suspended')
RETURNING id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at
`

type ApproveSellAuctionParams struct {
	DurationHours int32       `json:"duration_hours"`
	AdminID       int32       `json:"admin_id"`
	PublicID      pgtype.UUID `json:"public_id"`
}

// end_time is set here, not at creation: the deal gets its full run from the
// moment it goes live, however long it waited in the queue. Also used to
// restore a suspended post, which is why 'suspended' is accepted too.
func (q *Queries) ApproveSellAuction(ctx context.Context, arg ApproveSellAuctionParams) (SellAuction, error) {
	row := q.db.QueryRow(ctx, approveSellAuction, arg.DurationHours, arg.AdminID, arg.PublicID)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const cancelSellAuction = `-- name: CancelSellAuction :exec
UPDATE sell_auctions SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND status IN ('active','pending_approval')
`

func (q *Queries) CancelSellAuction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelSellAuction, id)
	return err
}

const countActiveSellAuctions = `-- name: CountActiveSellAuctions :one
SELECT COUNT(*) FROM sell_auctions
WHERE status = 'active' AND end_time > NOW()
  AND ($1::int IS NULL OR owner_id != $1::int)
  AND ($2::int[] IS NULL OR id NOT IN (
    SELECT sb.auction_id FROM sell_bids sb WHERE sb.bidder_id = $3::int
  ))
  AND ($4::int = 0 OR region_id = $4::int)
  AND ($5::text[] IS NULL OR cardinality($5::text[]) = 0 OR EXISTS (
    SELECT 1 FROM users ow WHERE ow.id = owner_id AND ow.job_key = ANY($5::text[])))
`

type CountActiveSellAuctionsParams struct {
	ExcludeOwnerID        int32    `json:"exclude_owner_id"`
	ExcludeBiddedAuctions []int32  `json:"exclude_bidded_auctions"`
	UserID                int32    `json:"user_id"`
	FilterRegionID        int32    `json:"filter_region_id"`
	OwnerJobKeys          []string `json:"owner_job_keys"`
}

func (q *Queries) CountActiveSellAuctions(ctx context.Context, arg CountActiveSellAuctionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSellAuctions,
		arg.ExcludeOwnerID,
		arg.ExcludeBiddedAuctions,
		arg.UserID,
		arg.FilterRegionID,
		arg.OwnerJobKeys,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModeratableSellAuctions = `-- name: CountModeratableSellAuctions :one
SELECT COUNT(*) FROM sell_auctions WHERE status IN ('active','suspended')
`

func (q *Queries) CountModeratableSellAuctions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countModeratableSellAuctions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonthlySellCancellations = `-- name: CountMonthlySellCancellations :one
SELECT COUNT(*) FROM sell_auctions
WHERE owner_id = $1 AND status = 'cancelled'
  AND updated_at >= date_trunc('month', NOW())
`

func (q *Queries) CountMonthlySellCancellations(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countMonthlySellCancellations, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingApprovalSellAuctions = `-- name: CountPendingApprovalSellAuctions :one
SELECT COUNT(*) FROM sell_auctions WHERE status = 'pending_approval'
`

func (q *Queries) CountPendingApprovalSellAuctions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApprovalSellAuctions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchSellAuctions = `-- name: CountSearchSellAuctions :one
SELECT COUNT(*) FROM sell_auctions
WHERE status = 'active' AND end_time > NOW()
  AND title ILIKE '%' || $1::text || '%'
  AND ($2::int IS NULL OR owner_id != $2::int)
  AND ($3::int[] IS NULL OR id NOT IN (
    SELECT sb.auction_id FROM sell_bids sb WHERE sb.bidder_id = $4::int
  ))
  AND ($5::int = 0 OR region_id = $5::int)
  AND ($6::text[] IS NULL OR cardinality($6::text[]) = 0 OR EXISTS (
    SELECT 1 FROM users ow WHERE ow.id = owner_id AND ow.job_key = ANY($6::text[])))
`

type CountSearchSellAuctionsParams struct {
	SearchTerm            string   `json:"search_term"`
	ExcludeOwnerID        int32    `json:"exclude_owner_id"`
	ExcludeBiddedAuctions []int32  `json:"exclude_bidded_auctions"`
	UserID                int32    `json:"user_id"`
	FilterRegionID        int32    `json:"filter_region_id"`
	OwnerJobKeys          []string `json:"owner_job_keys"`
}

func (q *Queries) CountSearchSellAuctions(ctx context.Context, arg CountSearchSellAuctionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSellAuctions,
		arg.SearchTerm,
		arg.ExcludeOwnerID,
		arg.ExcludeBiddedAuctions,
		arg.UserID,
		arg.FilterRegionID,
		arg.OwnerJobKeys,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSellAuctionsByOwner = `-- name: CountSellAuctionsByOwner :one
SELECT COUNT(*) FROM sell_auctions WHERE owner_id = $1
`

func (q *Queries) CountSellAuctionsByOwner(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSellAuctionsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSellAuction = `-- name: CreateSellAuction :one
INSERT INTO sell_auctions (owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, end_time, owner_name, region_name, interest_name, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at
`

type CreateSellAuctionParams struct {
	OwnerID       int32              `json:"owner_id"`
	RegionID      int32              `json:"region_id"`
	InterestID    int32              `json:"interest_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	ImageUrl      string             `json:"image_url"`
	Unit          string             `json:"unit"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	UnitPrice     pgtype.Numeric     `json:"unit_price"`
	BuyAllFromOne bool               `json:"buy_all_from_one"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	OwnerName     string             `json:"owner_name"`
	RegionName    string             `json:"region_name"`
	InterestName  string             `json:"interest_name"`
	Status        string             `json:"status"`
}

func (q *Queries) CreateSellAuction(ctx context.Context, arg CreateSellAuctionParams) (SellAuction, error) {
	row := q.db.QueryRow(ctx, createSellAuction,
		arg.OwnerID,
		arg.RegionID,
		arg.InterestID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Unit,
		arg.Quantity,
		arg.UnitPrice,
		arg.BuyAllFromOne,
		arg.EndTime,
		arg.OwnerName,
		arg.RegionName,
		arg.InterestName,
		arg.Status,
	)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const getExpiredActiveSellAuctions = `-- name: GetExpiredActiveSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions WHERE status = 'active' AND end_time <= NOW()
`

func (q *Queries) GetExpiredActiveSellAuctions(ctx context.Context) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, getExpiredActiveSellAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPendingSelectionSellAuctions = `-- name: GetExpiredPendingSelectionSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions
WHERE status = 'pending_selection'
  AND end_time + ($1::int * INTERVAL '1 hour') <= NOW()
`

func (q *Queries) GetExpiredPendingSelectionSellAuctions(ctx context.Context, windowHours int32) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, getExpiredPendingSelectionSellAuctions, windowHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMotivatableActiveSellAuctions = `-- name: GetMotivatableActiveSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions
WHERE status = 'active'
  AND end_time > NOW()
  AND end_time <= NOW() + INTERVAL '30 minutes'
  AND (last_motivation_sent_at IS NULL OR last_motivation_sent_at < NOW() - INTERVAL '20 minutes')
`

func (q *Queries) GetMotivatableActiveSellAuctions(ctx context.Context) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, getMotivatableActiveSellAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellAuctionByID = `-- name: GetSellAuctionByID :one
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions WHERE id = $1
`

func (q *Queries) GetSellAuctionByID(ctx context.Context, id int32) (SellAuction, error) {
	row := q.db.QueryRow(ctx, getSellAuctionByID, id)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const getSellAuctionByPublicID = `-- name: GetSellAuctionByPublicID :one
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions WHERE public_id = $1
`

func (q *Queries) GetSellAuctionByPublicID(ctx context.Context, publicID pgtype.UUID) (SellAuction, error) {
	row := q.db.QueryRow(ctx, getSellAuctionByPublicID, publicID)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const getSellAuctionByPublicIDForUpdate = `-- name: GetSellAuctionByPublicIDForUpdate :one
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions WHERE public_id = $1 FOR UPDATE
`

func (q *Queries) GetSellAuctionByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (SellAuction, error) {
	row := q.db.QueryRow(ctx, getSellAuctionByPublicIDForUpdate, publicID)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const getSoonExpiringSelectionSellAuctions = `-- name: GetSoonExpiringSelectionSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions
WHERE status = 'pending_selection'
  AND selection_warning_sent_at IS NULL
  AND NOW() >= end_time + ($1::int * INTERVAL '1 hour') - INTERVAL '1 hour'
  AND NOW() <  end_time + ($1::int * INTERVAL '1 hour')
`

// Fires once, during the final hour before the selection deadline.
func (q *Queries) GetSoonExpiringSelectionSellAuctions(ctx context.Context, windowHours int32) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, getSoonExpiringSelectionSellAuctions, windowHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnnotifiedActiveSellAuctions = `-- name: GetUnnotifiedActiveSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions
WHERE status = 'active' AND notified_at IS NULL
`

func (q *Queries) GetUnnotifiedActiveSellAuctions(ctx context.Context) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, getUnnotifiedActiveSellAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementSellAuctionBidCount = `-- name: IncrementSellAuctionBidCount :exec
UPDATE sell_auctions SET bid_count = bid_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementSellAuctionBidCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementSellAuctionBidCount, id)
	return err
}

const listActiveSellAuctions = `-- name: ListActiveSellAuctions :many
SELECT sa.id, sa.public_id, sa.owner_id, sa.region_id, sa.interest_id, sa.title, sa.description, sa.image_url, sa.unit, sa.quantity, sa.unit_price, sa.buy_all_from_one, sa.bid_count, sa.end_time, sa.status, sa.selected_bid_id, sa.winner_id, sa.final_price, sa.created_at, sa.updated_at, sa.owner_name, sa.region_name, sa.interest_name, sa.notified_at, sa.last_motivation_sent_at, sa.selection_warning_sent_at, sa.moderation_reason, sa.moderated_by_admin_id, sa.moderated_at FROM sell_auctions sa
WHERE sa.status = 'active' AND sa.end_time > NOW()
  AND ($3::int IS NULL OR sa.owner_id != $3::int)
  AND ($4::int[] IS NULL OR sa.id NOT IN (
    SELECT sb.auction_id FROM sell_bids sb WHERE sb.bidder_id = $5::int
  ))
  AND ($6::int = 0 OR sa.region_id = $6::int)
  AND ($7::text[] IS NULL OR cardinality($7::text[]) = 0 OR EXISTS (
    SELECT 1 FROM users ow WHERE ow.id = sa.owner_id AND ow.job_key = ANY($7::text[])))
ORDER BY
  CASE WHEN sa.interest_id = ANY($8::integer[]) THEN 0 ELSE 1 END,
  sa.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveSellAuctionsParams struct {
	Limit                 int32    `json:"limit"`
	Offset                int32    `json:"offset"`
	ExcludeOwnerID        int32    `json:"exclude_owner_id"`
	ExcludeBiddedAuctions []int32  `json:"exclude_bidded_auctions"`
	UserID                int32    `json:"user_id"`
	FilterRegionID        int32    `json:"filter_region_id"`
	OwnerJobKeys          []string `json:"owner_job_keys"`
	UserInterestIds       []int32  `json:"user_interest_ids"`
}

func (q *Queries) ListActiveSellAuctions(ctx context.Context, arg ListActiveSellAuctionsParams) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, listActiveSellAuctions,
		arg.Limit,
		arg.Offset,
		arg.ExcludeOwnerID,
		arg.ExcludeBiddedAuctions,
		arg.UserID,
		arg.FilterRegionID,
		arg.OwnerJobKeys,
		arg.UserInterestIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModeratableSellAuctions = `-- name: ListModeratableSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions
WHERE status IN ('active','suspended')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListModeratableSellAuctionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Live and suspended posts, for the admin's "published" tab.
func (q *Queries) ListModeratableSellAuctions(ctx context.Context, arg ListModeratableSellAuctionsParams) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, listModeratableSellAuctions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalSellAuctions = `-- name: ListPendingApprovalSellAuctions :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions
WHERE status = 'pending_approval'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingApprovalSellAuctionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingApprovalSellAuctions(ctx context.Context, arg ListPendingApprovalSellAuctionsParams) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalSellAuctions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellAuctionsByOwner = `-- name: ListSellAuctionsByOwner :many
SELECT id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at FROM sell_auctions WHERE owner_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSellAuctionsByOwnerParams struct {
	OwnerID int32 `json:"owner_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListSellAuctionsByOwner(ctx context.Context, arg ListSellAuctionsByOwnerParams) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, listSellAuctionsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSellAuctionMotivated = `-- name: MarkSellAuctionMotivated :exec
UPDATE sell_auctions SET last_motivation_sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkSellAuctionMotivated(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markSellAuctionMotivated, id)
	return err
}

const markSellAuctionNotified = `-- name: MarkSellAuctionNotified :exec
UPDATE sell_auctions SET notified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkSellAuctionNotified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markSellAuctionNotified, id)
	return err
}

const markSellAuctionSelectionWarned = `-- name: MarkSellAuctionSelectionWarned :exec
UPDATE sell_auctions SET selection_warning_sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkSellAuctionSelectionWarned(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markSellAuctionSelectionWarned, id)
	return err
}

const rejectSellAuction = `-- name: RejectSellAuction :one
UPDATE sell_auctions
SET status = 'rejected',
    moderation_reason = $1::text,
    moderated_by_admin_id = $2::int,
    moderated_at = NOW(),
    updated_at = NOW()
WHERE public_id = $3 AND status = 'pending_approval'
RETURNING id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at
`

type RejectSellAuctionParams struct {
	Reason   string      `json:"reason"`
	AdminID  int32       `json:"admin_id"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) RejectSellAuction(ctx context.Context, arg RejectSellAuctionParams) (SellAuction, error) {
	row := q.db.QueryRow(ctx, rejectSellAuction, arg.Reason, arg.AdminID, arg.PublicID)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const revertSellAuctionToPendingSelection = `-- name: RevertSellAuctionToPendingSelection :exec
UPDATE sell_auctions 
SET status = 'pending_selection', selected_bid_id = NULL, winner_id = NULL, final_price = NULL, updated_at = NOW()
WHERE id = $1 AND status = 'winner_selected'
`

func (q *Queries) RevertSellAuctionToPendingSelection(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revertSellAuctionToPendingSelection, id)
	return err
}

const searchSellAuctions = `-- name: SearchSellAuctions :many
SELECT sa.id, sa.public_id, sa.owner_id, sa.region_id, sa.interest_id, sa.title, sa.description, sa.image_url, sa.unit, sa.quantity, sa.unit_price, sa.buy_all_from_one, sa.bid_count, sa.end_time, sa.status, sa.selected_bid_id, sa.winner_id, sa.final_price, sa.created_at, sa.updated_at, sa.owner_name, sa.region_name, sa.interest_name, sa.notified_at, sa.last_motivation_sent_at, sa.selection_warning_sent_at, sa.moderation_reason, sa.moderated_by_admin_id, sa.moderated_at FROM sell_auctions sa
WHERE sa.status = 'active' AND sa.end_time > NOW()
  AND sa.title ILIKE '%' || $3::text || '%'
  AND ($4::int IS NULL OR sa.owner_id != $4::int)
  AND ($5::int[] IS NULL OR sa.id NOT IN (
    SELECT sb.auction_id FROM sell_bids sb WHERE sb.bidder_id = $6::int
  ))
  AND ($7::int = 0 OR sa.region_id = $7::int)
  AND ($8::text[] IS NULL OR cardinality($8::text[]) = 0 OR EXISTS (
    SELECT 1 FROM users ow WHERE ow.id = sa.owner_id AND ow.job_key = ANY($8::text[])))
ORDER BY
  CASE WHEN sa.interest_id = ANY($9::integer[]) THEN 0 ELSE 1 END,
  sa.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchSellAuctionsParams struct {
	Limit                 int32    `json:"limit"`
	Offset                int32    `json:"offset"`
	SearchTerm            string   `json:"search_term"`
	ExcludeOwnerID        int32    `json:"exclude_owner_id"`
	ExcludeBiddedAuctions []int32  `json:"exclude_bidded_auctions"`
	UserID                int32    `json:"user_id"`
	FilterRegionID        int32    `json:"filter_region_id"`
	OwnerJobKeys          []string `json:"owner_job_keys"`
	UserInterestIds       []int32  `json:"user_interest_ids"`
}

func (q *Queries) SearchSellAuctions(ctx context.Context, arg SearchSellAuctionsParams) ([]SellAuction, error) {
	rows, err := q.db.Query(ctx, searchSellAuctions,
		arg.Limit,
		arg.Offset,
		arg.SearchTerm,
		arg.ExcludeOwnerID,
		arg.ExcludeBiddedAuctions,
		arg.UserID,
		arg.FilterRegionID,
		arg.OwnerJobKeys,
		arg.UserInterestIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellAuction
	for rows.Next() {
		var i SellAuction
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.RegionID,
			&i.InterestID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.BuyAllFromOne,
			&i.BidCount,
			&i.EndTime,
			&i.Status,
			&i.SelectedBidID,
			&i.WinnerID,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.RegionName,
			&i.InterestName,
			&i.NotifiedAt,
			&i.LastMotivationSentAt,
			&i.SelectionWarningSentAt,
			&i.ModerationReason,
			&i.ModeratedByAdminID,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSellWinner = `-- name: SelectSellWinner :exec
UPDATE sell_auctions
SET selected_bid_id = $2, winner_id = $3, final_price = $4, status = 'winner_selected', updated_at = NOW()
WHERE id = $1
`

type SelectSellWinnerParams struct {
	ID            int32          `json:"id"`
	SelectedBidID pgtype.Int4    `json:"selected_bid_id"`
	WinnerID      pgtype.Int4    `json:"winner_id"`
	FinalPrice    pgtype.Numeric `json:"final_price"`
}

func (q *Queries) SelectSellWinner(ctx context.Context, arg SelectSellWinnerParams) error {
	_, err := q.db.Exec(ctx, selectSellWinner,
		arg.ID,
		arg.SelectedBidID,
		arg.WinnerID,
		arg.FinalPrice,
	)
	return err
}

const suspendSellAuction = `-- name: SuspendSellAuction :one
UPDATE sell_auctions
SET status = 'suspended',
    moderation_reason = $1::text,
    moderated_by_admin_id = $2::int,
    moderated_at = NOW(),
    updated_at = NOW()
WHERE public_id = $3 AND status = 'active'
RETURNING id, public_id, owner_id, region_id, interest_id, title, description, image_url, unit, quantity, unit_price, buy_all_from_one, bid_count, end_time, status, selected_bid_id, winner_id, final_price, created_at, updated_at, owner_name, region_name, interest_name, notified_at, last_motivation_sent_at, selection_warning_sent_at, moderation_reason, moderated_by_admin_id, moderated_at
`

type SuspendSellAuctionParams struct {
	Reason   string      `json:"reason"`
	AdminID  int32       `json:"admin_id"`
	PublicID pgtype.UUID `json:"public_id"`
}

func (q *Queries) SuspendSellAuction(ctx context.Context, arg SuspendSellAuctionParams) (SellAuction, error) {
	row := q.db.QueryRow(ctx, suspendSellAuction, arg.Reason, arg.AdminID, arg.PublicID)
	var i SellAuction
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.RegionID,
		&i.InterestID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.BuyAllFromOne,
		&i.BidCount,
		&i.EndTime,
		&i.Status,
		&i.SelectedBidID,
		&i.WinnerID,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.RegionName,
		&i.InterestName,
		&i.NotifiedAt,
		&i.LastMotivationSentAt,
		&i.SelectionWarningSentAt,
		&i.ModerationReason,
		&i.ModeratedByAdminID,
		&i.ModeratedAt,
	)
	return i, err
}

const updateSellAuctionStatus = `-- name: UpdateSellAuctionStatus :exec
UPDATE sell_auctions SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSellAuctionStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSellAuctionStatus(ctx context.Context, arg UpdateSellAuctionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSellAuctionStatus, arg.ID, arg.Status)
	return err
}
