// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sell_bids.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSellBidsByBidder = `-- name: CountActiveSellBidsByBidder :one
SELECT COUNT(*) FROM sell_bids sb
JOIN sell_auctions sa ON sa.id = sb.auction_id
WHERE sb.bidder_id = $1 AND sa.status = 'active'
`

func (q *Queries) CountActiveSellBidsByBidder(ctx context.Context, bidderID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSellBidsByBidder, bidderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSellBidsByUser = `-- name: CountActiveSellBidsByUser :one
SELECT COUNT(*) FROM sell_bids sb
JOIN sell_auctions sa ON sa.id = sb.auction_id
WHERE sb.bidder_id = $1 AND sa.status = 'active'
`

func (q *Queries) CountActiveSellBidsByUser(ctx context.Context, bidderID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSellBidsByUser, bidderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSellBidsByAuction = `-- name: CountSellBidsByAuction :one
SELECT COUNT(*) FROM sell_bids WHERE auction_id = $1
`

func (q *Queries) CountSellBidsByAuction(ctx context.Context, auctionID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSellBidsByAuction, auctionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSellBid = `-- name: CreateSellBid :one
INSERT INTO sell_bids (auction_id, bidder_id, amount, bidder_region_name, bidder_fake_name, auction_title, auction_unit_price, auction_quantity, auction_unit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, public_id, auction_id, bidder_id, amount, is_selected, created_at, bidder_region_name, bidder_fake_name, auction_title, auction_unit_price, auction_quantity, auction_unit, is_not_chosen
`

type CreateSellBidParams struct {
	AuctionID        int32          `json:"auction_id"`
	BidderID         int32          `json:"bidder_id"`
	Amount           pgtype.Numeric `json:"amount"`
	BidderRegionName string         `json:"bidder_region_name"`
	BidderFakeName   string         `json:"bidder_fake_name"`
	AuctionTitle     string         `json:"auction_title"`
	AuctionUnitPrice pgtype.Numeric `json:"auction_unit_price"`
	AuctionQuantity  pgtype.Numeric `json:"auction_quantity"`
	AuctionUnit      string         `json:"auction_unit"`
}

func (q *Queries) CreateSellBid(ctx context.Context, arg CreateSellBidParams) (SellBid, error) {
	row := q.db.QueryRow(ctx, createSellBid,
		arg.AuctionID,
		arg.BidderID,
		arg.Amount,
		arg.BidderRegionName,
		arg.BidderFakeName,
		arg.AuctionTitle,
		arg.AuctionUnitPrice,
		arg.AuctionQuantity,
		arg.AuctionUnit,
	)
	var i SellBid
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsSelected,
		&i.CreatedAt,
		&i.BidderRegionName,
		&i.BidderFakeName,
		&i.AuctionTitle,
		&i.AuctionUnitPrice,
		&i.AuctionQuantity,
		&i.AuctionUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getLosingBidderIDsForAuction = `-- name: GetLosingBidderIDsForAuction :many
SELECT DISTINCT bidder_id
FROM sell_bids
WHERE auction_id = $1 AND id != $2
`

type GetLosingBidderIDsForAuctionParams struct {
	AuctionID int32 `json:"auction_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) GetLosingBidderIDsForAuction(ctx context.Context, arg GetLosingBidderIDsForAuctionParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getLosingBidderIDsForAuction, arg.AuctionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var bidder_id int32
		if err := rows.Scan(&bidder_id); err != nil {
			return nil, err
		}
		items = append(items, bidder_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellBidByAuctionAndBidder = `-- name: GetSellBidByAuctionAndBidder :one
SELECT id, public_id, auction_id, bidder_id, amount, is_selected, created_at, bidder_region_name, bidder_fake_name, auction_title, auction_unit_price, auction_quantity, auction_unit, is_not_chosen FROM sell_bids WHERE auction_id = $1 AND bidder_id = $2
`

type GetSellBidByAuctionAndBidderParams struct {
	AuctionID int32 `json:"auction_id"`
	BidderID  int32 `json:"bidder_id"`
}

func (q *Queries) GetSellBidByAuctionAndBidder(ctx context.Context, arg GetSellBidByAuctionAndBidderParams) (SellBid, error) {
	row := q.db.QueryRow(ctx, getSellBidByAuctionAndBidder, arg.AuctionID, arg.BidderID)
	var i SellBid
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsSelected,
		&i.CreatedAt,
		&i.BidderRegionName,
		&i.BidderFakeName,
		&i.AuctionTitle,
		&i.AuctionUnitPrice,
		&i.AuctionQuantity,
		&i.AuctionUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getSellBidByID = `-- name: GetSellBidByID :one
SELECT id, public_id, auction_id, bidder_id, amount, is_selected, created_at, bidder_region_name, bidder_fake_name, auction_title, auction_unit_price, auction_quantity, auction_unit, is_not_chosen FROM sell_bids WHERE id = $1
`

func (q *Queries) GetSellBidByID(ctx context.Context, id int32) (SellBid, error) {
	row := q.db.QueryRow(ctx, getSellBidByID, id)
	var i SellBid
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsSelected,
		&i.CreatedAt,
		&i.BidderRegionName,
		&i.BidderFakeName,
		&i.AuctionTitle,
		&i.AuctionUnitPrice,
		&i.AuctionQuantity,
		&i.AuctionUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getSellBidByPublicID = `-- name: GetSellBidByPublicID :one
SELECT id, public_id, auction_id, bidder_id, amount, is_selected, created_at, bidder_region_name, bidder_fake_name, auction_title, auction_unit_price, auction_quantity, auction_unit, is_not_chosen FROM sell_bids WHERE public_id = $1
`

func (q *Queries) GetSellBidByPublicID(ctx context.Context, publicID pgtype.UUID) (SellBid, error) {
	row := q.db.QueryRow(ctx, getSellBidByPublicID, publicID)
	var i SellBid
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsSelected,
		&i.CreatedAt,
		&i.BidderRegionName,
		&i.BidderFakeName,
		&i.AuctionTitle,
		&i.AuctionUnitPrice,
		&i.AuctionQuantity,
		&i.AuctionUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const listSellBidsByAuction = `-- name: ListSellBidsByAuction :many
SELECT 
    sb.id, sb.public_id, sb.auction_id, sb.bidder_id, sb.amount, sb.is_selected, sb.created_at, sb.bidder_region_name, sb.bidder_fake_name, sb.auction_title, sb.auction_unit_price, sb.auction_quantity, sb.auction_unit, sb.is_not_chosen,
    sb.bidder_fake_name as bidder_name,
    sb.bidder_region_name as bidder_region
FROM sell_bids sb 
WHERE sb.auction_id = $1
ORDER BY sb.amount DESC, sb.created_at ASC
`

type ListSellBidsByAuctionRow struct {
	ID               int32              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	AuctionID        int32              `json:"auction_id"`
	BidderID         int32              `json:"bidder_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	IsSelected       bool               `json:"is_selected"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BidderRegionName string             `json:"bidder_region_name"`
	BidderFakeName   string             `json:"bidder_fake_name"`
	AuctionTitle     string             `json:"auction_title"`
	AuctionUnitPrice pgtype.Numeric     `json:"auction_unit_price"`
	AuctionQuantity  pgtype.Numeric     `json:"auction_quantity"`
	AuctionUnit      string             `json:"auction_unit"`
	IsNotChosen      bool               `json:"is_not_chosen"`
	BidderName       string             `json:"bidder_name"`
	BidderRegion     string             `json:"bidder_region"`
}

func (q *Queries) ListSellBidsByAuction(ctx context.Context, auctionID int32) ([]ListSellBidsByAuctionRow, error) {
	rows, err := q.db.Query(ctx, listSellBidsByAuction, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellBidsByAuctionRow
	for rows.Next() {
		var i ListSellBidsByAuctionRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.AuctionID,
			&i.BidderID,
			&i.Amount,
			&i.IsSelected,
			&i.CreatedAt,
			&i.BidderRegionName,
			&i.BidderFakeName,
			&i.AuctionTitle,
			&i.AuctionUnitPrice,
			&i.AuctionQuantity,
			&i.AuctionUnit,
			&i.IsNotChosen,
			&i.BidderName,
			&i.BidderRegion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellBidsByBidder = `-- name: ListSellBidsByBidder :many
SELECT sb.id, sb.public_id, sb.auction_id, sb.bidder_id, sb.amount, sb.is_selected, sb.created_at, sb.bidder_region_name, sb.bidder_fake_name, sb.auction_title, sb.auction_unit_price, sb.auction_quantity, sb.auction_unit, sb.is_not_chosen, sa.title as auction_title, sa.public_id as auction_public_id,
       sa.status as auction_status, sa.end_time as auction_end_time
FROM sell_bids sb
JOIN sell_auctions sa ON sa.id = sb.auction_id
WHERE sb.bidder_id = $1
ORDER BY sb.created_at DESC LIMIT $2 OFFSET $3
`

type ListSellBidsByBidderParams struct {
	BidderID int32 `json:"bidder_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListSellBidsByBidderRow struct {
	ID               int32              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	AuctionID        int32              `json:"auction_id"`
	BidderID         int32              `json:"bidder_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	IsSelected       bool               `json:"is_selected"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BidderRegionName string             `json:"bidder_region_name"`
	BidderFakeName   string             `json:"bidder_fake_name"`
	AuctionTitle     string             `json:"auction_title"`
	AuctionUnitPrice pgtype.Numeric     `json:"auction_unit_price"`
	AuctionQuantity  pgtype.Numeric     `json:"auction_quantity"`
	AuctionUnit      string             `json:"auction_unit"`
	IsNotChosen      bool               `json:"is_not_chosen"`
	AuctionTitle_2   string             `json:"auction_title_2"`
	AuctionPublicID  pgtype.UUID        `json:"auction_public_id"`
	AuctionStatus    string             `json:"auction_status"`
	AuctionEndTime   pgtype.Timestamptz `json:"auction_end_time"`
}

func (q *Queries) ListSellBidsByBidder(ctx context.Context, arg ListSellBidsByBidderParams) ([]ListSellBidsByBidderRow, error) {
	rows, err := q.db.Query(ctx, listSellBidsByBidder, arg.BidderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellBidsByBidderRow
	for rows.Next() {
		var i ListSellBidsByBidderRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.AuctionID,
			&i.BidderID,
			&i.Amount,
			&i.IsSelected,
			&i.CreatedAt,
			&i.BidderRegionName,
			&i.BidderFakeName,
			&i.AuctionTitle,
			&i.AuctionUnitPrice,
			&i.AuctionQuantity,
			&i.AuctionUnit,
			&i.IsNotChosen,
			&i.AuctionTitle_2,
			&i.AuctionPublicID,
			&i.AuctionStatus,
			&i.AuctionEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotChosenSellBids = `-- name: MarkNotChosenSellBids :exec
UPDATE sell_bids SET is_not_chosen = TRUE
WHERE auction_id = $1 AND is_selected = FALSE
`

func (q *Queries) MarkNotChosenSellBids(ctx context.Context, auctionID int32) error {
	_, err := q.db.Exec(ctx, markNotChosenSellBids, auctionID)
	return err
}

const selectSellBid = `-- name: SelectSellBid :exec
UPDATE sell_bids SET is_selected = TRUE WHERE id = $1
`

func (q *Queries) SelectSellBid(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, selectSellBid, id)
	return err
}
