// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipping.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearShippingCompanyRegions = `-- name: ClearShippingCompanyRegions :exec
DELETE FROM shipping_company_regions WHERE shipping_company_id = $1
`

func (q *Queries) ClearShippingCompanyRegions(ctx context.Context, shippingCompanyID int32) error {
	_, err := q.db.Exec(ctx, clearShippingCompanyRegions, shippingCompanyID)
	return err
}

const createShippingCompany = `-- name: CreateShippingCompany :one
INSERT INTO shipping_companies (name, phone, logo_url, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, name, phone, logo_url, notes, is_active, created_at, updated_at
`

type CreateShippingCompanyParams struct {
	Name    string      `json:"name"`
	Phone   string      `json:"phone"`
	LogoUrl pgtype.Text `json:"logo_url"`
	Notes   pgtype.Text `json:"notes"`
}

func (q *Queries) CreateShippingCompany(ctx context.Context, arg CreateShippingCompanyParams) (ShippingCompany, error) {
	row := q.db.QueryRow(ctx, createShippingCompany,
		arg.Name,
		arg.Phone,
		arg.LogoUrl,
		arg.Notes,
	)
	var i ShippingCompany
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Phone,
		&i.LogoUrl,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateShippingCompany = `-- name: DeactivateShippingCompany :exec
UPDATE shipping_companies SET is_active = FALSE, updated_at = NOW() WHERE public_id = $1
`

// Soft delete: a merchant may already have written the number down, and the
// admin's own history should not lose the record.
func (q *Queries) DeactivateShippingCompany(ctx context.Context, publicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateShippingCompany, publicID)
	return err
}

const getShippingCompanyByPublicID = `-- name: GetShippingCompanyByPublicID :one
SELECT id, public_id, name, phone, logo_url, notes, is_active, created_at, updated_at FROM shipping_companies WHERE public_id = $1
`

func (q *Queries) GetShippingCompanyByPublicID(ctx context.Context, publicID pgtype.UUID) (ShippingCompany, error) {
	row := q.db.QueryRow(ctx, getShippingCompanyByPublicID, publicID)
	var i ShippingCompany
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Phone,
		&i.LogoUrl,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllShippingCompanies = `-- name: ListAllShippingCompanies :many
SELECT id, public_id, name, phone, logo_url, notes, is_active, created_at, updated_at FROM shipping_companies ORDER BY is_active DESC, name
`

// Admin view: everything, including deactivated carriers.
func (q *Queries) ListAllShippingCompanies(ctx context.Context) ([]ShippingCompany, error) {
	rows, err := q.db.Query(ctx, listAllShippingCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingCompany
	for rows.Next() {
		var i ShippingCompany
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Phone,
			&i.LogoUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingCompaniesByRegion = `-- name: ListShippingCompaniesByRegion :many
SELECT sc.id, sc.public_id, sc.name, sc.phone, sc.logo_url, sc.notes, sc.is_active, sc.created_at, sc.updated_at FROM shipping_companies sc
JOIN shipping_company_regions scr ON scr.shipping_company_id = sc.id
WHERE sc.is_active = TRUE AND scr.region_id = $1
ORDER BY sc.name
`

// What a merchant sees while creating a post: active carriers that actually
// serve the post's governorate.
func (q *Queries) ListShippingCompaniesByRegion(ctx context.Context, regionID int32) ([]ShippingCompany, error) {
	rows, err := q.db.Query(ctx, listShippingCompaniesByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingCompany
	for rows.Next() {
		var i ShippingCompany
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Phone,
			&i.LogoUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingCompanyRegions = `-- name: ListShippingCompanyRegions :many
SELECT r.id, r.name_ar
FROM shipping_company_regions scr
JOIN regions r ON r.id = scr.region_id
WHERE scr.shipping_company_id = $1
ORDER BY r.id
`

type ListShippingCompanyRegionsRow struct {
	ID     int32  `json:"id"`
	NameAr string `json:"name_ar"`
}

func (q *Queries) ListShippingCompanyRegions(ctx context.Context, shippingCompanyID int32) ([]ListShippingCompanyRegionsRow, error) {
	rows, err := q.db.Query(ctx, listShippingCompanyRegions, shippingCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShippingCompanyRegionsRow
	for rows.Next() {
		var i ListShippingCompanyRegionsRow
		if err := rows.Scan(&i.ID, &i.NameAr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setShippingCompanyRegions = `-- name: SetShippingCompanyRegions :exec
INSERT INTO shipping_company_regions (shipping_company_id, region_id)
SELECT $1, unnest($2::int[])
ON CONFLICT DO NOTHING
`

type SetShippingCompanyRegionsParams struct {
	ShippingCompanyID int32   `json:"shipping_company_id"`
	RegionIds         []int32 `json:"region_ids"`
}

// Coverage is replaced wholesale rather than added and removed one at a time —
// it is a checkbox list in practice. Paired with ClearShippingCompanyRegions.
func (q *Queries) SetShippingCompanyRegions(ctx context.Context, arg SetShippingCompanyRegionsParams) error {
	_, err := q.db.Exec(ctx, setShippingCompanyRegions, arg.ShippingCompanyID, arg.RegionIds)
	return err
}

const updateShippingCompany = `-- name: UpdateShippingCompany :one
UPDATE shipping_companies
SET name = $2, phone = $3, logo_url = $4, notes = $5, is_active = $6, updated_at = NOW()
WHERE public_id = $1
RETURNING id, public_id, name, phone, logo_url, notes, is_active, created_at, updated_at
`

type UpdateShippingCompanyParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	Name     string      `json:"name"`
	Phone    string      `json:"phone"`
	LogoUrl  pgtype.Text `json:"logo_url"`
	Notes    pgtype.Text `json:"notes"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateShippingCompany(ctx context.Context, arg UpdateShippingCompanyParams) (ShippingCompany, error) {
	row := q.db.QueryRow(ctx, updateShippingCompany,
		arg.PublicID,
		arg.Name,
		arg.Phone,
		arg.LogoUrl,
		arg.Notes,
		arg.IsActive,
	)
	var i ShippingCompany
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Phone,
		&i.LogoUrl,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
