// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipping_quotes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptShippingQuote = `-- name: AcceptShippingQuote :one
UPDATE shipping_quotes
SET status = 'accepted', accepted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at
`

func (q *Queries) AcceptShippingQuote(ctx context.Context, id int32) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, acceptShippingQuote, id)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attachCarrierToOrder = `-- name: AttachCarrierToOrder :one
UPDATE orders
SET carrier_id = $2, shipping_price = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, public_id, sell_auction_id, buy_request_id, seller_id, buyer_id, final_price, quantity, unit, status, seller_confirmed_at, buyer_confirmed_at, completed_at, created_at, updated_at, seller_name, seller_phone, seller_region, buyer_name, buyer_phone, buyer_region, source_public_id, confirmation_deadline, cancelled_at, carrier_id, shipping_price, seller_region_id, buyer_region_id
`

type AttachCarrierToOrderParams struct {
	ID            int32          `json:"id"`
	CarrierID     pgtype.Int4    `json:"carrier_id"`
	ShippingPrice pgtype.Numeric `json:"shipping_price"`
}

func (q *Queries) AttachCarrierToOrder(ctx context.Context, arg AttachCarrierToOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, attachCarrierToOrder, arg.ID, arg.CarrierID, arg.ShippingPrice)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.SellerID,
		&i.BuyerID,
		&i.FinalPrice,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.SellerConfirmedAt,
		&i.BuyerConfirmedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerPhone,
		&i.SellerRegion,
		&i.BuyerName,
		&i.BuyerPhone,
		&i.BuyerRegion,
		&i.SourcePublicID,
		&i.ConfirmationDeadline,
		&i.CancelledAt,
		&i.CarrierID,
		&i.ShippingPrice,
		&i.SellerRegionID,
		&i.BuyerRegionID,
	)
	return i, err
}

const countQuotableBuyRequestsForCarrier = `-- name: CountQuotableBuyRequestsForCarrier :one
SELECT COUNT(*) FROM buy_requests br
WHERE br.status = 'active' AND br.end_time > NOW()
  AND br.region_id = ANY($1::int[])
`

func (q *Queries) CountQuotableBuyRequestsForCarrier(ctx context.Context, regionIds []int32) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotableBuyRequestsForCarrier, regionIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuotableOrdersForCarrier = `-- name: CountQuotableOrdersForCarrier :one
SELECT COUNT(*) FROM orders o
WHERE o.carrier_id IS NULL
  AND o.status IN ('created', 'seller_confirmed', 'buyer_confirmed', 'completed')
  AND (o.seller_region_id = ANY($1::int[]) OR o.buyer_region_id = ANY($1::int[]))
`

func (q *Queries) CountQuotableOrdersForCarrier(ctx context.Context, regionIds []int32) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotableOrdersForCarrier, regionIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuotableSellAuctionsForCarrier = `-- name: CountQuotableSellAuctionsForCarrier :one
SELECT COUNT(*) FROM sell_auctions sa
WHERE sa.status = 'active' AND sa.end_time > NOW()
  AND sa.region_id = ANY($1::int[])
`

func (q *Queries) CountQuotableSellAuctionsForCarrier(ctx context.Context, regionIds []int32) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotableSellAuctionsForCarrier, regionIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShippingQuotesByCarrier = `-- name: CountShippingQuotesByCarrier :one
SELECT COUNT(*) FROM shipping_quotes WHERE carrier_id = $1
`

func (q *Queries) CountShippingQuotesByCarrier(ctx context.Context, carrierID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countShippingQuotesByCarrier, carrierID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShippingQuote = `-- name: CreateShippingQuote :one

INSERT INTO shipping_quotes (carrier_id, sell_auction_id, buy_request_id, order_id, price, notes)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at
`

type CreateShippingQuoteParams struct {
	CarrierID     int32          `json:"carrier_id"`
	SellAuctionID pgtype.Int4    `json:"sell_auction_id"`
	BuyRequestID  pgtype.Int4    `json:"buy_request_id"`
	OrderID       pgtype.Int4    `json:"order_id"`
	Price         pgtype.Numeric `json:"price"`
	Notes         pgtype.Text    `json:"notes"`
}

// Quotes.
func (q *Queries) CreateShippingQuote(ctx context.Context, arg CreateShippingQuoteParams) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, createShippingQuote,
		arg.CarrierID,
		arg.SellAuctionID,
		arg.BuyRequestID,
		arg.OrderID,
		arg.Price,
		arg.Notes,
	)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcceptedQuoteForOrder = `-- name: GetAcceptedQuoteForOrder :one
SELECT q.id, q.public_id, q.carrier_id, q.sell_auction_id, q.buy_request_id, q.order_id, q.price, q.notes, q.status, q.accepted_at, q.created_at, q.updated_at, u.name AS carrier_name, u.phone AS carrier_phone
FROM shipping_quotes q
JOIN users u ON u.id = q.carrier_id
WHERE q.order_id = $1 AND q.status = 'accepted'
`

type GetAcceptedQuoteForOrderRow struct {
	ID            int32              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	CarrierID     int32              `json:"carrier_id"`
	SellAuctionID pgtype.Int4        `json:"sell_auction_id"`
	BuyRequestID  pgtype.Int4        `json:"buy_request_id"`
	OrderID       pgtype.Int4        `json:"order_id"`
	Price         pgtype.Numeric     `json:"price"`
	Notes         pgtype.Text        `json:"notes"`
	Status        string             `json:"status"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CarrierName   string             `json:"carrier_name"`
	CarrierPhone  pgtype.Text        `json:"carrier_phone"`
}

func (q *Queries) GetAcceptedQuoteForOrder(ctx context.Context, orderID pgtype.Int4) (GetAcceptedQuoteForOrderRow, error) {
	row := q.db.QueryRow(ctx, getAcceptedQuoteForOrder, orderID)
	var i GetAcceptedQuoteForOrderRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CarrierName,
		&i.CarrierPhone,
	)
	return i, err
}

const getAcceptedQuoteForPost = `-- name: GetAcceptedQuoteForPost :one
SELECT id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at FROM shipping_quotes
WHERE status = 'accepted'
  AND (($1::int > 0 AND sell_auction_id = $1::int)
    OR ($2::int > 0 AND buy_request_id = $2::int))
LIMIT 1
`

type GetAcceptedQuoteForPostParams struct {
	SellAuctionID int32 `json:"sell_auction_id"`
	BuyRequestID  int32 `json:"buy_request_id"`
}

// Post-stage acceptance happens before an order exists, so when the deal closes
// the winning carrier has to be carried onto it — otherwise the order looks
// unshipped and the carrier feed would offer it again.
func (q *Queries) GetAcceptedQuoteForPost(ctx context.Context, arg GetAcceptedQuoteForPostParams) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, getAcceptedQuoteForPost, arg.SellAuctionID, arg.BuyRequestID)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShippingQuoteByPublicID = `-- name: GetShippingQuoteByPublicID :one
SELECT id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at FROM shipping_quotes WHERE public_id = $1
`

func (q *Queries) GetShippingQuoteByPublicID(ctx context.Context, publicID pgtype.UUID) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, getShippingQuoteByPublicID, publicID)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShippingQuoteByPublicIDForUpdate = `-- name: GetShippingQuoteByPublicIDForUpdate :one
SELECT id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at FROM shipping_quotes WHERE public_id = $1 FOR UPDATE
`

func (q *Queries) GetShippingQuoteByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, getShippingQuoteByPublicIDForUpdate, publicID)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotableBuyRequestsForCarrier = `-- name: ListQuotableBuyRequestsForCarrier :many
SELECT br.public_id, br.title, br.quantity, br.unit, br.end_time, br.created_at,
       br.region_name, i.name_ar AS interest_name,
       EXISTS (
           SELECT 1 FROM shipping_quotes q
           WHERE q.buy_request_id = br.id AND q.carrier_id = $3::int
             AND q.status <> 'withdrawn'
       ) AS already_quoted
FROM buy_requests br
JOIN interests i ON i.id = br.interest_id
WHERE br.status = 'active' AND br.end_time > NOW()
  AND br.region_id = ANY($4::int[])
ORDER BY br.created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuotableBuyRequestsForCarrierParams struct {
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
	CarrierID int32   `json:"carrier_id"`
	RegionIds []int32 `json:"region_ids"`
}

type ListQuotableBuyRequestsForCarrierRow struct {
	PublicID      pgtype.UUID        `json:"public_id"`
	Title         string             `json:"title"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          string             `json:"unit"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RegionName    string             `json:"region_name"`
	InterestName  string             `json:"interest_name"`
	AlreadyQuoted bool               `json:"already_quoted"`
}

func (q *Queries) ListQuotableBuyRequestsForCarrier(ctx context.Context, arg ListQuotableBuyRequestsForCarrierParams) ([]ListQuotableBuyRequestsForCarrierRow, error) {
	rows, err := q.db.Query(ctx, listQuotableBuyRequestsForCarrier,
		arg.Limit,
		arg.Offset,
		arg.CarrierID,
		arg.RegionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuotableBuyRequestsForCarrierRow
	for rows.Next() {
		var i ListQuotableBuyRequestsForCarrierRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Title,
			&i.Quantity,
			&i.Unit,
			&i.EndTime,
			&i.CreatedAt,
			&i.RegionName,
			&i.InterestName,
			&i.AlreadyQuoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotableOrdersForCarrier = `-- name: ListQuotableOrdersForCarrier :many

SELECT o.public_id, o.quantity, o.unit, o.status, o.created_at,
       o.seller_region, o.buyer_region,
       sa.title AS sell_title, br.title AS buy_title,
       si.name_ar AS sell_interest, bi.name_ar AS buy_interest,
       EXISTS (
           SELECT 1 FROM shipping_quotes q
           WHERE q.order_id = o.id AND q.carrier_id = $3::int
             AND q.status <> 'withdrawn'
       ) AS already_quoted
FROM orders o
LEFT JOIN sell_auctions sa ON sa.id = o.sell_auction_id
LEFT JOIN buy_requests br ON br.id = o.buy_request_id
LEFT JOIN interests si ON si.id = sa.interest_id
LEFT JOIN interests bi ON bi.id = br.interest_id
WHERE o.carrier_id IS NULL
  AND o.status IN ('created', 'seller_confirmed', 'buyer_confirmed', 'completed')
  AND (o.seller_region_id = ANY($4::int[]) OR o.buyer_region_id = ANY($4::int[]))
ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuotableOrdersForCarrierParams struct {
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
	CarrierID int32   `json:"carrier_id"`
	RegionIds []int32 `json:"region_ids"`
}

type ListQuotableOrdersForCarrierRow struct {
	PublicID      pgtype.UUID        `json:"public_id"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          string             `json:"unit"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SellerRegion  string             `json:"seller_region"`
	BuyerRegion   string             `json:"buyer_region"`
	SellTitle     pgtype.Text        `json:"sell_title"`
	BuyTitle      pgtype.Text        `json:"buy_title"`
	SellInterest  pgtype.Text        `json:"sell_interest"`
	BuyInterest   pgtype.Text        `json:"buy_interest"`
	AlreadyQuoted bool               `json:"already_quoted"`
}

// Carrier-facing job feeds.
//
// Every one of these deliberately omits the money: final_price, unit_price and
// total_price never leave the database on a carrier request. Transport is priced
// on weight, distance and goods type, so a carrier has no need for the value of
// the cargo — and handing a third party the market's pricing is not recoverable
// once done.
// Deals that still need moving: both parties have a stake, no carrier chosen
// yet, and at least one end sits in a governorate this carrier serves.
func (q *Queries) ListQuotableOrdersForCarrier(ctx context.Context, arg ListQuotableOrdersForCarrierParams) ([]ListQuotableOrdersForCarrierRow, error) {
	rows, err := q.db.Query(ctx, listQuotableOrdersForCarrier,
		arg.Limit,
		arg.Offset,
		arg.CarrierID,
		arg.RegionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuotableOrdersForCarrierRow
	for rows.Next() {
		var i ListQuotableOrdersForCarrierRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.CreatedAt,
			&i.SellerRegion,
			&i.BuyerRegion,
			&i.SellTitle,
			&i.BuyTitle,
			&i.SellInterest,
			&i.BuyInterest,
			&i.AlreadyQuoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotableSellAuctionsForCarrier = `-- name: ListQuotableSellAuctionsForCarrier :many
SELECT sa.public_id, sa.title, sa.quantity, sa.unit, sa.end_time, sa.created_at,
       sa.region_name, i.name_ar AS interest_name,
       EXISTS (
           SELECT 1 FROM shipping_quotes q
           WHERE q.sell_auction_id = sa.id AND q.carrier_id = $3::int
             AND q.status <> 'withdrawn'
       ) AS already_quoted
FROM sell_auctions sa
JOIN interests i ON i.id = sa.interest_id
WHERE sa.status = 'active' AND sa.end_time > NOW()
  AND sa.region_id = ANY($4::int[])
ORDER BY sa.created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuotableSellAuctionsForCarrierParams struct {
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
	CarrierID int32   `json:"carrier_id"`
	RegionIds []int32 `json:"region_ids"`
}

type ListQuotableSellAuctionsForCarrierRow struct {
	PublicID      pgtype.UUID        `json:"public_id"`
	Title         string             `json:"title"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          string             `json:"unit"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RegionName    string             `json:"region_name"`
	InterestName  string             `json:"interest_name"`
	AlreadyQuoted bool               `json:"already_quoted"`
}

// Post-stage mode. The destination does not exist yet — no winner means no
// buyer — so a quote here is indicative on the origin governorate alone.
func (q *Queries) ListQuotableSellAuctionsForCarrier(ctx context.Context, arg ListQuotableSellAuctionsForCarrierParams) ([]ListQuotableSellAuctionsForCarrierRow, error) {
	rows, err := q.db.Query(ctx, listQuotableSellAuctionsForCarrier,
		arg.Limit,
		arg.Offset,
		arg.CarrierID,
		arg.RegionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuotableSellAuctionsForCarrierRow
	for rows.Next() {
		var i ListQuotableSellAuctionsForCarrierRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Title,
			&i.Quantity,
			&i.Unit,
			&i.EndTime,
			&i.CreatedAt,
			&i.RegionName,
			&i.InterestName,
			&i.AlreadyQuoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingQuotesByCarrier = `-- name: ListShippingQuotesByCarrier :many
SELECT q.id, q.public_id, q.carrier_id, q.sell_auction_id, q.buy_request_id, q.order_id, q.price, q.notes, q.status, q.accepted_at, q.created_at, q.updated_at,
       COALESCE(sa.title, br.title, osa.title, obr.title, '') AS job_title,
       COALESCE(sa.region_name, br.region_name, o.seller_region, '') AS job_region,
       o.public_id AS order_public_id,
       sa.public_id AS sell_auction_public_id,
       br.public_id AS buy_request_public_id
FROM shipping_quotes q
LEFT JOIN sell_auctions sa ON sa.id = q.sell_auction_id
LEFT JOIN buy_requests br ON br.id = q.buy_request_id
LEFT JOIN orders o ON o.id = q.order_id
LEFT JOIN sell_auctions osa ON osa.id = o.sell_auction_id
LEFT JOIN buy_requests obr ON obr.id = o.buy_request_id
WHERE q.carrier_id = $1
ORDER BY q.created_at DESC
LIMIT $2 OFFSET $3
`

type ListShippingQuotesByCarrierParams struct {
	CarrierID int32 `json:"carrier_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListShippingQuotesByCarrierRow struct {
	ID                  int32              `json:"id"`
	PublicID            pgtype.UUID        `json:"public_id"`
	CarrierID           int32              `json:"carrier_id"`
	SellAuctionID       pgtype.Int4        `json:"sell_auction_id"`
	BuyRequestID        pgtype.Int4        `json:"buy_request_id"`
	OrderID             pgtype.Int4        `json:"order_id"`
	Price               pgtype.Numeric     `json:"price"`
	Notes               pgtype.Text        `json:"notes"`
	Status              string             `json:"status"`
	AcceptedAt          pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	JobTitle            string             `json:"job_title"`
	JobRegion           string             `json:"job_region"`
	OrderPublicID       pgtype.UUID        `json:"order_public_id"`
	SellAuctionPublicID pgtype.UUID        `json:"sell_auction_public_id"`
	BuyRequestPublicID  pgtype.UUID        `json:"buy_request_public_id"`
}

// The carrier's own list, so their own prices are theirs to see. The job's title
// comes from whichever target the quote points at.
func (q *Queries) ListShippingQuotesByCarrier(ctx context.Context, arg ListShippingQuotesByCarrierParams) ([]ListShippingQuotesByCarrierRow, error) {
	rows, err := q.db.Query(ctx, listShippingQuotesByCarrier, arg.CarrierID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShippingQuotesByCarrierRow
	for rows.Next() {
		var i ListShippingQuotesByCarrierRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CarrierID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.OrderID,
			&i.Price,
			&i.Notes,
			&i.Status,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.JobRegion,
			&i.OrderPublicID,
			&i.SellAuctionPublicID,
			&i.BuyRequestPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingQuotesForBuyRequest = `-- name: ListShippingQuotesForBuyRequest :many
SELECT q.id, q.public_id, q.carrier_id, q.sell_auction_id, q.buy_request_id, q.order_id, q.price, q.notes, q.status, q.accepted_at, q.created_at, q.updated_at, u.name AS carrier_name, u.phone AS carrier_phone,
       cp.logo_url AS carrier_logo, cp.notes AS carrier_notes
FROM shipping_quotes q
JOIN users u ON u.id = q.carrier_id
LEFT JOIN carrier_profiles cp ON cp.user_id = q.carrier_id
WHERE q.buy_request_id = $1 AND q.status <> 'withdrawn'
ORDER BY q.price ASC, q.created_at ASC
`

type ListShippingQuotesForBuyRequestRow struct {
	ID            int32              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	CarrierID     int32              `json:"carrier_id"`
	SellAuctionID pgtype.Int4        `json:"sell_auction_id"`
	BuyRequestID  pgtype.Int4        `json:"buy_request_id"`
	OrderID       pgtype.Int4        `json:"order_id"`
	Price         pgtype.Numeric     `json:"price"`
	Notes         pgtype.Text        `json:"notes"`
	Status        string             `json:"status"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CarrierName   string             `json:"carrier_name"`
	CarrierPhone  pgtype.Text        `json:"carrier_phone"`
	CarrierLogo   pgtype.Text        `json:"carrier_logo"`
	CarrierNotes  pgtype.Text        `json:"carrier_notes"`
}

func (q *Queries) ListShippingQuotesForBuyRequest(ctx context.Context, buyRequestID pgtype.Int4) ([]ListShippingQuotesForBuyRequestRow, error) {
	rows, err := q.db.Query(ctx, listShippingQuotesForBuyRequest, buyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShippingQuotesForBuyRequestRow
	for rows.Next() {
		var i ListShippingQuotesForBuyRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CarrierID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.OrderID,
			&i.Price,
			&i.Notes,
			&i.Status,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CarrierName,
			&i.CarrierPhone,
			&i.CarrierLogo,
			&i.CarrierNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingQuotesForOrder = `-- name: ListShippingQuotesForOrder :many

SELECT q.id, q.public_id, q.carrier_id, q.sell_auction_id, q.buy_request_id, q.order_id, q.price, q.notes, q.status, q.accepted_at, q.created_at, q.updated_at, u.name AS carrier_name, u.phone AS carrier_phone,
       cp.logo_url AS carrier_logo, cp.notes AS carrier_notes
FROM shipping_quotes q
JOIN users u ON u.id = q.carrier_id
LEFT JOIN carrier_profiles cp ON cp.user_id = q.carrier_id
WHERE q.order_id = $1 AND q.status <> 'withdrawn'
ORDER BY q.price ASC, q.created_at ASC
`

type ListShippingQuotesForOrderRow struct {
	ID            int32              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	CarrierID     int32              `json:"carrier_id"`
	SellAuctionID pgtype.Int4        `json:"sell_auction_id"`
	BuyRequestID  pgtype.Int4        `json:"buy_request_id"`
	OrderID       pgtype.Int4        `json:"order_id"`
	Price         pgtype.Numeric     `json:"price"`
	Notes         pgtype.Text        `json:"notes"`
	Status        string             `json:"status"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CarrierName   string             `json:"carrier_name"`
	CarrierPhone  pgtype.Text        `json:"carrier_phone"`
	CarrierLogo   pgtype.Text        `json:"carrier_logo"`
	CarrierNotes  pgtype.Text        `json:"carrier_notes"`
}

// Merchant-facing.
func (q *Queries) ListShippingQuotesForOrder(ctx context.Context, orderID pgtype.Int4) ([]ListShippingQuotesForOrderRow, error) {
	rows, err := q.db.Query(ctx, listShippingQuotesForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShippingQuotesForOrderRow
	for rows.Next() {
		var i ListShippingQuotesForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CarrierID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.OrderID,
			&i.Price,
			&i.Notes,
			&i.Status,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CarrierName,
			&i.CarrierPhone,
			&i.CarrierLogo,
			&i.CarrierNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingQuotesForSellAuction = `-- name: ListShippingQuotesForSellAuction :many
SELECT q.id, q.public_id, q.carrier_id, q.sell_auction_id, q.buy_request_id, q.order_id, q.price, q.notes, q.status, q.accepted_at, q.created_at, q.updated_at, u.name AS carrier_name, u.phone AS carrier_phone,
       cp.logo_url AS carrier_logo, cp.notes AS carrier_notes
FROM shipping_quotes q
JOIN users u ON u.id = q.carrier_id
LEFT JOIN carrier_profiles cp ON cp.user_id = q.carrier_id
WHERE q.sell_auction_id = $1 AND q.status <> 'withdrawn'
ORDER BY q.price ASC, q.created_at ASC
`

type ListShippingQuotesForSellAuctionRow struct {
	ID            int32              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	CarrierID     int32              `json:"carrier_id"`
	SellAuctionID pgtype.Int4        `json:"sell_auction_id"`
	BuyRequestID  pgtype.Int4        `json:"buy_request_id"`
	OrderID       pgtype.Int4        `json:"order_id"`
	Price         pgtype.Numeric     `json:"price"`
	Notes         pgtype.Text        `json:"notes"`
	Status        string             `json:"status"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CarrierName   string             `json:"carrier_name"`
	CarrierPhone  pgtype.Text        `json:"carrier_phone"`
	CarrierLogo   pgtype.Text        `json:"carrier_logo"`
	CarrierNotes  pgtype.Text        `json:"carrier_notes"`
}

func (q *Queries) ListShippingQuotesForSellAuction(ctx context.Context, sellAuctionID pgtype.Int4) ([]ListShippingQuotesForSellAuctionRow, error) {
	rows, err := q.db.Query(ctx, listShippingQuotesForSellAuction, sellAuctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShippingQuotesForSellAuctionRow
	for rows.Next() {
		var i ListShippingQuotesForSellAuctionRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CarrierID,
			&i.SellAuctionID,
			&i.BuyRequestID,
			&i.OrderID,
			&i.Price,
			&i.Notes,
			&i.Status,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CarrierName,
			&i.CarrierPhone,
			&i.CarrierLogo,
			&i.CarrierNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectShippingQuote = `-- name: RejectShippingQuote :one
UPDATE shipping_quotes
SET status = 'rejected', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at
`

func (q *Queries) RejectShippingQuote(ctx context.Context, id int32) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, rejectShippingQuote, id)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectSiblingShippingQuotes = `-- name: RejectSiblingShippingQuotes :many
UPDATE shipping_quotes
SET status = 'rejected', updated_at = NOW()
WHERE id <> $1::int
  AND status = 'pending'
  AND (
      ($2::int > 0 AND order_id = $2::int)
      OR ($3::int > 0 AND sell_auction_id = $3::int)
      OR ($4::int > 0 AND buy_request_id = $4::int)
  )
RETURNING id, carrier_id, public_id
`

type RejectSiblingShippingQuotesParams struct {
	AcceptedID    int32 `json:"accepted_id"`
	OrderID       int32 `json:"order_id"`
	SellAuctionID int32 `json:"sell_auction_id"`
	BuyRequestID  int32 `json:"buy_request_id"`
}

type RejectSiblingShippingQuotesRow struct {
	ID        int32       `json:"id"`
	CarrierID int32       `json:"carrier_id"`
	PublicID  pgtype.UUID `json:"public_id"`
}

// Accepting one answers the rest. Returns the losers so each can be told, which
// is the difference between a carrier knowing where it stands and being ignored.
func (q *Queries) RejectSiblingShippingQuotes(ctx context.Context, arg RejectSiblingShippingQuotesParams) ([]RejectSiblingShippingQuotesRow, error) {
	rows, err := q.db.Query(ctx, rejectSiblingShippingQuotes,
		arg.AcceptedID,
		arg.OrderID,
		arg.SellAuctionID,
		arg.BuyRequestID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RejectSiblingShippingQuotesRow
	for rows.Next() {
		var i RejectSiblingShippingQuotesRow
		if err := rows.Scan(&i.ID, &i.CarrierID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawShippingQuote = `-- name: WithdrawShippingQuote :one
UPDATE shipping_quotes
SET status = 'withdrawn', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, public_id, carrier_id, sell_auction_id, buy_request_id, order_id, price, notes, status, accepted_at, created_at, updated_at
`

// Only a quote nobody has answered yet: withdrawing an accepted one would strip
// a carrier off a deal the merchant has already committed to.
func (q *Queries) WithdrawShippingQuote(ctx context.Context, id int32) (ShippingQuote, error) {
	row := q.db.QueryRow(ctx, withdrawShippingQuote, id)
	var i ShippingQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CarrierID,
		&i.SellAuctionID,
		&i.BuyRequestID,
		&i.OrderID,
		&i.Price,
		&i.Notes,
		&i.Status,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
