// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSubscription = `-- name: CreateUserSubscription :one
INSERT INTO user_subscriptions (
    user_id, tier_name, started_at, expires_at, is_active, is_primary
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tier_name, started_at, expires_at, auctions_created_this_month, requests_created_this_month, bids_placed_this_month, offers_made_this_month, month_reset_at, is_active, is_primary, created_at, updated_at
`

type CreateUserSubscriptionParams struct {
	UserID    int32              `json:"user_id"`
	TierName  string             `json:"tier_name"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  bool               `json:"is_active"`
	IsPrimary bool               `json:"is_primary"`
}

func (q *Queries) CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, createUserSubscription,
		arg.UserID,
		arg.TierName,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.IsActive,
		arg.IsPrimary,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierName,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAllUserSubscriptions = `-- name: DeactivateAllUserSubscriptions :exec
UPDATE user_subscriptions
SET is_active  = FALSE,
    is_primary = FALSE,
    updated_at = NOW()
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) DeactivateAllUserSubscriptions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deactivateAllUserSubscriptions, userID)
	return err
}

const getAllUserSubscriptions = `-- name: GetAllUserSubscriptions :many
SELECT us.id, us.user_id, us.tier_name, us.started_at, us.expires_at, us.auctions_created_this_month, us.requests_created_this_month, us.bids_placed_this_month, us.offers_made_this_month, us.month_reset_at, us.is_active, us.is_primary, us.created_at, us.updated_at, st.tier_name, st.price_egp, st.price_usd, st.max_sell_auctions_per_month, st.max_buy_requests_per_month, st.max_bids_per_month, st.max_offers_per_month, st.can_create_sell_auctions, st.can_create_buy_requests, st.can_place_bids, st.can_make_offers, st.priority_support, st.display_name_ar, st.display_name_en, st.description_ar, st.description_en, st.created_at, st.updated_at
FROM user_subscriptions us
JOIN subscription_tiers st ON us.tier_name = st.tier_name
WHERE us.user_id = $1
ORDER BY us.is_active DESC, st.price_egp DESC
`

type GetAllUserSubscriptionsRow struct {
	ID                       int32              `json:"id"`
	UserID                   int32              `json:"user_id"`
	TierName                 string             `json:"tier_name"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	AuctionsCreatedThisMonth int32              `json:"auctions_created_this_month"`
	RequestsCreatedThisMonth int32              `json:"requests_created_this_month"`
	BidsPlacedThisMonth      int32              `json:"bids_placed_this_month"`
	OffersMadeThisMonth      int32              `json:"offers_made_this_month"`
	MonthResetAt             pgtype.Timestamptz `json:"month_reset_at"`
	IsActive                 bool               `json:"is_active"`
	IsPrimary                bool               `json:"is_primary"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	TierName_2               string             `json:"tier_name_2"`
	PriceEgp                 pgtype.Numeric     `json:"price_egp"`
	PriceUsd                 pgtype.Numeric     `json:"price_usd"`
	MaxSellAuctionsPerMonth  pgtype.Int4        `json:"max_sell_auctions_per_month"`
	MaxBuyRequestsPerMonth   pgtype.Int4        `json:"max_buy_requests_per_month"`
	MaxBidsPerMonth          pgtype.Int4        `json:"max_bids_per_month"`
	MaxOffersPerMonth        pgtype.Int4        `json:"max_offers_per_month"`
	CanCreateSellAuctions    bool               `json:"can_create_sell_auctions"`
	CanCreateBuyRequests     bool               `json:"can_create_buy_requests"`
	CanPlaceBids             bool               `json:"can_place_bids"`
	CanMakeOffers            bool               `json:"can_make_offers"`
	PrioritySupport          bool               `json:"priority_support"`
	DisplayNameAr            string             `json:"display_name_ar"`
	DisplayNameEn            string             `json:"display_name_en"`
	DescriptionAr            pgtype.Text        `json:"description_ar"`
	DescriptionEn            pgtype.Text        `json:"description_en"`
	CreatedAt_2              pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2              pgtype.Timestamptz `json:"updated_at_2"`
}

// Admin: lists ALL subscriptions for a user, active or not.
func (q *Queries) GetAllUserSubscriptions(ctx context.Context, userID int32) ([]GetAllUserSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getAllUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserSubscriptionsRow
	for rows.Next() {
		var i GetAllUserSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierName,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.AuctionsCreatedThisMonth,
			&i.RequestsCreatedThisMonth,
			&i.BidsPlacedThisMonth,
			&i.OffersMadeThisMonth,
			&i.MonthResetAt,
			&i.IsActive,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TierName_2,
			&i.PriceEgp,
			&i.PriceUsd,
			&i.MaxSellAuctionsPerMonth,
			&i.MaxBuyRequestsPerMonth,
			&i.MaxBidsPerMonth,
			&i.MaxOffersPerMonth,
			&i.CanCreateSellAuctions,
			&i.CanCreateBuyRequests,
			&i.CanPlaceBids,
			&i.CanMakeOffers,
			&i.PrioritySupport,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionTiers = `-- name: GetSubscriptionTiers :many
SELECT tier_name, price_egp, price_usd, max_sell_auctions_per_month, max_buy_requests_per_month, max_bids_per_month, max_offers_per_month, can_create_sell_auctions, can_create_buy_requests, can_place_bids, can_make_offers, priority_support, display_name_ar, display_name_en, description_ar, description_en, created_at, updated_at FROM subscription_tiers ORDER BY price_egp ASC
`

func (q *Queries) GetSubscriptionTiers(ctx context.Context) ([]SubscriptionTier, error) {
	rows, err := q.db.Query(ctx, getSubscriptionTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionTier
	for rows.Next() {
		var i SubscriptionTier
		if err := rows.Scan(
			&i.TierName,
			&i.PriceEgp,
			&i.PriceUsd,
			&i.MaxSellAuctionsPerMonth,
			&i.MaxBuyRequestsPerMonth,
			&i.MaxBidsPerMonth,
			&i.MaxOffersPerMonth,
			&i.CanCreateSellAuctions,
			&i.CanCreateBuyRequests,
			&i.CanPlaceBids,
			&i.CanMakeOffers,
			&i.PrioritySupport,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscriptionByID = `-- name: GetUserSubscriptionByID :one
SELECT id, user_id, tier_name, started_at, expires_at, auctions_created_this_month, requests_created_this_month, bids_placed_this_month, offers_made_this_month, month_reset_at, is_active, is_primary, created_at, updated_at FROM user_subscriptions WHERE id = $1
`

func (q *Queries) GetUserSubscriptionByID(ctx context.Context, id int32) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionByID, id)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierName,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscriptionByUserAndTier = `-- name: GetUserSubscriptionByUserAndTier :one
SELECT id, user_id, tier_name, started_at, expires_at, auctions_created_this_month, requests_created_this_month, bids_placed_this_month, offers_made_this_month, month_reset_at, is_active, is_primary, created_at, updated_at FROM user_subscriptions
WHERE user_id = $1 AND tier_name = $2
`

type GetUserSubscriptionByUserAndTierParams struct {
	UserID   int32  `json:"user_id"`
	TierName string `json:"tier_name"`
}

func (q *Queries) GetUserSubscriptionByUserAndTier(ctx context.Context, arg GetUserSubscriptionByUserAndTierParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionByUserAndTier, arg.UserID, arg.TierName)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierName,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSubscriptions = `-- name: GetUserSubscriptions :many
SELECT us.id, us.user_id, us.tier_name, us.started_at, us.expires_at, us.auctions_created_this_month, us.requests_created_this_month, us.bids_placed_this_month, us.offers_made_this_month, us.month_reset_at, us.is_active, us.is_primary, us.created_at, us.updated_at, st.tier_name, st.price_egp, st.price_usd, st.max_sell_auctions_per_month, st.max_buy_requests_per_month, st.max_bids_per_month, st.max_offers_per_month, st.can_create_sell_auctions, st.can_create_buy_requests, st.can_place_bids, st.can_make_offers, st.priority_support, st.display_name_ar, st.display_name_en, st.description_ar, st.description_en, st.created_at, st.updated_at 
FROM user_subscriptions us
JOIN subscription_tiers st ON us.tier_name = st.tier_name
WHERE us.user_id = $1 AND us.is_active = TRUE
ORDER BY st.price_egp DESC
`

type GetUserSubscriptionsRow struct {
	ID                       int32              `json:"id"`
	UserID                   int32              `json:"user_id"`
	TierName                 string             `json:"tier_name"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	AuctionsCreatedThisMonth int32              `json:"auctions_created_this_month"`
	RequestsCreatedThisMonth int32              `json:"requests_created_this_month"`
	BidsPlacedThisMonth      int32              `json:"bids_placed_this_month"`
	OffersMadeThisMonth      int32              `json:"offers_made_this_month"`
	MonthResetAt             pgtype.Timestamptz `json:"month_reset_at"`
	IsActive                 bool               `json:"is_active"`
	IsPrimary                bool               `json:"is_primary"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	TierName_2               string             `json:"tier_name_2"`
	PriceEgp                 pgtype.Numeric     `json:"price_egp"`
	PriceUsd                 pgtype.Numeric     `json:"price_usd"`
	MaxSellAuctionsPerMonth  pgtype.Int4        `json:"max_sell_auctions_per_month"`
	MaxBuyRequestsPerMonth   pgtype.Int4        `json:"max_buy_requests_per_month"`
	MaxBidsPerMonth          pgtype.Int4        `json:"max_bids_per_month"`
	MaxOffersPerMonth        pgtype.Int4        `json:"max_offers_per_month"`
	CanCreateSellAuctions    bool               `json:"can_create_sell_auctions"`
	CanCreateBuyRequests     bool               `json:"can_create_buy_requests"`
	CanPlaceBids             bool               `json:"can_place_bids"`
	CanMakeOffers            bool               `json:"can_make_offers"`
	PrioritySupport          bool               `json:"priority_support"`
	DisplayNameAr            string             `json:"display_name_ar"`
	DisplayNameEn            string             `json:"display_name_en"`
	DescriptionAr            pgtype.Text        `json:"description_ar"`
	DescriptionEn            pgtype.Text        `json:"description_en"`
	CreatedAt_2              pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2              pgtype.Timestamptz `json:"updated_at_2"`
}

func (q *Queries) GetUserSubscriptions(ctx context.Context, userID int32) ([]GetUserSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSubscriptionsRow
	for rows.Next() {
		var i GetUserSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierName,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.AuctionsCreatedThisMonth,
			&i.RequestsCreatedThisMonth,
			&i.BidsPlacedThisMonth,
			&i.OffersMadeThisMonth,
			&i.MonthResetAt,
			&i.IsActive,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TierName_2,
			&i.PriceEgp,
			&i.PriceUsd,
			&i.MaxSellAuctionsPerMonth,
			&i.MaxBuyRequestsPerMonth,
			&i.MaxBidsPerMonth,
			&i.MaxOffersPerMonth,
			&i.CanCreateSellAuctions,
			&i.CanCreateBuyRequests,
			&i.CanPlaceBids,
			&i.CanMakeOffers,
			&i.PrioritySupport,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithSubscription = `-- name: GetUserWithSubscription :one
SELECT
    u.id as user_id,
    u.status as user_status,
    u.suspended_until as user_suspended_until,
    u.suspension_reason as user_suspension_reason,
    u.banned_reason as user_banned_reason,
    u.public_id,
    us.id as subscription_id,
    us.tier_name,
    us.is_active as sub_is_active,
    us.expires_at as sub_expires_at,
    us.auctions_created_this_month,
    us.requests_created_this_month,
    us.bids_placed_this_month,
    us.offers_made_this_month,
    us.month_reset_at,
    st.can_create_sell_auctions,
    st.can_create_buy_requests,
    st.can_place_bids,
    st.can_make_offers,
    st.max_sell_auctions_per_month,
    st.max_buy_requests_per_month,
    st.max_bids_per_month,
    st.max_offers_per_month,
    st.price_egp,
    st.display_name_ar
FROM users u
LEFT JOIN user_subscriptions us ON u.id = us.user_id 
    AND us.is_active = TRUE
    AND (us.expires_at IS NULL OR us.expires_at > NOW())
LEFT JOIN subscription_tiers st ON us.tier_name = st.tier_name
WHERE u.id = $1
ORDER BY us.is_primary DESC NULLS LAST, st.price_egp DESC NULLS LAST
LIMIT 1
`

type GetUserWithSubscriptionRow struct {
	UserID                   int32              `json:"user_id"`
	UserStatus               string             `json:"user_status"`
	UserSuspendedUntil       pgtype.Timestamptz `json:"user_suspended_until"`
	UserSuspensionReason     pgtype.Text        `json:"user_suspension_reason"`
	UserBannedReason         pgtype.Text        `json:"user_banned_reason"`
	PublicID                 pgtype.UUID        `json:"public_id"`
	SubscriptionID           pgtype.Int4        `json:"subscription_id"`
	TierName                 pgtype.Text        `json:"tier_name"`
	SubIsActive              pgtype.Bool        `json:"sub_is_active"`
	SubExpiresAt             pgtype.Timestamptz `json:"sub_expires_at"`
	AuctionsCreatedThisMonth pgtype.Int4        `json:"auctions_created_this_month"`
	RequestsCreatedThisMonth pgtype.Int4        `json:"requests_created_this_month"`
	BidsPlacedThisMonth      pgtype.Int4        `json:"bids_placed_this_month"`
	OffersMadeThisMonth      pgtype.Int4        `json:"offers_made_this_month"`
	MonthResetAt             pgtype.Timestamptz `json:"month_reset_at"`
	CanCreateSellAuctions    pgtype.Bool        `json:"can_create_sell_auctions"`
	CanCreateBuyRequests     pgtype.Bool        `json:"can_create_buy_requests"`
	CanPlaceBids             pgtype.Bool        `json:"can_place_bids"`
	CanMakeOffers            pgtype.Bool        `json:"can_make_offers"`
	MaxSellAuctionsPerMonth  pgtype.Int4        `json:"max_sell_auctions_per_month"`
	MaxBuyRequestsPerMonth   pgtype.Int4        `json:"max_buy_requests_per_month"`
	MaxBidsPerMonth          pgtype.Int4        `json:"max_bids_per_month"`
	MaxOffersPerMonth        pgtype.Int4        `json:"max_offers_per_month"`
	PriceEgp                 pgtype.Numeric     `json:"price_egp"`
	DisplayNameAr            pgtype.Text        `json:"display_name_ar"`
}

// Get user info with their highest active subscription in one query
func (q *Queries) GetUserWithSubscription(ctx context.Context, id int32) (GetUserWithSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getUserWithSubscription, id)
	var i GetUserWithSubscriptionRow
	err := row.Scan(
		&i.UserID,
		&i.UserStatus,
		&i.UserSuspendedUntil,
		&i.UserSuspensionReason,
		&i.UserBannedReason,
		&i.PublicID,
		&i.SubscriptionID,
		&i.TierName,
		&i.SubIsActive,
		&i.SubExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.CanCreateSellAuctions,
		&i.CanCreateBuyRequests,
		&i.CanPlaceBids,
		&i.CanMakeOffers,
		&i.MaxSellAuctionsPerMonth,
		&i.MaxBuyRequestsPerMonth,
		&i.MaxBidsPerMonth,
		&i.MaxOffersPerMonth,
		&i.PriceEgp,
		&i.DisplayNameAr,
	)
	return i, err
}

const incrementAuctionCount = `-- name: IncrementAuctionCount :exec
UPDATE user_subscriptions 
SET auctions_created_this_month = auctions_created_this_month + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementAuctionCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementAuctionCount, id)
	return err
}

const incrementBidCount = `-- name: IncrementBidCount :exec
UPDATE user_subscriptions 
SET bids_placed_this_month = bids_placed_this_month + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementBidCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementBidCount, id)
	return err
}

const incrementOfferCount = `-- name: IncrementOfferCount :exec
UPDATE user_subscriptions 
SET offers_made_this_month = offers_made_this_month + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementOfferCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementOfferCount, id)
	return err
}

const incrementRequestCount = `-- name: IncrementRequestCount :exec
UPDATE user_subscriptions 
SET requests_created_this_month = requests_created_this_month + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementRequestCount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementRequestCount, id)
	return err
}

const reactivateUserSubscription = `-- name: ReactivateUserSubscription :one
UPDATE user_subscriptions
SET is_active  = TRUE,
    started_at = $3,
    expires_at = $4,
    is_primary = $5,
    updated_at = NOW()
WHERE user_id = $1 AND tier_name = $2
RETURNING id, user_id, tier_name, started_at, expires_at, auctions_created_this_month, requests_created_this_month, bids_placed_this_month, offers_made_this_month, month_reset_at, is_active, is_primary, created_at, updated_at
`

type ReactivateUserSubscriptionParams struct {
	UserID    int32              `json:"user_id"`
	TierName  string             `json:"tier_name"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsPrimary bool               `json:"is_primary"`
}

func (q *Queries) ReactivateUserSubscription(ctx context.Context, arg ReactivateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, reactivateUserSubscription,
		arg.UserID,
		arg.TierName,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.IsPrimary,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierName,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetMonthlyCounts = `-- name: ResetMonthlyCounts :exec
UPDATE user_subscriptions 
SET auctions_created_this_month = 0,
    requests_created_this_month = 0,
    bids_placed_this_month = 0,
    offers_made_this_month = 0,
    month_reset_at = NOW(),
    updated_at = NOW()
WHERE month_reset_at < DATE_TRUNC('month', NOW())
`

func (q *Queries) ResetMonthlyCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetMonthlyCounts)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :one
UPDATE user_subscriptions
SET started_at = COALESCE($1,  started_at),
    expires_at = COALESCE($2,  expires_at),
    is_active  = COALESCE($3,   is_active),
    is_primary = COALESCE($4,  is_primary),
    updated_at = NOW()
WHERE id = $5
RETURNING id, user_id, tier_name, started_at, expires_at, auctions_created_this_month, requests_created_this_month, bids_placed_this_month, offers_made_this_month, month_reset_at, is_active, is_primary, created_at, updated_at
`

type UpdateUserSubscriptionParams struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  pgtype.Bool        `json:"is_active"`
	IsPrimary pgtype.Bool        `json:"is_primary"`
	ID        int32              `json:"id"`
}

// NOTE: clearing expires_at to NULL is not supported by COALESCE(narg, expires_at).
//
//	For perpetual subscriptions, send a far-future date from the frontend.
func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, updateUserSubscription,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.IsActive,
		arg.IsPrimary,
		arg.ID,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierName,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
