// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: supply_offers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptSupplyOffer = `-- name: AcceptSupplyOffer :exec
UPDATE supply_offers SET is_accepted = TRUE, accepted_at = NOW() WHERE id = $1
`

func (q *Queries) AcceptSupplyOffer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, acceptSupplyOffer, id)
	return err
}

const countActiveSupplyOffersBySupplier = `-- name: CountActiveSupplyOffersBySupplier :one
SELECT COUNT(*) FROM supply_offers so
JOIN buy_requests br ON br.id = so.buy_request_id
WHERE so.supplier_id = $1 AND br.status = 'active'
`

func (q *Queries) CountActiveSupplyOffersBySupplier(ctx context.Context, supplierID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSupplyOffersBySupplier, supplierID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSupplyOffersByUser = `-- name: CountActiveSupplyOffersByUser :one
SELECT COUNT(*) FROM supply_offers so
JOIN buy_requests br ON br.id = so.buy_request_id
WHERE so.supplier_id = $1 AND br.status = 'active'
`

func (q *Queries) CountActiveSupplyOffersByUser(ctx context.Context, supplierID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSupplyOffersByUser, supplierID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupplyOffersByRequest = `-- name: CountSupplyOffersByRequest :one
SELECT COUNT(*) FROM supply_offers WHERE buy_request_id = $1
`

func (q *Queries) CountSupplyOffersByRequest(ctx context.Context, buyRequestID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSupplyOffersByRequest, buyRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplyOffer = `-- name: CreateSupplyOffer :one
INSERT INTO supply_offers (buy_request_id, supplier_id, price_per_unit, offered_quantity, supplier_region_name, supplier_fake_name, request_title, request_quantity, request_unit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, public_id, buy_request_id, supplier_id, price_per_unit, offered_quantity, is_accepted, accepted_at, created_at, supplier_region_name, supplier_fake_name, request_title, request_quantity, request_unit, is_not_chosen
`

type CreateSupplyOfferParams struct {
	BuyRequestID       int32          `json:"buy_request_id"`
	SupplierID         int32          `json:"supplier_id"`
	PricePerUnit       pgtype.Numeric `json:"price_per_unit"`
	OfferedQuantity    pgtype.Numeric `json:"offered_quantity"`
	SupplierRegionName string         `json:"supplier_region_name"`
	SupplierFakeName   string         `json:"supplier_fake_name"`
	RequestTitle       string         `json:"request_title"`
	RequestQuantity    pgtype.Numeric `json:"request_quantity"`
	RequestUnit        string         `json:"request_unit"`
}

func (q *Queries) CreateSupplyOffer(ctx context.Context, arg CreateSupplyOfferParams) (SupplyOffer, error) {
	row := q.db.QueryRow(ctx, createSupplyOffer,
		arg.BuyRequestID,
		arg.SupplierID,
		arg.PricePerUnit,
		arg.OfferedQuantity,
		arg.SupplierRegionName,
		arg.SupplierFakeName,
		arg.RequestTitle,
		arg.RequestQuantity,
		arg.RequestUnit,
	)
	var i SupplyOffer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BuyRequestID,
		&i.SupplierID,
		&i.PricePerUnit,
		&i.OfferedQuantity,
		&i.IsAccepted,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.SupplierRegionName,
		&i.SupplierFakeName,
		&i.RequestTitle,
		&i.RequestQuantity,
		&i.RequestUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getSupplyOfferByID = `-- name: GetSupplyOfferByID :one
SELECT id, public_id, buy_request_id, supplier_id, price_per_unit, offered_quantity, is_accepted, accepted_at, created_at, supplier_region_name, supplier_fake_name, request_title, request_quantity, request_unit, is_not_chosen FROM supply_offers WHERE id = $1
`

func (q *Queries) GetSupplyOfferByID(ctx context.Context, id int32) (SupplyOffer, error) {
	row := q.db.QueryRow(ctx, getSupplyOfferByID, id)
	var i SupplyOffer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BuyRequestID,
		&i.SupplierID,
		&i.PricePerUnit,
		&i.OfferedQuantity,
		&i.IsAccepted,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.SupplierRegionName,
		&i.SupplierFakeName,
		&i.RequestTitle,
		&i.RequestQuantity,
		&i.RequestUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getSupplyOfferByPublicID = `-- name: GetSupplyOfferByPublicID :one
SELECT id, public_id, buy_request_id, supplier_id, price_per_unit, offered_quantity, is_accepted, accepted_at, created_at, supplier_region_name, supplier_fake_name, request_title, request_quantity, request_unit, is_not_chosen FROM supply_offers WHERE public_id = $1
`

func (q *Queries) GetSupplyOfferByPublicID(ctx context.Context, publicID pgtype.UUID) (SupplyOffer, error) {
	row := q.db.QueryRow(ctx, getSupplyOfferByPublicID, publicID)
	var i SupplyOffer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BuyRequestID,
		&i.SupplierID,
		&i.PricePerUnit,
		&i.OfferedQuantity,
		&i.IsAccepted,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.SupplierRegionName,
		&i.SupplierFakeName,
		&i.RequestTitle,
		&i.RequestQuantity,
		&i.RequestUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getSupplyOfferByRequestAndSupplier = `-- name: GetSupplyOfferByRequestAndSupplier :one
SELECT id, public_id, buy_request_id, supplier_id, price_per_unit, offered_quantity, is_accepted, accepted_at, created_at, supplier_region_name, supplier_fake_name, request_title, request_quantity, request_unit, is_not_chosen FROM supply_offers WHERE buy_request_id = $1 AND supplier_id = $2
`

type GetSupplyOfferByRequestAndSupplierParams struct {
	BuyRequestID int32 `json:"buy_request_id"`
	SupplierID   int32 `json:"supplier_id"`
}

func (q *Queries) GetSupplyOfferByRequestAndSupplier(ctx context.Context, arg GetSupplyOfferByRequestAndSupplierParams) (SupplyOffer, error) {
	row := q.db.QueryRow(ctx, getSupplyOfferByRequestAndSupplier, arg.BuyRequestID, arg.SupplierID)
	var i SupplyOffer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BuyRequestID,
		&i.SupplierID,
		&i.PricePerUnit,
		&i.OfferedQuantity,
		&i.IsAccepted,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.SupplierRegionName,
		&i.SupplierFakeName,
		&i.RequestTitle,
		&i.RequestQuantity,
		&i.RequestUnit,
		&i.IsNotChosen,
	)
	return i, err
}

const getUnacceptedSupplierIDsForRequest = `-- name: GetUnacceptedSupplierIDsForRequest :many
SELECT DISTINCT supplier_id
FROM supply_offers
WHERE buy_request_id = $1
  AND is_accepted = FALSE
`

func (q *Queries) GetUnacceptedSupplierIDsForRequest(ctx context.Context, buyRequestID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUnacceptedSupplierIDsForRequest, buyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var supplier_id int32
		if err := rows.Scan(&supplier_id); err != nil {
			return nil, err
		}
		items = append(items, supplier_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcceptedOffersByRequest = `-- name: ListAcceptedOffersByRequest :many
SELECT id, public_id, buy_request_id, supplier_id, price_per_unit, offered_quantity, is_accepted, accepted_at, created_at, supplier_region_name, supplier_fake_name, request_title, request_quantity, request_unit, is_not_chosen FROM supply_offers WHERE buy_request_id = $1 AND is_accepted = TRUE
`

func (q *Queries) ListAcceptedOffersByRequest(ctx context.Context, buyRequestID int32) ([]SupplyOffer, error) {
	rows, err := q.db.Query(ctx, listAcceptedOffersByRequest, buyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplyOffer
	for rows.Next() {
		var i SupplyOffer
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.BuyRequestID,
			&i.SupplierID,
			&i.PricePerUnit,
			&i.OfferedQuantity,
			&i.IsAccepted,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.SupplierRegionName,
			&i.SupplierFakeName,
			&i.RequestTitle,
			&i.RequestQuantity,
			&i.RequestUnit,
			&i.IsNotChosen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplyOffersByRequest = `-- name: ListSupplyOffersByRequest :many
SELECT 
    so.id, so.public_id, so.buy_request_id, so.supplier_id, so.price_per_unit, so.offered_quantity, so.is_accepted, so.accepted_at, so.created_at, so.supplier_region_name, so.supplier_fake_name, so.request_title, so.request_quantity, so.request_unit, so.is_not_chosen,
    so.supplier_fake_name as supplier_name,
    so.supplier_region_name as supplier_region
FROM supply_offers so 
WHERE so.buy_request_id = $1
ORDER BY so.price_per_unit ASC, so.created_at ASC
`

type ListSupplyOffersByRequestRow struct {
	ID                 int32              `json:"id"`
	PublicID           pgtype.UUID        `json:"public_id"`
	BuyRequestID       int32              `json:"buy_request_id"`
	SupplierID         int32              `json:"supplier_id"`
	PricePerUnit       pgtype.Numeric     `json:"price_per_unit"`
	OfferedQuantity    pgtype.Numeric     `json:"offered_quantity"`
	IsAccepted         bool               `json:"is_accepted"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SupplierRegionName string             `json:"supplier_region_name"`
	SupplierFakeName   string             `json:"supplier_fake_name"`
	RequestTitle       string             `json:"request_title"`
	RequestQuantity    pgtype.Numeric     `json:"request_quantity"`
	RequestUnit        string             `json:"request_unit"`
	IsNotChosen        bool               `json:"is_not_chosen"`
	SupplierName       string             `json:"supplier_name"`
	SupplierRegion     string             `json:"supplier_region"`
}

func (q *Queries) ListSupplyOffersByRequest(ctx context.Context, buyRequestID int32) ([]ListSupplyOffersByRequestRow, error) {
	rows, err := q.db.Query(ctx, listSupplyOffersByRequest, buyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplyOffersByRequestRow
	for rows.Next() {
		var i ListSupplyOffersByRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.BuyRequestID,
			&i.SupplierID,
			&i.PricePerUnit,
			&i.OfferedQuantity,
			&i.IsAccepted,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.SupplierRegionName,
			&i.SupplierFakeName,
			&i.RequestTitle,
			&i.RequestQuantity,
			&i.RequestUnit,
			&i.IsNotChosen,
			&i.SupplierName,
			&i.SupplierRegion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplyOffersBySupplier = `-- name: ListSupplyOffersBySupplier :many
SELECT so.id, so.public_id, so.buy_request_id, so.supplier_id, so.price_per_unit, so.offered_quantity, so.is_accepted, so.accepted_at, so.created_at, so.supplier_region_name, so.supplier_fake_name, so.request_title, so.request_quantity, so.request_unit, so.is_not_chosen, br.title as request_title, br.public_id as request_public_id,
       br.status as request_status, br.end_time as request_end_time
FROM supply_offers so
JOIN buy_requests br ON br.id = so.buy_request_id
WHERE so.supplier_id = $1
ORDER BY so.created_at DESC LIMIT $2 OFFSET $3
`

type ListSupplyOffersBySupplierParams struct {
	SupplierID int32 `json:"supplier_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListSupplyOffersBySupplierRow struct {
	ID                 int32              `json:"id"`
	PublicID           pgtype.UUID        `json:"public_id"`
	BuyRequestID       int32              `json:"buy_request_id"`
	SupplierID         int32              `json:"supplier_id"`
	PricePerUnit       pgtype.Numeric     `json:"price_per_unit"`
	OfferedQuantity    pgtype.Numeric     `json:"offered_quantity"`
	IsAccepted         bool               `json:"is_accepted"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SupplierRegionName string             `json:"supplier_region_name"`
	SupplierFakeName   string             `json:"supplier_fake_name"`
	RequestTitle       string             `json:"request_title"`
	RequestQuantity    pgtype.Numeric     `json:"request_quantity"`
	RequestUnit        string             `json:"request_unit"`
	IsNotChosen        bool               `json:"is_not_chosen"`
	RequestTitle_2     string             `json:"request_title_2"`
	RequestPublicID    pgtype.UUID        `json:"request_public_id"`
	RequestStatus      string             `json:"request_status"`
	RequestEndTime     pgtype.Timestamptz `json:"request_end_time"`
}

func (q *Queries) ListSupplyOffersBySupplier(ctx context.Context, arg ListSupplyOffersBySupplierParams) ([]ListSupplyOffersBySupplierRow, error) {
	rows, err := q.db.Query(ctx, listSupplyOffersBySupplier, arg.SupplierID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplyOffersBySupplierRow
	for rows.Next() {
		var i ListSupplyOffersBySupplierRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.BuyRequestID,
			&i.SupplierID,
			&i.PricePerUnit,
			&i.OfferedQuantity,
			&i.IsAccepted,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.SupplierRegionName,
			&i.SupplierFakeName,
			&i.RequestTitle,
			&i.RequestQuantity,
			&i.RequestUnit,
			&i.IsNotChosen,
			&i.RequestTitle_2,
			&i.RequestPublicID,
			&i.RequestStatus,
			&i.RequestEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotChosenSupplyOffers = `-- name: MarkNotChosenSupplyOffers :exec
UPDATE supply_offers SET is_not_chosen = TRUE
WHERE buy_request_id = $1 AND is_accepted = FALSE
`

func (q *Queries) MarkNotChosenSupplyOffers(ctx context.Context, buyRequestID int32) error {
	_, err := q.db.Exec(ctx, markNotChosenSupplyOffers, buyRequestID)
	return err
}

const sumAcceptedQuantityByRequest = `-- name: SumAcceptedQuantityByRequest :one
SELECT COALESCE(SUM(offered_quantity), 0)::DECIMAL(10,2) FROM supply_offers
WHERE buy_request_id = $1 AND is_accepted = TRUE
`

func (q *Queries) SumAcceptedQuantityByRequest(ctx context.Context, buyRequestID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumAcceptedQuantityByRequest, buyRequestID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}
