// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, token_hash, device_info, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, is_current, device_info, ip_address, created_at, expires_at, last_used_at
`

type CreateSessionParams struct {
	UserID     int32              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsCurrent,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, is_current, device_info, ip_address, created_at, expires_at, last_used_at FROM user_sessions WHERE token_hash = $1 AND is_current = TRUE
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsCurrent,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const invalidateSession = `-- name: InvalidateSession :exec
UPDATE user_sessions SET is_current = FALSE WHERE id = $1
`

func (q *Queries) InvalidateSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, invalidateSession, id)
	return err
}

const invalidateUserSessions = `-- name: InvalidateUserSessions :exec
UPDATE user_sessions SET is_current = FALSE WHERE user_id = $1 AND is_current = TRUE
`

func (q *Queries) InvalidateUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, invalidateUserSessions, userID)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE user_sessions SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, id)
	return err
}
