// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_documents.sql

package sqlc

import (
	"context"
)

const countUserDocuments = `-- name: CountUserDocuments :one
SELECT COUNT(*) FROM user_documents WHERE user_id = $1
`

func (q *Queries) CountUserDocuments(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDocuments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserDocument = `-- name: CreateUserDocument :one
INSERT INTO user_documents (user_id, document_type, file_path)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, document_type) DO UPDATE SET file_path = $3, uploaded_at = NOW()
RETURNING id, user_id, document_type, file_path, uploaded_at
`

type CreateUserDocumentParams struct {
	UserID       int32  `json:"user_id"`
	DocumentType string `json:"document_type"`
	FilePath     string `json:"file_path"`
}

func (q *Queries) CreateUserDocument(ctx context.Context, arg CreateUserDocumentParams) (UserDocument, error) {
	row := q.db.QueryRow(ctx, createUserDocument, arg.UserID, arg.DocumentType, arg.FilePath)
	var i UserDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentType,
		&i.FilePath,
		&i.UploadedAt,
	)
	return i, err
}

const getMissingDocumentTypes = `-- name: GetMissingDocumentTypes :many
SELECT unnest(ARRAY['business_license','national_id','tax_card'])
EXCEPT
SELECT document_type FROM user_documents WHERE user_id = $1
`

func (q *Queries) GetMissingDocumentTypes(ctx context.Context, userID int32) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getMissingDocumentTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var unnest interface{}
		if err := rows.Scan(&unnest); err != nil {
			return nil, err
		}
		items = append(items, unnest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDocuments = `-- name: GetUserDocuments :many
SELECT id, user_id, document_type, file_path, uploaded_at FROM user_documents WHERE user_id = $1
`

func (q *Queries) GetUserDocuments(ctx context.Context, userID int32) ([]UserDocument, error) {
	rows, err := q.db.Query(ctx, getUserDocuments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDocument
	for rows.Next() {
		var i UserDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentType,
			&i.FilePath,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
