// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserInterest = `-- name: AddUserInterest :exec
INSERT INTO user_interests (user_id, interest_id) VALUES ($1, $2)
ON CONFLICT (user_id, interest_id) DO NOTHING
`

type AddUserInterestParams struct {
	UserID     int32 `json:"user_id"`
	InterestID int32 `json:"interest_id"`
}

func (q *Queries) AddUserInterest(ctx context.Context, arg AddUserInterestParams) error {
	_, err := q.db.Exec(ctx, addUserInterest, arg.UserID, arg.InterestID)
	return err
}

const banUser = `-- name: BanUser :execrows
UPDATE users
SET status = 'banned',
    banned_at = NOW(),
    banned_reason = $2,
    suspension_reason = NULL,
    suspended_until = NULL,
    status_changed_by_admin_id = $3,
    status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status <> 'banned'
`

type BanUserParams struct {
	ID                     int32       `json:"id"`
	BannedReason           pgtype.Text `json:"banned_reason"`
	StatusChangedByAdminID pgtype.Int4 `json:"status_changed_by_admin_id"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, banUser, arg.ID, arg.BannedReason, arg.StatusChangedByAdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearUserOTP = `-- name: ClearUserOTP :exec
UPDATE users SET otp_hash = NULL, otp_expires_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ClearUserOTP(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, clearUserOTP, id)
	return err
}

const countAllUsersAnyStatus = `-- name: CountAllUsersAnyStatus :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAllUsersAnyStatus(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsersAnyStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByStatus = `-- name: CountUsersByStatus :one
SELECT COUNT(*) FROM users WHERE status = $1
`

func (q *Queries) CountUsersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone, password_hash, name, job_id, region_id, status, signup_source, supplies_to_retail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key
`

type CreateUserParams struct {
	Email            string      `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	PasswordHash     pgtype.Text `json:"password_hash"`
	Name             string      `json:"name"`
	JobID            pgtype.Int4 `json:"job_id"`
	RegionID         pgtype.Int4 `json:"region_id"`
	Status           string      `json:"status"`
	SignupSource     string      `json:"signup_source"`
	SuppliesToRetail bool        `json:"supplies_to_retail"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Name,
		arg.JobID,
		arg.RegionID,
		arg.Status,
		arg.SignupSource,
		arg.SuppliesToRetail,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
	)
	return i, err
}

const deleteUserInterests = `-- name: DeleteUserInterests :exec
DELETE FROM user_interests WHERE user_id = $1
`

func (q *Queries) DeleteUserInterests(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserInterests, userID)
	return err
}

const ensureSeedUser = `-- name: EnsureSeedUser :one
INSERT INTO users (
    email, name, status,
    email_verified, email_verified_at,
    phone, phone_verified,
    region_id, job_id,
    latitude, longitude
) VALUES (
    $1, $2, 'active',
    TRUE, NOW(),
    $3, TRUE,
    $4, $5,
    $6, $7
)
ON CONFLICT (email) DO UPDATE SET
    status = 'active',
    email_verified = TRUE,
    phone_verified = TRUE,
    updated_at = NOW()
RETURNING id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key
`

type EnsureSeedUserParams struct {
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Phone     pgtype.Text    `json:"phone"`
	RegionID  pgtype.Int4    `json:"region_id"`
	JobID     pgtype.Int4    `json:"job_id"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
}

func (q *Queries) EnsureSeedUser(ctx context.Context, arg EnsureSeedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureSeedUser,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.RegionID,
		arg.JobID,
		arg.Latitude,
		arg.Longitude,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
	)
	return i, err
}

const getActiveUsersByInterest = `-- name: GetActiveUsersByInterest :many
SELECT u.id FROM users u
JOIN user_interests ui ON ui.user_id = u.id
WHERE ui.interest_id = $1::int
  AND u.status = 'active'
  AND u.id != $2::int
  AND ($3::int = 0 OR u.region_id = $3::int)
  -- Nobody should be told about a post their feed hides: retailers cannot fill a
  -- buy request, and they only see sell posts from supply-side merchants.
  AND ($4::bool = false OR u.job_key <> 'retailer')
`

type GetActiveUsersByInterestParams struct {
	InterestID       int32 `json:"interest_id"`
	ExcludeUserID    int32 `json:"exclude_user_id"`
	FilterRegionID   int32 `json:"filter_region_id"`
	ExcludeRetailers bool  `json:"exclude_retailers"`
}

func (q *Queries) GetActiveUsersByInterest(ctx context.Context, arg GetActiveUsersByInterestParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getActiveUsersByInterest,
		arg.InterestID,
		arg.ExcludeUserID,
		arg.FilterRegionID,
		arg.ExcludeRetailers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key FROM users WHERE public_id = $1
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
	)
	return i, err
}

const getUserInterestIDs = `-- name: GetUserInterestIDs :many
SELECT interest_id FROM user_interests WHERE user_id = $1
`

func (q *Queries) GetUserInterestIDs(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUserInterestIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var interest_id int32
		if err := rows.Scan(&interest_id); err != nil {
			return nil, err
		}
		items = append(items, interest_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInterests = `-- name: GetUserInterests :many
SELECT i.id, i.name_ar, i.name_en FROM interests i
JOIN user_interests ui ON ui.interest_id = i.id
WHERE ui.user_id = $1
`

type GetUserInterestsRow struct {
	ID     int32       `json:"id"`
	NameAr string      `json:"name_ar"`
	NameEn pgtype.Text `json:"name_en"`
}

func (q *Queries) GetUserInterests(ctx context.Context, userID int32) ([]GetUserInterestsRow, error) {
	rows, err := q.db.Query(ctx, getUserInterests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInterestsRow
	for rows.Next() {
		var i GetUserInterestsRow
		if err := rows.Scan(&i.ID, &i.NameAr, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStatusByID = `-- name: GetUserStatusByID :one
SELECT status, suspension_reason, banned_reason FROM users WHERE id = $1
`

type GetUserStatusByIDRow struct {
	Status           string      `json:"status"`
	SuspensionReason pgtype.Text `json:"suspension_reason"`
	BannedReason     pgtype.Text `json:"banned_reason"`
}

func (q *Queries) GetUserStatusByID(ctx context.Context, id int32) (GetUserStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserStatusByID, id)
	var i GetUserStatusByIDRow
	err := row.Scan(&i.Status, &i.SuspensionReason, &i.BannedReason)
	return i, err
}

const getUserStatusData = `-- name: GetUserStatusData :one
SELECT id, status, latitude, longitude, interests_count
FROM users WHERE id = $1
`

type GetUserStatusDataRow struct {
	ID             int32          `json:"id"`
	Status         string         `json:"status"`
	Latitude       pgtype.Numeric `json:"latitude"`
	Longitude      pgtype.Numeric `json:"longitude"`
	InterestsCount int32          `json:"interests_count"`
}

func (q *Queries) GetUserStatusData(ctx context.Context, id int32) (GetUserStatusDataRow, error) {
	row := q.db.QueryRow(ctx, getUserStatusData, id)
	var i GetUserStatusDataRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Latitude,
		&i.Longitude,
		&i.InterestsCount,
	)
	return i, err
}

const getUserSubscriptionStatus = `-- name: GetUserSubscriptionStatus :one
SELECT
    us.id,
    us.user_id,
    us.tier_name,
    us.started_at,
    us.expires_at,
    us.auctions_created_this_month,
    us.requests_created_this_month,
    us.bids_placed_this_month,
    us.offers_made_this_month,
    us.month_reset_at,
    us.is_active,
    us.is_primary,
    us.created_at,
    us.updated_at,
    st.max_sell_auctions_per_month,
    st.max_buy_requests_per_month,
    st.max_bids_per_month,
    st.max_offers_per_month,
    st.can_create_sell_auctions,
    st.can_create_buy_requests,
    st.can_place_bids,
    st.can_make_offers
FROM user_subscriptions us
JOIN subscription_tiers st ON st.tier_name = us.tier_name
WHERE us.user_id = $1 AND us.is_active = TRUE
ORDER BY us.is_primary DESC
LIMIT 1
`

type GetUserSubscriptionStatusRow struct {
	ID                       int32              `json:"id"`
	UserID                   int32              `json:"user_id"`
	TierName                 string             `json:"tier_name"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	AuctionsCreatedThisMonth int32              `json:"auctions_created_this_month"`
	RequestsCreatedThisMonth int32              `json:"requests_created_this_month"`
	BidsPlacedThisMonth      int32              `json:"bids_placed_this_month"`
	OffersMadeThisMonth      int32              `json:"offers_made_this_month"`
	MonthResetAt             pgtype.Timestamptz `json:"month_reset_at"`
	IsActive                 bool               `json:"is_active"`
	IsPrimary                bool               `json:"is_primary"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	MaxSellAuctionsPerMonth  pgtype.Int4        `json:"max_sell_auctions_per_month"`
	MaxBuyRequestsPerMonth   pgtype.Int4        `json:"max_buy_requests_per_month"`
	MaxBidsPerMonth          pgtype.Int4        `json:"max_bids_per_month"`
	MaxOffersPerMonth        pgtype.Int4        `json:"max_offers_per_month"`
	CanCreateSellAuctions    bool               `json:"can_create_sell_auctions"`
	CanCreateBuyRequests     bool               `json:"can_create_buy_requests"`
	CanPlaceBids             bool               `json:"can_place_bids"`
	CanMakeOffers            bool               `json:"can_make_offers"`
}

func (q *Queries) GetUserSubscriptionStatus(ctx context.Context, userID int32) (GetUserSubscriptionStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionStatus, userID)
	var i GetUserSubscriptionStatusRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierName,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.AuctionsCreatedThisMonth,
		&i.RequestsCreatedThisMonth,
		&i.BidsPlacedThisMonth,
		&i.OffersMadeThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxSellAuctionsPerMonth,
		&i.MaxBuyRequestsPerMonth,
		&i.MaxBidsPerMonth,
		&i.MaxOffersPerMonth,
		&i.CanCreateSellAuctions,
		&i.CanCreateBuyRequests,
		&i.CanPlaceBids,
		&i.CanMakeOffers,
	)
	return i, err
}

const getUserWithRegion = `-- name: GetUserWithRegion :one
SELECT
    u.id, u.public_id, u.email, u.phone, u.phone_verified, u.password_hash, u.email_verified, u.email_verified_at, u.otp_hash, u.otp_expires_at, u.name, u.role, u.job_id, u.region_id, u.status, u.rejection_reason, u.latitude, u.longitude, u.fcm_token, u.created_at, u.updated_at, u.interests_count, u.region_name, u.job_name, u.signup_source, u.suspended_until, u.suspension_reason, u.banned_at, u.banned_reason, u.status_changed_by_admin_id, u.status_changed_at, u.supplies_to_retail, u.password_changed_at, u.job_key,
    COALESCE(r.name_ar, '') as region_name
FROM users u
LEFT JOIN regions r ON r.id = u.region_id
WHERE u.id = $1
`

type GetUserWithRegionRow struct {
	ID                     int32              `json:"id"`
	PublicID               pgtype.UUID        `json:"public_id"`
	Email                  string             `json:"email"`
	Phone                  pgtype.Text        `json:"phone"`
	PhoneVerified          bool               `json:"phone_verified"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	EmailVerified          bool               `json:"email_verified"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	OtpHash                pgtype.Text        `json:"otp_hash"`
	OtpExpiresAt           pgtype.Timestamptz `json:"otp_expires_at"`
	Name                   string             `json:"name"`
	Role                   pgtype.Text        `json:"role"`
	JobID                  pgtype.Int4        `json:"job_id"`
	RegionID               pgtype.Int4        `json:"region_id"`
	Status                 string             `json:"status"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	Latitude               pgtype.Numeric     `json:"latitude"`
	Longitude              pgtype.Numeric     `json:"longitude"`
	FcmToken               pgtype.Text        `json:"fcm_token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	InterestsCount         int32              `json:"interests_count"`
	RegionName             string             `json:"region_name"`
	JobName                string             `json:"job_name"`
	SignupSource           string             `json:"signup_source"`
	SuspendedUntil         pgtype.Timestamptz `json:"suspended_until"`
	SuspensionReason       pgtype.Text        `json:"suspension_reason"`
	BannedAt               pgtype.Timestamptz `json:"banned_at"`
	BannedReason           pgtype.Text        `json:"banned_reason"`
	StatusChangedByAdminID pgtype.Int4        `json:"status_changed_by_admin_id"`
	StatusChangedAt        pgtype.Timestamptz `json:"status_changed_at"`
	SuppliesToRetail       bool               `json:"supplies_to_retail"`
	PasswordChangedAt      pgtype.Timestamptz `json:"password_changed_at"`
	JobKey                 string             `json:"job_key"`
	RegionName_2           string             `json:"region_name_2"`
}

func (q *Queries) GetUserWithRegion(ctx context.Context, id int32) (GetUserWithRegionRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRegion, id)
	var i GetUserWithRegionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
		&i.RegionName_2,
	)
	return i, err
}

const getUserWithRegionAndJob = `-- name: GetUserWithRegionAndJob :one
SELECT
    u.id, u.public_id, u.email, u.phone, u.phone_verified, u.password_hash, u.email_verified, u.email_verified_at, u.otp_hash, u.otp_expires_at, u.name, u.role, u.job_id, u.region_id, u.status, u.rejection_reason, u.latitude, u.longitude, u.fcm_token, u.created_at, u.updated_at, u.interests_count, u.region_name, u.job_name, u.signup_source, u.suspended_until, u.suspension_reason, u.banned_at, u.banned_reason, u.status_changed_by_admin_id, u.status_changed_at, u.supplies_to_retail, u.password_changed_at, u.job_key,
    COALESCE(r.name_ar, '') as region_name,
    COALESCE(j.name_ar, '') as job_name
FROM users u
LEFT JOIN regions r ON r.id = u.region_id
LEFT JOIN jobs j ON j.id = u.job_id
WHERE u.id = $1
`

type GetUserWithRegionAndJobRow struct {
	ID                     int32              `json:"id"`
	PublicID               pgtype.UUID        `json:"public_id"`
	Email                  string             `json:"email"`
	Phone                  pgtype.Text        `json:"phone"`
	PhoneVerified          bool               `json:"phone_verified"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	EmailVerified          bool               `json:"email_verified"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	OtpHash                pgtype.Text        `json:"otp_hash"`
	OtpExpiresAt           pgtype.Timestamptz `json:"otp_expires_at"`
	Name                   string             `json:"name"`
	Role                   pgtype.Text        `json:"role"`
	JobID                  pgtype.Int4        `json:"job_id"`
	RegionID               pgtype.Int4        `json:"region_id"`
	Status                 string             `json:"status"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	Latitude               pgtype.Numeric     `json:"latitude"`
	Longitude              pgtype.Numeric     `json:"longitude"`
	FcmToken               pgtype.Text        `json:"fcm_token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	InterestsCount         int32              `json:"interests_count"`
	RegionName             string             `json:"region_name"`
	JobName                string             `json:"job_name"`
	SignupSource           string             `json:"signup_source"`
	SuspendedUntil         pgtype.Timestamptz `json:"suspended_until"`
	SuspensionReason       pgtype.Text        `json:"suspension_reason"`
	BannedAt               pgtype.Timestamptz `json:"banned_at"`
	BannedReason           pgtype.Text        `json:"banned_reason"`
	StatusChangedByAdminID pgtype.Int4        `json:"status_changed_by_admin_id"`
	StatusChangedAt        pgtype.Timestamptz `json:"status_changed_at"`
	SuppliesToRetail       bool               `json:"supplies_to_retail"`
	PasswordChangedAt      pgtype.Timestamptz `json:"password_changed_at"`
	JobKey                 string             `json:"job_key"`
	RegionName_2           string             `json:"region_name_2"`
	JobName_2              string             `json:"job_name_2"`
}

func (q *Queries) GetUserWithRegionAndJob(ctx context.Context, id int32) (GetUserWithRegionAndJobRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRegionAndJob, id)
	var i GetUserWithRegionAndJobRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
		&i.RegionName_2,
		&i.JobName_2,
	)
	return i, err
}

const getUserWithRegionAndJobByPublicID = `-- name: GetUserWithRegionAndJobByPublicID :one
SELECT
    u.id, u.public_id, u.email, u.phone, u.phone_verified, u.password_hash, u.email_verified, u.email_verified_at, u.otp_hash, u.otp_expires_at, u.name, u.role, u.job_id, u.region_id, u.status, u.rejection_reason, u.latitude, u.longitude, u.fcm_token, u.created_at, u.updated_at, u.interests_count, u.region_name, u.job_name, u.signup_source, u.suspended_until, u.suspension_reason, u.banned_at, u.banned_reason, u.status_changed_by_admin_id, u.status_changed_at, u.supplies_to_retail, u.password_changed_at, u.job_key,
    COALESCE(r.name_ar, '') as region_name,
    COALESCE(j.name_ar, '') as job_name
FROM users u
LEFT JOIN regions r ON r.id = u.region_id
LEFT JOIN jobs j ON j.id = u.job_id
WHERE u.public_id = $1
`

type GetUserWithRegionAndJobByPublicIDRow struct {
	ID                     int32              `json:"id"`
	PublicID               pgtype.UUID        `json:"public_id"`
	Email                  string             `json:"email"`
	Phone                  pgtype.Text        `json:"phone"`
	PhoneVerified          bool               `json:"phone_verified"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	EmailVerified          bool               `json:"email_verified"`
	EmailVerifiedAt        pgtype.Timestamptz `json:"email_verified_at"`
	OtpHash                pgtype.Text        `json:"otp_hash"`
	OtpExpiresAt           pgtype.Timestamptz `json:"otp_expires_at"`
	Name                   string             `json:"name"`
	Role                   pgtype.Text        `json:"role"`
	JobID                  pgtype.Int4        `json:"job_id"`
	RegionID               pgtype.Int4        `json:"region_id"`
	Status                 string             `json:"status"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	Latitude               pgtype.Numeric     `json:"latitude"`
	Longitude              pgtype.Numeric     `json:"longitude"`
	FcmToken               pgtype.Text        `json:"fcm_token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	InterestsCount         int32              `json:"interests_count"`
	RegionName             string             `json:"region_name"`
	JobName                string             `json:"job_name"`
	SignupSource           string             `json:"signup_source"`
	SuspendedUntil         pgtype.Timestamptz `json:"suspended_until"`
	SuspensionReason       pgtype.Text        `json:"suspension_reason"`
	BannedAt               pgtype.Timestamptz `json:"banned_at"`
	BannedReason           pgtype.Text        `json:"banned_reason"`
	StatusChangedByAdminID pgtype.Int4        `json:"status_changed_by_admin_id"`
	StatusChangedAt        pgtype.Timestamptz `json:"status_changed_at"`
	SuppliesToRetail       bool               `json:"supplies_to_retail"`
	PasswordChangedAt      pgtype.Timestamptz `json:"password_changed_at"`
	JobKey                 string             `json:"job_key"`
	RegionName_2           string             `json:"region_name_2"`
	JobName_2              string             `json:"job_name_2"`
}

func (q *Queries) GetUserWithRegionAndJobByPublicID(ctx context.Context, publicID pgtype.UUID) (GetUserWithRegionAndJobByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRegionAndJobByPublicID, publicID)
	var i GetUserWithRegionAndJobByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Phone,
		&i.PhoneVerified,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.Name,
		&i.Role,
		&i.JobID,
		&i.RegionID,
		&i.Status,
		&i.RejectionReason,
		&i.Latitude,
		&i.Longitude,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestsCount,
		&i.RegionName,
		&i.JobName,
		&i.SignupSource,
		&i.SuspendedUntil,
		&i.SuspensionReason,
		&i.BannedAt,
		&i.BannedReason,
		&i.StatusChangedByAdminID,
		&i.StatusChangedAt,
		&i.SuppliesToRetail,
		&i.PasswordChangedAt,
		&i.JobKey,
		&i.RegionName_2,
		&i.JobName_2,
	)
	return i, err
}

const hasActiveSubscription = `-- name: HasActiveSubscription :one
SELECT EXISTS(
    SELECT 1 FROM user_subscriptions
    WHERE user_id = $1
      AND is_active = TRUE
      AND (expires_at IS NULL OR expires_at > NOW())
) AS has_active
`

func (q *Queries) HasActiveSubscription(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSubscription, userID)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const lazyRestoreExpiredSuspension = `-- name: LazyRestoreExpiredSuspension :execrows
UPDATE users
SET status = 'active',
    suspension_reason = NULL,
    suspended_until = NULL,
    status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'suspended'
  AND suspended_until IS NOT NULL
  AND suspended_until <= NOW()
`

func (q *Queries) LazyRestoreExpiredSuspension(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, lazyRestoreExpiredSuspension, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllUsersAnyStatus = `-- name: ListAllUsersAnyStatus :many
SELECT id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllUsersAnyStatusParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllUsersAnyStatus(ctx context.Context, arg ListAllUsersAnyStatusParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsersAnyStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Email,
			&i.Phone,
			&i.PhoneVerified,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.OtpHash,
			&i.OtpExpiresAt,
			&i.Name,
			&i.Role,
			&i.JobID,
			&i.RegionID,
			&i.Status,
			&i.RejectionReason,
			&i.Latitude,
			&i.Longitude,
			&i.FcmToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InterestsCount,
			&i.RegionName,
			&i.JobName,
			&i.SignupSource,
			&i.SuspendedUntil,
			&i.SuspensionReason,
			&i.BannedAt,
			&i.BannedReason,
			&i.StatusChangedByAdminID,
			&i.StatusChangedAt,
			&i.SuppliesToRetail,
			&i.PasswordChangedAt,
			&i.JobKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStatus = `-- name: ListUsersByStatus :many
SELECT id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key FROM users WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Email,
			&i.Phone,
			&i.PhoneVerified,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.OtpHash,
			&i.OtpExpiresAt,
			&i.Name,
			&i.Role,
			&i.JobID,
			&i.RegionID,
			&i.Status,
			&i.RejectionReason,
			&i.Latitude,
			&i.Longitude,
			&i.FcmToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InterestsCount,
			&i.RegionName,
			&i.JobName,
			&i.SignupSource,
			&i.SuspendedUntil,
			&i.SuspensionReason,
			&i.BannedAt,
			&i.BannedReason,
			&i.StatusChangedByAdminID,
			&i.StatusChangedAt,
			&i.SuppliesToRetail,
			&i.PasswordChangedAt,
			&i.JobKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, public_id, email, phone, phone_verified, password_hash, email_verified, email_verified_at, otp_hash, otp_expires_at, name, role, job_id, region_id, status, rejection_reason, latitude, longitude, fcm_token, created_at, updated_at, interests_count, region_name, job_name, signup_source, suspended_until, suspension_reason, banned_at, banned_reason, status_changed_by_admin_id, status_changed_at, supplies_to_retail, password_changed_at, job_key FROM users
WHERE ($3::text = '' OR
       email ILIKE '%' || $3::text || '%' OR
       phone ILIKE '%' || $3::text || '%' OR
       name  ILIKE '%' || $3::text || '%')
  AND ($4::text = '' OR status = $4::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Query  string `json:"query"`
	Status string `json:"status"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Limit,
		arg.Offset,
		arg.Query,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Email,
			&i.Phone,
			&i.PhoneVerified,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.OtpHash,
			&i.OtpExpiresAt,
			&i.Name,
			&i.Role,
			&i.JobID,
			&i.RegionID,
			&i.Status,
			&i.RejectionReason,
			&i.Latitude,
			&i.Longitude,
			&i.FcmToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InterestsCount,
			&i.RegionName,
			&i.JobName,
			&i.SignupSource,
			&i.SuspendedUntil,
			&i.SuspensionReason,
			&i.BannedAt,
			&i.BannedReason,
			&i.StatusChangedByAdminID,
			&i.StatusChangedAt,
			&i.SuppliesToRetail,
			&i.PasswordChangedAt,
			&i.JobKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersCount = `-- name: SearchUsersCount :one
SELECT COUNT(*) FROM users
WHERE ($1::text = '' OR
       email ILIKE '%' || $1::text || '%' OR
       phone ILIKE '%' || $1::text || '%' OR
       name  ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR status = $2::text)
`

type SearchUsersCountParams struct {
	Query  string `json:"query"`
	Status string `json:"status"`
}

func (q *Queries) SearchUsersCount(ctx context.Context, arg SearchUsersCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, searchUsersCount, arg.Query, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const suspendUser = `-- name: SuspendUser :execrows
UPDATE users
SET status = 'suspended',
    suspension_reason = $2,
    suspended_until = $3,
    status_changed_by_admin_id = $4,
    status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('banned')
`

type SuspendUserParams struct {
	ID                     int32              `json:"id"`
	SuspensionReason       pgtype.Text        `json:"suspension_reason"`
	SuspendedUntil         pgtype.Timestamptz `json:"suspended_until"`
	StatusChangedByAdminID pgtype.Int4        `json:"status_changed_by_admin_id"`
}

func (q *Queries) SuspendUser(ctx context.Context, arg SuspendUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendUser,
		arg.ID,
		arg.SuspensionReason,
		arg.SuspendedUntil,
		arg.StatusChangedByAdminID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unbanUser = `-- name: UnbanUser :execrows
UPDATE users
SET status = 'active',
    banned_at = NULL,
    banned_reason = NULL,
    status_changed_by_admin_id = $2,
    status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'banned'
`

type UnbanUserParams struct {
	ID                     int32       `json:"id"`
	StatusChangedByAdminID pgtype.Int4 `json:"status_changed_by_admin_id"`
}

func (q *Queries) UnbanUser(ctx context.Context, arg UnbanUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unbanUser, arg.ID, arg.StatusChangedByAdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unsuspendUser = `-- name: UnsuspendUser :execrows
UPDATE users
SET status = 'active',
    suspension_reason = NULL,
    suspended_until = NULL,
    status_changed_by_admin_id = $2,
    status_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'suspended'
`

type UnsuspendUserParams struct {
	ID                     int32       `json:"id"`
	StatusChangedByAdminID pgtype.Int4 `json:"status_changed_by_admin_id"`
}

func (q *Queries) UnsuspendUser(ctx context.Context, arg UnsuspendUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unsuspendUser, arg.ID, arg.StatusChangedByAdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserCachedNames = `-- name: UpdateUserCachedNames :exec
UPDATE users
SET 
    job_name = COALESCE((SELECT j.name_ar FROM jobs j WHERE j.id = $2), ''),
    job_key = COALESCE((SELECT j.key FROM jobs j WHERE j.id = $2), ''),
    region_name = COALESCE((SELECT r.name_ar FROM regions r WHERE r.id = $3), ''),
    updated_at = NOW()
WHERE users.id = $1
`

type UpdateUserCachedNamesParams struct {
	ID   int32 `json:"id"`
	ID_2 int32 `json:"id_2"`
	ID_3 int32 `json:"id_3"`
}

func (q *Queries) UpdateUserCachedNames(ctx context.Context, arg UpdateUserCachedNamesParams) error {
	_, err := q.db.Exec(ctx, updateUserCachedNames, arg.ID, arg.ID_2, arg.ID_3)
	return err
}

const updateUserFCMToken = `-- name: UpdateUserFCMToken :exec
UPDATE users SET fcm_token = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserFCMTokenParams struct {
	ID       int32       `json:"id"`
	FcmToken pgtype.Text `json:"fcm_token"`
}

func (q *Queries) UpdateUserFCMToken(ctx context.Context, arg UpdateUserFCMTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserFCMToken, arg.ID, arg.FcmToken)
	return err
}

const updateUserInterestsCount = `-- name: UpdateUserInterestsCount :exec
UPDATE users SET interests_count = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserInterestsCountParams struct {
	ID             int32 `json:"id"`
	InterestsCount int32 `json:"interests_count"`
}

func (q *Queries) UpdateUserInterestsCount(ctx context.Context, arg UpdateUserInterestsCountParams) error {
	_, err := q.db.Exec(ctx, updateUserInterestsCount, arg.ID, arg.InterestsCount)
	return err
}

const updateUserLocation = `-- name: UpdateUserLocation :exec
UPDATE users SET latitude = $2, longitude = $3, updated_at = NOW() WHERE id = $1
`

type UpdateUserLocationParams struct {
	ID        int32          `json:"id"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
}

func (q *Queries) UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error {
	_, err := q.db.Exec(ctx, updateUserLocation, arg.ID, arg.Latitude, arg.Longitude)
	return err
}

const updateUserOTP = `-- name: UpdateUserOTP :exec
UPDATE users SET otp_hash = $2, otp_expires_at = $3, updated_at = NOW() WHERE id = $1
`

type UpdateUserOTPParams struct {
	ID           int32              `json:"id"`
	OtpHash      pgtype.Text        `json:"otp_hash"`
	OtpExpiresAt pgtype.Timestamptz `json:"otp_expires_at"`
}

func (q *Queries) UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) error {
	_, err := q.db.Exec(ctx, updateUserOTP, arg.ID, arg.OtpHash, arg.OtpExpiresAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int32       `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET job_id = $2, region_id = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID       int32       `json:"id"`
	JobID    pgtype.Int4 `json:"job_id"`
	RegionID pgtype.Int4 `json:"region_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.JobID, arg.RegionID)
	return err
}

const updateUserProfileWithNames = `-- name: UpdateUserProfileWithNames :exec
UPDATE users
SET 
    job_id = $2,
    region_id = $3,
    job_name = COALESCE((SELECT j.name_ar FROM jobs j WHERE j.id = $2), ''),
    job_key = COALESCE((SELECT j.key FROM jobs j WHERE j.id = $2), ''),
    region_name = COALESCE((SELECT r.name_ar FROM regions r WHERE r.id = $3), ''),
    updated_at = NOW()
WHERE users.id = $1
`

type UpdateUserProfileWithNamesParams struct {
	ID       int32       `json:"id"`
	JobID    pgtype.Int4 `json:"job_id"`
	RegionID pgtype.Int4 `json:"region_id"`
}

func (q *Queries) UpdateUserProfileWithNames(ctx context.Context, arg UpdateUserProfileWithNamesParams) error {
	_, err := q.db.Exec(ctx, updateUserProfileWithNames, arg.ID, arg.JobID, arg.RegionID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}

const updateUserStatusWithReason = `-- name: UpdateUserStatusWithReason :exec
UPDATE users SET status = $2, rejection_reason = $3, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusWithReasonParams struct {
	ID              int32       `json:"id"`
	Status          string      `json:"status"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) UpdateUserStatusWithReason(ctx context.Context, arg UpdateUserStatusWithReasonParams) error {
	_, err := q.db.Exec(ctx, updateUserStatusWithReason, arg.ID, arg.Status, arg.RejectionReason)
	return err
}
